<?php
/**
 *  phtml for van/dashlet/overview
 */
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->

        <div class="row">
            <h3 class="col-md-8">
                VAN <small>dashboard & statistics</small>
            </h3>

        </div>
        <div class="row">&nbsp;</div>
        <!-- END PAGE HEADER-->
        <div class="row">
            <div class="col-md-12">
                <div class="widget widget-tabs">
                    <div class="widget-head dashboard-widget">
                        <ul>
                           
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/stocks">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-inventory-management"></i>
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">Stocks</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/vaccination">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-lims-campaign"></i>
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">Vaccination</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/wastage">
                                    <div class="dashboard-stat_custom">
                                        <i class="fa fa-trash-o" style="font-size:45px;color:red;padding-top: 20px"></i>
                                        
                                        <div style="float: right;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">Wastage</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/ccem">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-cold-chain"></i> 
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">CCEM</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/van">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-routine-immunization"></i> 
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">VAN</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>




                    <div class="widget-body">
                        <div class="tab-content">
                            <div class="tab-pane active">
                                <div class="row">
                                    <form method="post" name="ri" id="ri" action="">
                                        <div class="col-md-12 col-sm-12">
                                            <div id="sample_2_filter" class="dataTables_filter">                                                        
                                                <label><button class="btn btn-success" type="button" id="ri_btn" name="ri_btn" value="ri">GO</button></label>
                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                <label>Vaccines:
                                                    <select id="items" name="items" class="form-control input-inline">
                                                        <option value="" selected="selected">All</option> 
                                                        <option value="43">tOPV</option>   
                                                        <option value="40">BCG-20</option>   
                                                        <option value="26">Pneumococcal-2</option>   
                                                        <option value="6">Pentavalent-1</option>   
                                                        <option value="7">Measles-10</option>   
                                                        <option value="12">TT-20</option>   
                                                    </select>
                                                </label>
                                                <label>Month To:
                                                    <select id="month-to" name="month-to" class="form-control input-inline">
                                                        <option value="1">January</option>
                                                        <option value="2">February</option>
                                                        <option value="3" selected="selected">March</option>
                                                        <option value="4">April</option>
                                                        <option value="5">May</option>
                                                        <option value="6">June</option>
                                                        <option value="7">July</option>
                                                        <option value="8">August</option>
                                                        <option value="9">September</option>
                                                        <option value="10">October</option>
                                                        <option value="11">November</option>
                                                        <option value="12">December</option>  
                                                    </select>
                                                </label> 
                                                <label>Year To:
                                                    <select id="year-to" name="year-to" class="form-control input-inline">
                                                        <option value="2013">2013</option>
                                                        <option value="2014">2014</option>
                                                        <option value="2015">2015</option>
                                                        <option value="2016" selected="selected">2016</option>   
                                                    </select>
                                                </label>  
                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>

                                                <label>Month From:
                                                    <select id="month-from" name="month-from" class="form-control input-inline">
                                                        <option value="1">January</option>
                                                        <option value="2">February</option>
                                                        <option value="3">March</option>
                                                        <option value="4">April</option>
                                                        <option value="5">May</option>
                                                        <option value="6">June</option>
                                                        <option value="7">July</option>
                                                        <option value="8">August</option>
                                                        <option value="9">September</option>
                                                        <option value="10" selected="selected">October</option>
                                                        <option value="11">November</option>
                                                        <option value="12">December</option>  
                                                    </select>
                                                </label> 
                                                <label>Year From:
                                                    <select id="year-from" name="year-from" class="form-control input-inline">
                                                        <option value="2013">2013</option>
                                                        <option value="2014">2014</option>
                                                        <option value="2015" selected="selected">2015</option>
                                                        <option value="2016" >2016</option>   
                                                    </select>
                                                </label> 

                                                <label>District:
                                                    <select id="district" name="district" class="form-control input-inline">
                                                        <option value="1" selected="selected">Ghotki</option>
                                                    </select>
                                                </label> 
                                                <label>Province:
                                                    <select id="province" name="province" class="form-control input-inline">
                                                        <option value="2" selected="selected">Sindh</option>  
                                                    </select>
                                                </label> 
                                            </div>
                                        </div>
                                    </form>
                                </div>


                                <div class="row">
                                    <div class="col-md-6">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>Number of UCs Late Reported</h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">

                                                <?php
                                                        FC_SetRenderer('javascript');
                                                        echo renderChart($this->baseUrl() . "/FusionCharts/Charts/MSLine.swf", "", $this->xmlstore, "NumberOfUCsLateReported", '100%', 350, false, false);
                                                        ?>    
                                                <div style="clear:both;"></div>            

                                            </div>
                                        </div>
                                    </div>


                                    <div class="col-md-6">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>Number of Vaccinators</h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">

                                                <?php
                                                        FC_SetRenderer('javascript');
                                                        echo renderChart($this->baseUrl() . "/FusionCharts/Charts/Pie2d.swf", "", $this->xmlstore2, "NumberOfVaccinators", '100%', 350, false, false);
                                                        ?>    
                                                <div style="clear:both;"></div>            

                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>UC wise Reporting Rate</h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">
                                                <br>
                                                <table class="table table-striped table-bordered">
                                                    <caption><h4>District Ghotki Reporting Rate UCs(Oct-15 to Mar-16)</h4></caption>
                                                    <thead>
                                                        <tr>
                                                            <th>Month</th>
                                                            <th>Oct-15</th>
                                                            <th>Nov-15</th>
                                                            <th>Dec-15</th>
                                                            <th>Jan-15</th>
                                                            <th>Feb-15</th>
                                                            <th>Mar-15</th>

                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                            <th scope="row">Reporting Rate</th>
                                                            <td class="right">100%</td>
                                                            <td class="right">100%</td>
                                                            <td class="right">100%</td>
                                                            <td class="right">100%</td>
                                                            <td class="right">100%</td>
                                                            <td class="right">100%</td>
                                                        </tr>

                                                    </tbody>
                                                </table>
                                                <div style="clear:both;"></div>            

                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>Health facility wise Reporting Rate</h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">
                                                <br>
                                                <table class="table table-striped table-bordered">
                                                    <caption><h4>District Ghotki Reporting Rate - Health Facility(Oct-15 to Mar-16)</h4></caption>
                                                    <thead>
                                                        <tr>
                                                            <th>Month</th>
                                                            <th>Oct-15</th>
                                                            <th>Nov-15</th>
                                                            <th>Dec-15</th>
                                                            <th>Jan-15</th>
                                                            <th>Feb-15</th>
                                                            <th>Mar-15</th>

                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                            <th scope="row">Reporting Rate</th>
                                                            <td class="right">92%</td>
                                                            <td class="right">98%</td>
                                                            <td class="right">98%</td>
                                                            <td class="right">98%</td>
                                                            <td class="right">98%</td>
                                                            <td class="right">100%</td>
                                                        </tr>

                                                    </tbody>
                                                </table>
                                                <div style="clear:both;"></div>            

                                            </div>
                                        </div>
                                    </div>

                                </div>


                                <div class="row">

                                    <div class="col-md-6">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>Number of FIC (Fully Immunize Children)</h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">
                                                <br>
                                                <table class="table table-striped table-bordered">
                                                    <caption><h4>Children Vaccinated</h4></caption>
                                                    <thead>
                                                        <tr>
                                                            <th>District</th>
                                                            <th>(Oct-15) to (Dec-15)</th>
                                                            <th>(Jan-16) to (Mar-16)</th>
                                                            <th>Sum</th>

                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                            <th scope="row">Ghotki</th>
                                                            <td class="right">5,106</td>
                                                            <td class="right">9,478</td>
                                                            <td class="right">14,584</td>
                                                        </tr>

                                                    </tbody>
                                                </table>
                                                <div style="clear:both;"></div>            

                                            </div>
                                        </div>
                                    </div>


                                </div>


                            </div>
                        </div>
                    </div>


                </div>
                <!-- // Tabs END -->                
            </div>
        </div>
    </div>
</div>