<style>
    table{
        font-size: 11px;
    }
</style>
<?php
/**
 *  phtml for van/dashlet/van
 */
$selected_province = $this->selected_province;
$selected_district = $this->selected_district;
$selected_year = $this->selected_year;
$selected_month = $this->selected_month;
$selected_product = $this->selected_product;
$vaccines = $this->all_vaccines;


$district_stores_stock_status_percentage_result = $this->district_stores_stock_status_percentage_result;
$ucs_stock_status_percentage_result = $this->ucs_stock_status_percentage_result;
$pending_voucher_array = $this->pending_voucher_array;
$non_reconciled_vouchers_result = $this->non_reconciled_vouchers_result;
$proportion_of_adjustments_result = $this->proportion_of_adjustments_result;

$district_stores_stock_status_percentage_array = array();
$ucs_stock_status_percentage_array = array();

foreach ($vaccines as $item) {
    //district stock status
    $district_stores_stock_status_percentage_array[$item['item_id']]['item_name'] = $item['item_name'];
    $district_stores_stock_status_percentage_array[$item['item_id']]['understocked_percent'] = null;
    $district_stores_stock_status_percentage_array[$item['item_id']]['overstocked_percent'] = null;
    $district_stores_stock_status_percentage_array[$item['item_id']]['adequetlystocked_percent'] = null;

    //UC stock status
    $ucs_stock_status_percentage_array[$item['item_id']]['item_name'] = $item['item_name'];
    $ucs_stock_status_percentage_array[$item['item_id']]['understocked_percent'] = null;
    $ucs_stock_status_percentage_array[$item['item_id']]['overstocked_percent'] = null;
    $ucs_stock_status_percentage_array[$item['item_id']]['adequetlystocked_percent'] = null;

    //district stock status
    foreach ($district_stores_stock_status_percentage_result as $row) {
        if ($row['item_pack_size_id'] == $item['item_id']) {
            $district_stores_stock_status_percentage_array[$item['item_id']]['understocked_percent'] = $row['understocked_percent'];
            $district_stores_stock_status_percentage_array[$item['item_id']]['overstocked_percent'] = $row['overstocked_percent'];
            $district_stores_stock_status_percentage_array[$item['item_id']]['adequetlystocked_percent'] = $row['adequetlystocked_percent'];
        }
    }

    //UC stock status
    foreach ($ucs_stock_status_percentage_result as $row) {
        if ($row['item_pack_size_id'] == $item['item_id']) {
            $ucs_stock_status_percentage_array[$item['item_id']]['understocked_percent'] = $row['understocked_percent'];
            $ucs_stock_status_percentage_array[$item['item_id']]['overstocked_percent'] = $row['overstocked_percent'];
            $ucs_stock_status_percentage_array[$item['item_id']]['adequetlystocked_percent'] = $row['adequetlystocked_percent'];
        }
    }
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->

        <div class="row">
            <h3 class="col-md-8">
                VAN <small>dashboard & statistics</small>
            </h3>

        </div>
        <div class="row">&nbsp;</div>
        <!-- END PAGE HEADER-->
        <div class="row">
            <!-- // Tabs START -->  
            <div class="col-md-12">
                <div class="widget widget-tabs">
                    <div class="widget-head dashboard-widget">
                        <ul>
                            <li class="active">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/van">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-routine-immunization"></i> 
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">VAN</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/stocks">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-inventory-management"></i>
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">Stocks</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/vaccination">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-lims-campaign"></i>
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">Vaccination</div>
                                        </div>
                                    </div>
                                </a>
                            </li>

                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/wastage">
                                    <div class="dashboard-stat_custom">
                                        <i class="fa fa-trash-o" style="font-size:45px;color:red;padding-top: 20px"></i>
                                        <div style="float: right;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">Wastage</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/ccem">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-cold-chain"></i> 
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">CCEM</div>
                                        </div>
                                    </div>
                                </a>
                            </li>

                        </ul>
                    </div>
                    <div class="widget-body">
                        <div class="tab-content">
                            <div class="tab-pane active">
                                <div class="row">
                                    <form method="post" name="van-filters" id="van-filters" action="">
                                        <div class="col-md-12 col-sm-12">
                                            <div id="sample_2_filter" class="dataTables_filter">                                                        
                                                <label><button class="btn btn-success" type="submit" id="go-btn" name="go-btn">GO</button></label>
                                                <!--                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                                                                <label>Vaccines:
                                                                                                    <select id="items" name="items" class="form-control input-inline input-xsmall">
                                                                                                        <option value="" selected="selected">All</option> 
                                                <?php
//                                                        foreach ($vaccines as $vaccine) {
//                                                            
                                                ?>
                                                                                                            <option value = "<?php //echo $vaccine['item_id'] ?>" <?php
//                                                            if ($vaccine['item_id'] == $this->selected_product) {
//                                                                echo "selected='selected'";
//                                                            }
//                                                            
                                                ?>><?php //echo $vaccine['item_name'] ?></option>
                                                                                                                    //<?php
//                                                                }
                                                ?>   
                                                                                                    </select>
                                                                                                </label>-->
                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                <label>Month:
                                                    <select id="month" name="month" class="form-control input-inline input-xsmall">
                                                        <option value = "">Select Month</option>
                                                        <?php
                                                        $months = $this->all_months;
                                                        foreach ($months as $month) {
                                                            ?>
                                                            <option value = "<?php echo $month['month_code'] ?>" <?php
                                                            if ($month['month_code'] == $this->selected_month) {
                                                                echo "selected='selected'";
                                                            }
                                                            ?>><?php echo $month['month_name'] ?></option>
                                                                    <?php
                                                                }
                                                                ?>  
                                                    </select>
                                                </label> 
                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                <label>Year:
                                                    <select id="year" name="year" class="form-control input-inline input-xsmall">
                                                        <option value = "">Select Year</option>
                                                        <?php
                                                        $years = $this->years;
                                                        foreach ($years as $key => $value) {
                                                            ?>
                                                            <option value = "<?php echo $key ?>" <?php
                                                            if ($key == $this->selected_year) {
                                                                echo "selected='selected'";
                                                            }
                                                            ?>><?php echo $value ?></option>
                                                                    <?php
                                                                }
                                                                ?>
                                                    </select>
                                                </label> 
                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                <label>District:
                                                    <select id="district" name="district" class="form-control input-inline input-xsmall">
                                                        <option value = "">Select District</option>
                                                        <?php
                                                        $districts = $this->districts;
                                                        foreach ($districts as $district) {
                                                            ?>
                                                            <option value = "<?php echo $district['district_id'] ?>" <?php
                                                            if ($district['district_id'] == $this->selected_district) {
                                                                echo "selected='selected'";
                                                            }
                                                            ?>><?php echo $district['district_name'] ?></option>
                                                                    <?php
                                                                }
                                                                ?>
                                                    </select>
                                                </label> 
                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                <label>Province:
                                                    <select id="province" name="province" class="form-control input-inline input-xsmall">
                                                        <option value = "">Select Province</option>
                                                        <?php
                                                        $provinces = $this->provinces;
                                                        foreach ($provinces as $key => $value) {
                                                            ?>
                                                            <option value = "<?php echo $key ?>" selected = "selected"><?php echo $value ?></option>
                                                            <?php
                                                        }
                                                        ?>

                                                    </select>
                                                </label> 
                                            </div>
                                        </div>
                                    </form>
                                </div>


                                <div class="row">
                                    <div class="col-md-12">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>Stock outs</h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <?php
                                                        FC_SetRenderer('javascript');
                                                        echo renderChart($this->baseUrl() . "/FusionCharts/Charts/Pie2d.swf", "", $this->xmlstore, "Percentageofdistrictstoreshavingstockoutofvaccines", '100%', 350, false, false);
                                                        ?>  
                                                    </div>
                                                    <div class="col-md-6">
                                                        <?php
                                                        FC_SetRenderer('javascript');
                                                        echo renderChart($this->baseUrl() . "/FusionCharts/Charts/Column2D.swf", "", $this->xmlstore2, "PercentageofUCshavingstockoutofvaccineindistrictGhotki", '100%', 350, false, false);
                                                        ?>  
                                                    </div>
                                                </div>
                                                <div style="clear:both;"></div>            

                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <div class="row">

                                    <div class="col-md-12">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>Stock Status</h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <br>
                                                        <?php
                                                        echo "<table class='table table-striped table-bordered'>";
                                                        echo "<caption><h4>Percentage of district stores understocked, adequately stocked or overstocked of vaccine</h4></caption>";
                                                        echo "<thead>";
                                                        echo "<tr>";
                                                        echo "<th>Vaccine</th>";
                                                        echo "<th>Under Stocked</th>";
                                                        echo "<th>Over Stocked</th>";
                                                        echo "<th>Adequately Stocked</th>";
                                                        echo "</thead>";
                                                        echo "<tbody>";
                                                        foreach ($district_stores_stock_status_percentage_array as $row) {
                                                            echo "<tr>";
                                                            echo "<th>" . $row['item_name'] . "</th>";
                                                            echo "<td class='right'>" . $row['understocked_percent'] . "</td>";
                                                            echo "<td class='right'>" . $row['overstocked_percent'] . "</td>";
                                                            echo "<td class='right'>" . $row['adequetlystocked_percent'] . "</td>";
                                                            echo "</tr>";
                                                        }
                                                        echo "</tbody>";
                                                        echo "</table>";
                                                        ?>

                                                    </div>
                                                    <div class="col-md-6">
                                                        <br>
                                                        <?php
                                                        echo "<table class='table table-striped table-bordered'>";
                                                        echo "<caption><h4>Percentage of UCs understocked, adequately stocked or overstocked of vaccine</h4></caption>";
                                                        echo "<thead>";
                                                        echo "<tr>";
                                                        echo "<th>Vaccine</th>";
                                                        echo "<th>Under Stocked</th>";
                                                        echo "<th>Over Stocked</th>";
                                                        echo "<th>Adequately Stocked</th>";
                                                        echo "</thead>";
                                                        echo "<tbody>";
                                                        foreach ($ucs_stock_status_percentage_array as $row) {
                                                            echo "<tr>";
                                                            echo "<th>" . $row['item_name'] . "</th>";
                                                            echo "<td class='right'>" . $row['understocked_percent'] . "</td>";
                                                            echo "<td class='right'>" . $row['overstocked_percent'] . "</td>";
                                                            echo "<td class='right'>" . $row['adequetlystocked_percent'] . "</td>";
                                                            echo "</tr>";
                                                        }
                                                        echo "</tbody>";
                                                        echo "</table>";
                                                        ?>

                                                    </div>
                                                </div>
                                            </div>
                                            <div style="clear:both;"></div>            

                                        </div>
                                    </div>
                                </div>



                                <div class="row">
                                    <div class="col-md-6">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>vLMIS reconciliation</h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">

                                                <?php
                                                if (!empty($non_reconciled_vouchers_result)) {
                                                    FC_SetRenderer('javascript');
                                                    echo renderChart($this->baseUrl() . "/FusionCharts/Charts/MSBar2d.swf", "", $this->xmlstore5, "5", '100%', 350, false, false);
                                                } else {
                                                    echo "No data found";
                                                }
                                                ?>    
                                                <div style="clear:both;"></div>            

                                            </div>
                                        </div>
                                    </div>


                                    <div class="col-md-6">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>Pending vouchers</h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">

                                                <?php
                                                if (!empty($pending_voucher_array)) {
                                                    FC_SetRenderer('javascript');
                                                    echo renderChart($this->baseUrl() . "/FusionCharts/Charts/MSBar2D.swf", "", $this->xmlstore8, "8", '100%', 350, false, false);
                                                } else {
                                                    echo "No data found";
                                                }
                                                ?>   
                                                <div style="clear:both;"></div>            

                                            </div>
                                        </div>
                                    </div>


                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>Proportion of adjustments  </h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">

                                                <?php
                                                if (!empty($proportion_of_adjustments_result)) {
                                                    FC_SetRenderer('javascript');
                                                    echo renderChart($this->baseUrl() . "/FusionCharts/Charts/MSColumn2D.swf", "", $this->xmlstore7, "7", '100%', 350, false, false);
                                                } else {
                                                    echo "No data found";
                                                }
                                                ?>    

                                                <div style="clear:both;"></div>            

                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>FEFO</h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">

                                                <?php
                                                FC_SetRenderer('javascript');
                                                echo renderChart($this->baseUrl() . "/FusionCharts/Charts/MSColumn2D.swf", "", $this->xmlstore10, "10", '100%', 350, false, false);
                                                ?>   
                                                <div style="clear:both;"></div>            

                                            </div>
                                        </div>

                                    </div>

                                </div>

                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div data-toggle="collapse-widget" class="widget">
                                        <div class="widget-head">
                                            <h4 class="heading "><i></i>Changed VVM</h4>
                                        </div>
                                        <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">

                                            <?php
                                            FC_SetRenderer('javascript');
                                            echo renderChart($this->baseUrl() . "/FusionCharts/Charts/MSColumn2D.swf", "", $this->xmlstore9, "9", '100%', 350, false, false);
                                            ?>    
                                            <div style="clear:both;"></div>            

                                        </div>
                                    </div>
                                </div>



                            </div>

                        </div>
                    </div>
                </div>


            </div>
            <!-- // Tabs END -->                
        </div>
    </div>
</div>
</div>