<style>
    table{
        font-size: 11px;
    }
</style>
<?php
/**
 *  phtml for van/dashlet/wastage
 */
$period = $this->period;
$vaccines = $this->all_vaccines;

$selected_district = $this->selected_district;
$selected_district_name = "";
$selected_product = $this->selected_product;

$wastage_array = array();
$average_wastage_array = array();
$UCs_wasting_vaccines_array = array();
$average_ucs_array = array();


//
foreach ($vaccines as $item) {
    $wastage_array[$item['item_id']][] = $item['item_name'];
    $average_wastage_array[$item['item_id']]['item_name'] = $item['item_name'];

    $UCs_wasting_vaccines_array[$item['item_id']]['item_name'] = $item['item_name'];
    $average_ucs_array[$item['item_id']]['item_name'] = $item['item_name'];

    $count = 1;
    foreach ($period as $date) {
        $date_str = $date->format("Y-m");
        $wastage_array[$item['item_id']][$count] = null;

        $UCs_wasting_vaccines_array[$item['item_id']][$count] = null;

        $count++;
    }
}

$count = 1;
foreach ($period as $date) {
    $date_str = $date->format("Y-m");
    $month_array[] = date('M-y', strtotime($date_str));
    $start_date = date('Y-m-01', strtotime($date_str));
    $end_date = date('Y-m-t', strtotime($date_str));

    $query_result = $this->VanDashletViewHelper()->getWastageInDistrict($selected_district, $start_date, $end_date, $selected_product);

    foreach ($query_result as $row) {
        $wastage_array[$row['item_id']][$count] = $row['PercentWastage'];
        $selected_district_name = $row['location_name'];
    }

    $query_result2 = $this->VanDashletViewHelper()->getUCsWastingVaccinesAbovePermissibleLevel($selected_district, $start_date, $end_date, $selected_product);

    foreach ($query_result2 as $row2) {
        $UCs_wasting_vaccines_array[$row2['item_id']][$count] = $row2['NomberOfUcs'];
        //$selected_district_name = $row2['location_name'];
    }
    $count++;
}

?>
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->

        <div class="row">
            <h3 class="col-md-8">
                VAN <small>dashboard & statistics</small>
            </h3>

        </div>
        <div class="row">&nbsp;</div>
        <!-- END PAGE HEADER-->
        <div class="row">
            <div class="col-md-12">
                <!-- // Tabs START -->  
                <div class="widget widget-tabs">
                    <div class="widget-head dashboard-widget">
                        <ul>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/van">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-routine-immunization"></i> 
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">VAN</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/stocks">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-inventory-management"></i>
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">Stocks</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/vaccination">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-lims-campaign"></i>
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">Vaccination</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="active">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/wastage">
                                    <div class="dashboard-stat_custom">
                                        <i class="fa fa-trash-o" style="font-size:45px;color:red;padding-top: 20px"></i>

                                        <div style="float: right;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">Wastage</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/van/dashlet/ccem">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-cold-chain"></i> 
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1"></div>
                                            <div class="dashboard-title-2" style="padding-top: 20px">CCEM</div>
                                        </div>
                                    </div>
                                </a>
                            </li>

                        </ul>
                    </div>


                    <div class="widget-body">
                        <div class="tab-content">
                            <div class="tab-pane active">
                                <div class="row">
                                    <form method="post" name="van-filters" id="van-filters" action="">
                                        <div class="col-md-12 col-sm-12">
                                            <div id="sample_2_filter" class="dataTables_filter">                                                        
                                                <label><button class="btn btn-success" type="submit" id="go-btn" name="go-btn">GO</button></label>
                                                <!--                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                                                                <label>Vaccines:
                                                                                                    <select id="items" name="items" class="form-control input-inline input-xsmall">
                                                                                                        <option value="" selected="selected">All</option> 
                                                <?php
//                                                        foreach ($vaccines as $vaccine) {
//                                                            
                                                ?>
                                                                                                            <option value = "//<?php echo $vaccine['item_id'] ?>" <?php
//                                                            if ($vaccine['item_id'] == $selected_product) {
//                                                                echo "selected='selected'";
//                                                            }
//                                                            
                                                ?>><?php echo $vaccine['item_name'] ?></option>
                                                                                                                    //<?php
//                                                                }
                                                ?>   
                                                                                                    </select>
                                                                                                </label>-->
                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                <label>Month:
                                                    <select id="month-to" name="month-to" class="form-control input-inline input-xsmall">
                                                        <option value = "">Select Month</option>
                                                        <?php
                                                        $months_to = $this->all_months;
                                                        foreach ($months_to as $month) {
                                                            ?>
                                                            <option value = "<?php echo $month['month_code'] ?>" <?php
                                                            if ($month['month_code'] == $this->selected_month_to) {
                                                                echo "selected='selected'";
                                                            }
                                                            ?>><?php echo $month['month_name'] ?></option>
                                                                    <?php
                                                                }
                                                                ?>  
                                                    </select>
                                                </label> 
                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                <label>Year:
                                                    <select id="year-to" name="year-to" class="form-control input-inline input-xsmall">
                                                        <option value = "">Select Year</option>
                                                        <?php
                                                        $years_to = $this->years;
                                                        foreach ($years_to as $key => $value) {
                                                            ?>
                                                            <option value = "<?php echo $key ?>" <?php
                                                            if ($key == $this->selected_year_to) {
                                                                echo "selected='selected'";
                                                            }
                                                            ?>><?php echo $value ?></option>
                                                                    <?php
                                                                }
                                                                ?>
                                                    </select>
                                                </label> 
                                                <!--                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>-->

                                                <!--                                                <label>Month From:
                                                                                                    <select id="month-from" name="month-from" class="form-control input-inline input-xsmall">
                                                                                                        <option value = "">Select Month</option>
                                                <?php
                                                $months_from = $this->all_months;
                                                foreach ($months_from as $month) {
                                                    ?>
                                                                                                                                                            <option value = "<?php echo $month['month_code'] ?>" <?php
                                                    if ($month['month_code'] == $this->selected_month_from) {
                                                        echo "selected='selected'";
                                                    }
                                                    ?>><?php echo $month['month_name'] ?></option>
                                                    <?php
                                                }
                                                ?>  
                                                                                                    </select>
                                                                                                </label> 
                                                                                                <label>Year From:
                                                                                                    <select id="year-from" name="year-from" class="form-control input-inline input-xsmall">
                                                                                                        <option value = "">Select Year</option>
                                                <?php
                                                $years_from = $this->years;
                                                foreach ($years_from as $key => $value) {
                                                    ?>
                                                                                                                                                            <option value = "<?php echo $key ?>" <?php
                                                    if ($key == $this->selected_year_from) {
                                                        echo "selected='selected'";
                                                    }
                                                    ?>><?php echo $value ?></option>
                                                    <?php
                                                }
                                                ?>
                                                                                                    </select>
                                                                                                </label> -->
                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                <label>District:
                                                    <select id="district" name="district" class="form-control input-inline input-xsmall">
                                                        <option value = "">Select District</option>
                                                        <?php
                                                        $districts = $this->districts;
                                                        foreach ($districts as $district) {
                                                            ?>
                                                            <option value = "<?php echo $district['district_id'] ?>" <?php
                                                            if ($district['district_id'] == $this->selected_district) {
                                                                echo "selected='selected'";
                                                            }
                                                            ?>><?php echo $district['district_name'] ?></option>
                                                                    <?php
                                                                }
                                                                ?>
                                                    </select>
                                                </label> 
                                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                                                <label>Province:
                                                    <select id="province" name="province" class="form-control input-inline input-xsmall">
                                                        <option value = "">Select Province</option>
                                                        <?php
                                                        $provinces = $this->provinces;
                                                        foreach ($provinces as $key => $value) {
                                                            ?>
                                                            <option value = "<?php echo $key ?>" selected = "selected"><?php echo $value ?></option>
                                                            <?php
                                                        }
                                                        ?>

                                                    </select>
                                                </label> 
                                            </div>
                                        </div>
                                    </form>
                                </div>

                                <div class="row">

                                    <div class="col-md-6">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>Wastage in District</h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages">
                                                <br>
                                                <div style=" overflow: auto;  ">
                                                <?php
                                                echo "<table class='table table-striped table-bordered'>";
                                                echo "<caption><h4>Wastage in District  $selected_district_name</h4></caption>";
                                                echo "<thead>";
                                                echo "<tr>";
                                                echo "<th>Vaccine</th>";
                                                foreach ($month_array as $month) {
                                                    echo "<th>$month</th>";
                                                }
                                                echo "<th>Avg</th>";
                                                echo "<th style='font-size: 11px'>Acceptable Level</th>";
                                                echo "</tr>";
                                                echo "</thead>";
                                                echo "<tbody>";
                                                foreach ($wastage_array as $item_id => $item_data) {

                                                    echo "<tr>";
                                                    $sum = 0;
                                                    $number_of_items = 0;

                                                    foreach ($item_data as $key => $value) {
                                                        if ($key > 0) {
                                                            if ($value != null) {
                                                                $value = round($value);
                                                                echo"<td>$value%</td>";
                                                                $sum = $sum + $value;
                                                                $number_of_items++;
                                                            } else {
                                                                echo"<td></td>";
                                                            }
                                                        } else {
                                                            echo"<th>$value</th>";
                                                        }
                                                    }
                                                    $average = null;
                                                    if ($number_of_items != 0) {
                                                        $average = $sum / $number_of_items;
                                                    }
                                                    $average_wastage_array[$item_id]['AverageWastage'] = round($average);
                                                    $allowed_wastage = 0;
                                                    foreach ($vaccines as $item) {
                                                        if ($item['item_id'] == $item_id) {
                                                            $allowed_wastage = $item['AcceptableLevel'];
                                                        }
                                                    }
                                                    if ($average != null) {
                                                        echo "<td>" . round($average) . "%</td>";
                                                    } else {
                                                        echo "<td></td>";
                                                    }
                                                    echo "<td>$allowed_wastage%</td>";
                                                    echo "</tr>";
                                                }
                                                echo "</tbody>";
                                                echo "</table>";
                                                ?>
                                                    </div>

                                                <br>
                                                <?php
                                                $from = $month_array[0];
                                                $to = end($month_array);
                                                $category = "";
                                                $dataset = "";
                                                foreach ($average_wastage_array as $data) {
                                                    $category .= "<category label='" . $data['item_name'] . "' />";
                                                    $dataset .="<set  value='" . $data['AverageWastage'] . "' />";
                                                }
                                                $xmlstore = "
                                                            <chart 
                                                                exportEnabled='1' 
                                                                slantLabels='1' 
                                                                yAxisMaxValue='100%' 
                                                                exportAction='Download' 
                                                                caption= 'Average Wastage in District $selected_district_name ($from to $to)' 
                                                                exportFileName='Average Wastage in District $selected_district_name ($from to $to)' 
                                                                yAxisName='' 
                                                                showValues='1' 
                                                                formatNumberScale='0' 
                                                                theme='fint'>
                                                                <categories>
                                                                    $category
                                                                </categories>
                                                                <dataset>
                                                                    $dataset
                                                                </dataset>
                                                            </chart>";
                                                FC_SetRenderer('javascript');
                                                echo renderChart($this->baseUrl() . "/FusionCharts/Charts/MSColumn2D.swf", "", $xmlstore, "AvgWastageInDistrict", '100%', 350, false, false);
                                                ?>                                                            <div style="clear:both;"></div>            

                                            </div>
                                        </div>
                                    </div>


                                    <div class="col-md-6">
                                        <div data-toggle="collapse-widget" class="widget">
                                            <div class="widget-head">
                                                <h4 class="heading "><i></i>Vaccines wastage above permissible level</h4>
                                            </div>
                                            <div class="widget-body dashlets" id="473" href="reports/dashlet/reported-wastages" >
                                                <br>
                                                <div style=" overflow: auto;  ">
                                                    <?php
                                                    echo "<table class='table table-striped table-bordered' id='example'>";
                                                    echo "<caption><h4>Number of UCs wasting vaccines above permissible level </h4></caption>";
                                                    echo "<thead>";
                                                    echo "<tr>";
                                                    echo "<th>Vaccine</th>";
                                                    foreach ($month_array as $month) {
                                                        echo "<th>$month</th>";
                                                    }
                                                    echo "<th>Avg</th>";
                                                    echo "<th style='font-size: 11px'>Allowed Wastage</th>";
                                                    echo "</tr>";
                                                    echo "</thead>";
                                                    echo "<tbody>";
                                                    foreach ($UCs_wasting_vaccines_array as $item_id => $item_data) {

                                                        echo "<tr>";
                                                        $sum = 0;
                                                        $number_of_items = 0;
                                                        foreach ($item_data as $key => $value) {
                                                            if ($key > 0) {
                                                                if ($value != null) {
                                                                    $value = round($value);
                                                                    echo"<td>$value%</td>";
                                                                    $sum = $sum + $value;
                                                                    $number_of_items++;
                                                                } else {
                                                                    echo"<td></td>";
                                                                }
                                                            } else {
                                                                echo"<th>$value</th>";
                                                            }
                                                        }
                                                        $average = null;
                                                        if ($number_of_items != 0) {
                                                            $average = $sum / $number_of_items;
                                                        }

                                                        $average_ucs_array[$item_id]['AverageUcs'] = round($average);
                                                        $allowed_wastage = 0;
                                                        foreach ($vaccines as $item) {
                                                            if ($item['item_id'] == $item_id) {
                                                                $allowed_wastage = $item['AcceptableLevel'];
                                                            }
                                                        }
                                                        if ($average != null) {
                                                            echo "<td>" . round($average) . "%</td>";
                                                        } else {
                                                            echo "<td></td>";
                                                        }
                                                        echo "<td>$allowed_wastage%</td>";
                                                        echo "</tr>";
                                                    }
                                                    echo "</tbody>";
                                                    echo "</table>";
                                                    ?>
                                                </div>

                                                <br>
                                                <?php
                                                $from = $month_array[0];
                                                $to = end($month_array);
                                                $category2 = "";
                                                $dataset2 = "";
                                                foreach ($average_ucs_array as $data) {
                                                    $category2 .= "<category label='" . $data['item_name'] . "' />";
                                                    $dataset2 .="<set  value='" . $data['AverageUcs'] . "' />";
                                                }
                                                $xmlstore2 = "
                                                            <chart 
                                                                exportEnabled='1' 
                                                                slantLabels='1' 
                                                                yAxisMaxValue='100%' 
                                                                exportAction='Download' 
                                                                caption= 'Average number of UCs wasting vaccines above permissible level' 
                                                                exportFileName='Average number of UCs wasting vaccines above permissible level' 
                                                                yAxisName='' 
                                                                showValues='1' 
                                                                formatNumberScale='0' 
                                                                theme='fint'>
                                                                <categories>
                                                                    $category2
                                                                </categories>
                                                                <dataset>
                                                                    $dataset2
                                                                </dataset>
                                                            </chart>";
                                                FC_SetRenderer('javascript');
                                                echo renderChart($this->baseUrl() . "/FusionCharts/Charts/MSColumn2D.swf", "", $xmlstore2, "AvgNoOfUCsWastingVaccinesAbovePermissibleLevel", '100%', 350, false, false);
                                                ?> 

                                                <div style="clear:both;"></div>            

                                            </div>
                                        </div>
                                    </div>


                                </div>


                                <input id="tabid" value="472" type="hidden">
                            </div>
                        </div>
                    </div>

                </div>
                <!-- // Tabs END -->                
            </div>
        </div>
    </div>
</div>