<?php
/**
 *  phtml for Cold Chain Capacity 
 */
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <?php if ($this->user_role == 4 || $this->user_role == 5 || $this->user_role == 6 || $this->user_role == 7 || $this->user_role == 54) { ?>
            <?php if (!empty($this->pending_receive)) { ?>
                <div class="row">
                    <div class="col-md-12">
                        <small style="font-weight: bold;color:red;"><?php
                            echo "Pending Vouchers for " . $this->warehouse_name . " : ";
                            foreach ($this->pending_receive as $pending_receive) {
                                ?> 
                                <a style="color:red" href="<?php echo $this->baseUrl(); ?>/stock/receive-warehouse?issue_no=<?php echo $pending_receive['transaction_number']; ?>&search=true"><?php echo $pending_receive['transaction_number'] ?></a>,
                            <?php } ?>                        
                        </small>
                        <hr>
                    </div>
                </div>
                <?php
            }
        }
        ?>
        <div class="row">
            <h3 class="col-md-8">
                <?php echo $this->warehousename; ?> <small>dashboard & statistics</small>
            </h3>
            <!--<form method="post" name="mystore" id="mystore" action="">
                <div class="col-md-3">
                    <input class="form-control" type="text" name="to_date" id="to_date" value="<?php echo $this->to_date; ?>" readonly/>
                </div>
                <div class="col-md-1 right">
                    <button class="btn btn-success" type="submit" id="camp_btn" name="camp_btn" value="camp">GO</button>
                </div>
            </form>-->
        </div>
        <div class="row">&nbsp;</div>
        <!-- END PAGE HEADER-->
        <div class="row">
            <div class="col-md-12">
                <div class="widget widget-tabs">
                    <div class="widget-head dashboard-widget">
                        <ul>
                            <li class="active">
                                <a href="<?php echo $this->baseUrl(); ?>/reports/dashlet/cold-chain-capacity?to_date=<?php echo $this->to_date; ?>">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-routine-immunization"></i>
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1">Capacity by:</div>
                                            <div class="dashboard-title-2">Utilization</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="">
                                <a href="<?php echo $this->baseUrl(); ?>/reports/dashlet/cold-chain-capacity-product?to_date=<?php echo $this->to_date; ?>">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-inventory-management"></i>
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1">Capacity by:</div>
                                            <div class="dashboard-title-2">Vaccine</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <!-- <li class="">
                                <a href="<?php //echo $this->baseUrl();                       ?>/reports/dashlet/cold-chain-capacity-vvm?to_date=<?php //echo $this->to_date;                       ?>">
                                    <div class="dashboard-stat_custom">
                                        <div style="width: auto;" class="visual">
                                            <i class="fa fa-cold-chain"></i>
                                        </div>
                                        <div style="float: left;" class="details">
                                            <div class="dashboard-title-1">Status by:</div>
                                            <div class="dashboard-title-2">VVM</div>
                                        </div>
                                    </div>
                                </a>
                            </li> -->

                        </ul>
                    </div>
                    <div class="widget-body">
                        <div class="tab-content">
                            <div class="tab-pane active">
                                <div class="row">
                                    <div class="col-md-12">
                                        <?php
                                        FC_SetRenderer('javascript');
                                        echo renderChart($this->baseUrl() . "/FusionCharts/Charts/MSColumn2D.swf", "", $this->xmlstore2, "coldchainCapacity28", '100%', 350, false, false);
                                        ?>
                                    </div>
                                    <div class="col-md-6">
                                        <?php
                                        FC_SetRenderer('javascript');
                                        echo renderChart($this->baseUrl() . "/FusionCharts/Charts/MSColumn2D.swf", "", $this->xmlstore1, "coldchainCapacity20", '100%', 350, false, false);
                                        ?>
                                    </div>
                                    <div class="col-md-6">
                                        <table class="dynamicTable table table-striped table-bordered table-hover dataTable no-footer" id="sample_4">
                                            <thead>
                                                <tr>
                                                    <th>Sr. No.</th>
                                                    <th>Cold Room</th>
                                                    <th class="right">Gross <br>(In Litres)</th>
                                                    <th alass="right">Net Usable <br>(In Litres)</th>
                                                    <th class="right">Being Used <br>(In Litres)</th>
                                                    <th class="right">Being <br> Used %</th>
                                                </tr>
                                            </thead>

                                            <tbody>


                                                <?php
                                                $i = 1;
                                                $q = 1;
                                                $total_gross_cc =0;
                                                $total_net_usable_cc = 0;
                                                $total_being_used_cc =0;
                                                foreach ($this->data as $row) {
                                                    if ($row['ccm_asset_type_id'] == 16) {
                                                        ?>
                                                        <tr>
                                                            <td class="center"><?php echo $i; ?></td>
                                                            <td><?php echo $row['asset_id']; ?></td>
                                                            <td class="right"><?php echo number_format($row['gross']); ?></td>
                                                            <td class="right"><?php echo number_format($row['net_usable']); ?></td>
                                                            <td class="right"><?php echo number_format($row['being_used']); ?></td>
                                                            <td class="right"><?php echo ROUND($row['being_used'] * 100 / $row['net_usable']); ?>%</td>
                                                        </tr>
                                                        <?php
                                                        $total_gross_cc += $row['gross'];
                                                        $total_net_usable_cc += $row['net_usable'];
                                                        $total_being_used_cc += $row['being_used'];
                                                        ?>

                                                        <?php
                                                    }
                                                    $i++;
                                                }
                                                ?>

                                                <tr>
                                                    <td class="right bold" colspan="2" >Total</td>

                                                    <td class="right"><?php echo number_format($total_gross_cc); ?></td>
                                                    <td class="right"><?php echo number_format($total_net_usable_cc); ?></td>
                                                    <td class="right"><?php echo number_format($total_being_used_cc); ?></td>
                                                    <td class="right"><?php echo ROUND($total_being_used_cc * 100 / $total_net_usable_cc); ?>%</td>
                                                </tr>









                                                <?php
                                                $i = 1;
                                                $q = 1;
                                                $total_gross_fr =0;
                                                $total_net_usable_fr = 0;
                                                $total_being_used_fr = 0;
                                                foreach ($this->data as $row) {
                                                    if ($row['ccm_asset_type_id'] == 15 && $q == 1) {
                                                        ?>
                                                        <tr>
                                                            <th>Sr. No.</th>
                                                            <th>Freezers</th>
                                                            <th class="right">Gross <br>(In Litres)</th>
                                                            <th alass="right">Net Usable <br>(In Litres)</th>
                                                            <th class="right">Being Used <br>(In Litres)</th>
                                                            <th class="right">Being <br> Used %</th>
                                                        </tr>
                                                        <?php
                                                        $i = 1;
                                                        $q++;
                                                    }
                                                    ?>
                                                    <?php if ($row['ccm_asset_type_id'] == 15) { ?>
                                                        <tr>
                                                            <td class="center"><?php echo $i; ?></td>
                                                            <td><?php echo $row['asset_id']; ?></td>
                                                            <td class="right"><?php echo number_format($row['gross']); ?></td>
                                                            <td class="right"><?php echo number_format($row['net_usable']); ?></td>
                                                            <td class="right"><?php echo number_format($row['being_used']); ?></td>
                                                            <td class="right"><?php echo ROUND($row['being_used'] * 100 / $row['net_usable']); ?>%</td>
                                                        </tr>
                                                        <?php
                                                        $total_gross_fr += $row['gross'];
                                                        $total_net_usable_fr += $row['net_usable'];
                                                        $total_being_used_fr += $row['being_used'];
                                                        ?>

                                                    <?php } ?>
                                                    <?php
                                                    $i++;
                                                }
                                                ?>      

                                                <tr>
                                                    <td class="right bold" colspan="2" >Total</td>

                                                    <td class="right"><?php echo number_format($total_gross_fr); ?></td>
                                                    <td class="right"><?php echo number_format($total_net_usable_fr); ?></td>
                                                    <td class="right"><?php echo number_format($total_being_used_fr); ?></td>
                                                    <td class="right"><?php echo ROUND($total_being_used_fr * 100 / $total_net_usable_fr); ?>%</td>
                                                </tr>


                                            </tbody>

                                        </table>

                                        <br>
                                        <div class="right"><input onclick="javascript: window.open('<?php echo $this->baseUrl(); ?>/reports/dashlet/cold-chain-capacity-print?to_date=<?php echo $this->to_date; ?>', '_blank', 'scrollbars=1,width=860,height=595')" type="button" class="btn btn-success" value="Print Table Data"/></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- // Tabs END -->                
            </div>
        </div>
    </div>
</div>