<table class="table table-striped table-bordered table-hover dataTable no-footer" id="sample_29">
    <!-- Table heading -->
    <thead>
        <tr>
            <th rowspan="2">S.No</th>
            <th colspan="3" class="center">AEFI Case</th>
            <th colspan="3" class="center">Reporting Sites</th>
            <th colspan="11" class="center">Case Details</th>
            <th colspan="5" class="center">Clinical Information</th>
            <th colspan="12" class="center">Vaccination</th>


            <th class="nonprint" rowspan="2">&nbsp;</th>
        </tr>
        <tr>

            <th>Entry Date</th>
            <th>Week</th>
            <th>Case Reported</th> 



            <th>Date of Notification</th>
            <th>Case Reported From Health Facility</th>
            <th>Other (Health Facility) </th>





            <th>District</th>
            <th>Tehsil/Taluka</th> 
            <th>UC</th> 
            <th>Village/Area</th> 
            <th>House # OR Nearest Area</th>
            <th>Child Name</th>
            <th>Father Name</th>
            <th>Contact Number</th>
            <th>Gender</th>
            <th>Date of Birth</th>
            <th>Age</th>



            <th>AEFI</th> 
            <th>Date of AEFI Onset</th> 
            <th>Date of Investigation</th> 
            <th>Hospitalization</th>
            <th>Death</th>



            <th>Date of Vaccine Given</th>
            <th>Vaccine Received</th>
            <th>Batch/Lot No</th>
             <th>Other (Batch/Lot No)</th>
             <th>Expiry Date</th>
            <th>District</th>
            <th>Tehsil/Taluka</th> 
            <th>UC</th> 
            <th>Other (EPI Center) </th>
            <th>Name of Vaccinator</th>
            <th>Case Vaccinated From EPI Center </th>
            <th>Designation</th>

        </tr>
    </thead>
    <!-- // Table heading END -->
    <!-- Table body -->

    <!-- // Table body END -->
    <tbody >
        <?php
        $m_res = array();
        $i = 1;
        if ($this->result && count($this->result) > 0) :
            foreach ($this->result as $row):
                ?>
                <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                    <td class="center" width="25"><?php echo $i; ?></td>
                    <td><?php echo date("d/m/Y", strtotime($row['date'])); ?></td>
                    <td><?php echo $row['week']; ?></td>
                    <td><?php
                        if ($row['type_case'] == 1) {
                            echo "Yes";
                        } else {
                            echo "No";
                        }
                        ?></td>
                    <td><?php echo $row['date_notification']; ?></td>
                    <td><?php echo $row['hf_name']; ?></td>
                    <td><?php echo $row['hf_name']; ?></td>

                    <td><?php echo $row['district_case']; ?></td>
                    <td><?php echo $row['tehsil_case']; ?></td>
                    <td><?php echo $row['uc_case']; ?></td>
                    <td><?php echo $row['address_village']; ?></td>
                    <td><?php echo $row['complete_address']; ?></td>
                    <td><?php echo $row['child_name']; ?></td>
                    <td><?php echo $row['father_name']; ?></td>
                    <td><?php echo $row['contact_number']; ?></td>

                    <td><?php
                        if ($row['gender'] == 1) {
                            echo 'Male';
                        } else {
                            echo 'Female';
                        }
                        ?></td>
                    <td><?php echo date("d/m/Y", strtotime($row['dob'])); ?></td>
                    <td><?php
                        echo $row['age'] . '-';
                        if ($row['age_unit'] == 1) {
                            echo "Months";
                        } else if ($row['age_unit'] == 2) {
                            echo "Days";
                        } else {
                            echo "Years";
                        }
                        ?></td>


                    <td><?php echo $row['aefi']; ?></td>
                    <td><?php echo date("d/m/Y", strtotime($row['date_aefi_onset'])); ?></td>
                    <td><?php echo date("d/m/Y", strtotime($row['date_of_investigation'])); ?></td>
                    <td><?php
                        if ($row['hospitalization'] == 1) {
                            echo "Yes";
                        } else {
                            echo "No";
                        }
                        ?></td>
                    <td><?php
                        if ($row['death'] == 1) {
                            echo "Yes";
                        } else {
                            echo "No";
                        }
                        ?></td>
                    <td><?php echo date("d/m/Y", strtotime($row['date_vaccine_given'])); ?></td>
                    <td><?php echo $row['vaccine']; ?></td>
                    <td><?php echo $row['batch_id']; ?></td>
                     <td><?php echo $row['batch_number']; ?></td>
                      <td><?php echo $row['expiry_date']; ?></td>
                    <td><?php echo $row['district']; ?></td>
                    <td><?php echo $row['tehsil']; ?></td>
                    <td><?php echo $row['uc']; ?></td>
                    <td><?php echo $row['other_case_epi']; ?></td>
                    <td><?php echo $row['vaccinator_name']; ?></td>
                    <td><?php echo $row['sentinel_site_name']; ?></td>
                    <td><?php echo $row['designation']; ?></td>
                    <td>
                        <a href="<?php echo $this->baseUrl(); ?>/surveillance/aefi?id=<?php echo $row['pk_id']; ?>" class="update-locations btn btn-xs green" ><i class="fa fa-edit"></i><?php echo $this->translate("Edit") ?>
                        </a>
                        <?php if ($row['aefi'] != 'Not Reported') { ?>
                            <input type="hidden" id="hdn_aefi_id" name="hdn_aefi_id" value="<?php echo $row['pk_id']; ?>">
                            <a pkid="<?php echo $row['pk_id']; ?>"  onclick="window.open('print-aefi?id=<?php echo $row['pk_id']; ?>', '_blank', 'scrollbars=1,width=840,height=595');" title="AEFI Detail"  class="btn default btn-xs green-stripe detail">View</a>
                        <?php } ?>
                    </td>
                    <!-- // Table row END --><?php
                    $i++;

                endforeach;

            endif;
            ?>
    </tbody>
</table>