<?php
/**
 *  phtml for Print Issue
 */
?>
<?php
ob_start();
?>
<style>
    #content_print {
        margin-left: 55px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #444;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #444;
    }
    table#mytable tr th {
        border: 1px solid #444;
    }
</style>

<style type="text/css" media="print">
    .page{
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print{    
        #printButt{
            display: none !important;
        }
    }
</style>

<div class="row">
    <div class="scroller" style="min-height:200px" data-always-visible="1" data-rail-visible1="1">

        <h4 class="form-section">AEFI Case</h4>
        <strong>Entry Date : </strong><?php echo'__________'?>&nbsp;&nbsp;&nbsp;
        <strong>Week : </strong> <?php echo'__________'?>
        &nbsp;&nbsp;&nbsp;<strong>Case Reported : </strong> <?php echo'__________'?>
         
        <br><br>
        <h4 class="form-section">Reporting Sites</h4>
        <strong>Date of Notification : </strong> <?php echo'__________'?>&nbsp;&nbsp;&nbsp;
        <strong>Case Reported from Health Facility : </strong> <?php echo'__________'?> &nbsp;&nbsp;&nbsp; 
        <br><strong>Other (Health Facility) : </strong> <?php echo'__________'?>
        <br><br>
           
        <h4 class="form-section">Case Details</h4>
        <strong>Province : </strong><?php echo'__________'?> &nbsp;&nbsp;&nbsp;<strong>District : </strong><?php echo'__________'?>&nbsp;&nbsp;&nbsp;<strong>Tehsil : </strong> <?php echo'__________'?>&nbsp;&nbsp;&nbsp;<strong>UC : </strong> <?php echo'__________'?><br>
       <strong>Village : </strong><?php echo'__________'?>&nbsp;&nbsp;&nbsp; <strong>Address : </strong><?php echo'__________'?><br>
      
        <strong>Child Name : </strong> <?php echo'__________'?>&nbsp;&nbsp;&nbsp;
        <strong>Father Name : </strong> <?php echo'__________'?>&nbsp;&nbsp;&nbsp;
        <strong>Contact Number : </strong> <?php echo'__________'?> &nbsp;&nbsp;&nbsp;
        <br><strong>Gender : </strong>  
       <?php echo'__________'?>
        <strong>Date of Birth : </strong> <?php echo'__________'?>&nbsp;&nbsp;&nbsp;
        <strong>Age : </strong>  
        <?php echo'__________'?>
           <br><br>
        <h4 class="form-section">Clinical Information</h4>
         <strong>Date of Investigation : </strong><?php echo'__________'?>&nbsp;&nbsp;&nbsp;<br>
        <strong>AEFI : </strong><?php echo'__________'?>&nbsp;&nbsp;&nbsp;
        <strong>Other  : </strong><?php echo'__________'?>
        <br>
        <strong>Date of AEFI Onset : </strong> <?php echo'__________'?><br>
        <strong>Hospitalization : </strong> <?php echo'__________'?>&nbsp;&nbsp;&nbsp;
        <strong>Death : </strong> <?php echo'__________'?>   <br><br>
  <h4 class="form-section">Vaccination</h4>
  <strong>Date of Vaccine Given : </strong><?php echo'__________'?>
<strong>&nbsp;&nbsp;&nbsp;Vaccine Received: </strong><?php echo'__________'?>&nbsp;&nbsp;&nbsp;
<strong>Batch No: </strong><?php echo'__________'?>&nbsp;&nbsp;&nbsp;
<br><strong>Other: </strong> <?php echo'__________'?>&nbsp;&nbsp;&nbsp;
<strong>Expiry Date : </strong> <?php echo'__________'?>&nbsp;&nbsp;&nbsp;
<strong>District : </strong> <?php echo'__________'?>&nbsp;&nbsp;&nbsp;<strong>Tehsil : </strong> <?php echo'__________'?>&nbsp;&nbsp;&nbsp;<strong>UC : </strong> <?php echo'__________'?>
     <br><strong>Case Vaccinated From EPI Center : </strong> <?php echo'__________'?>&nbsp;&nbsp;&nbsp;
       <strong>Other (EPI Center)  : </strong> <?php echo'__________'?> &nbsp;&nbsp;&nbsp;
      
    <br><strong>Name of Vaccinator : </strong> <?php echo'__________'?>&nbsp;&nbsp;&nbsp;
       <strong>Designation : </strong> <?php echo'__________'?> &nbsp;&nbsp;&nbsp;
       
    
    
    </div>
</div>

<div class="col-md-12" class="widget">
    <div class="widget-body right">
        <button id="print" name="print" value="1" type="button" class="btn btn-primary" ><?php echo $this->translate("Print"); ?></button>
    </div>
</div>

<script>
    $(function () {
        //printCont();
        $("#print").click(function () {
            printCont();
        });
    });

    function printCont()
    {
        $("a").hide();
        $('#print').hide();
        window.print();
        setTimeout(function () {
            // Do something after 5 seconds
            $('#print').show();
            $("a").show();
        }, 5000);
    }
</script>