<?php
/**
 *  phtml for Index
 */
?>
<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Search VPD Cases") ?>  </h3>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Search VPD Cases") ?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" name="search-vpd" id="search-vpd" action="" >
                                    <!-- Row -->
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label class="control-label" for="t_o_case">
                                                Reporting Date  
                                            </label>
                                            <div class="input-group input-large date-picker input-daterange" data-date="10/11/2012" data-date-format="mm/dd/yyyy">
                                                <input style="width:236px;" class="form-control  " name="date_from" id="date_from" type="text" value="<?php echo date('1/m/Y') ?>">
                                                <span class="input-group-addon">to</span>
                                                <input style="width:236px;" class="form-control " name="date_to" id="date_to" type="text" value="<?php echo date('d/m/Y') ?>">
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group">
                                                <label class="control-label" for="t_o_case">
                                                    Type of Case  
                                                </label>
                                                <select class="form-control" id="t_o_case" name="t_o_case">

                                                    <?php
                                                    foreach ($this->type_case as $row) {
                                                        ?>
                                                        <option value="<?php echo $row['pkId']; ?>"  >
                                                            <?php echo $row['listValue']; ?>
                                                        </option>
                                                        <?php
                                                    }
                                                    ?>

                                                </select>

                                            </div>
                                        </div>
                                        <div class="row">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-10">
                                        </div>
                                        <div class="col-md-2">

                                            <button data-loading-text="Searching"  class="btn btn-sm green btn-outline filter-submit" type="button" name="search" id="search" ><i class="fa fa-search"></i>
                                                <?php echo $this->translate("Search") ?></button>
                                            <button type="reset" class="btn btn-sm default btn-outline filter-cancel" id="reset"><i class="fa fa-times"></i>
                                                Reset</button>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Vaccine Preventable Disease Report") ?>
                        </div>
                        <div class="tools">

                            <a href="javascript:;" class="reload" style="visibility: hidden"></a>

                        </div>

                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="dataTables_wrapper form-inline" id="ajax-table" >

                                    <table class="table table-striped table-bordered table-hover dataTable no-footer" id="sample_2">
                                        <!-- Table heading -->
                                        <?php
                                        $fields = array(
                                            's_no' => 'S.No',
                                            'reporting_date' => 'Reporting Date',
                                            'type_of_case' => 'Type of case',
                                            'epid_number' => 'EPID Number',
                                            'child_name' => 'Child Name',
                                            'date_of_onset' => 'Date of Onset',
                                            'district' => 'District',
                                            'tehsil' => 'Tehsil',
                                            'UC' => 'UC'
                                        );
                                        $this->tableHeading($this->order, $this->sort, $fields);
                                        ?>
                                        <!-- // Table heading END -->
                                        <!-- Table body -->

                                        <!-- // Table body END -->
                                        <tbody >
                                            <?php
                                            $m_res = array();
                                            $i = 1;
                                            if ($this->paginator && count($this->paginator) > 0) :
                                                foreach ($this->paginator as $row):
                                                    ?>
                                                    <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                        <td class="center" width="25"><?php echo $i; ?></td>
                                                        <td><?php echo $row['locationName']; ?></td>
                                                        <td><?php echo $row['parent']; ?></td>
                                                        <td><?php echo $row['geoLevelName']; ?></td>
                                                        <td><?php echo $row['ccmLocationId']; ?></td>
                                                        <td><?php echo $row['locationTypeName']; ?></td>
                                                        <td><?php echo $row['locationTypeName']; ?></td>
                                                        <td><?php echo $row['locationTypeName']; ?></td>
                                                        <td><?php echo $row['locationTypeName']; ?></td>
                                                        <td>
                                                            <a itemid="<?php echo $row['pkId']; ?>" class="update-locations btn btn-xs green" data-toggle="modal" href="#modal-update-locations"><i class="fa fa-edit"></i><?php echo $this->translate("Edit") ?>
                                                            </a>
                                                            <?php if ($this->locationsDelete($row['pkId'])) { ?>
                                                            <?php } else { ?>
                                                                <a data-toggle="notyfy" data-bind="<?php echo $row['pkId']; ?>" data-type="confirm" data-layout="top" class="btn btn-xs red"><i class="fa fa-times"></i><?php echo $this->translate("Delete"); ?>
                                                                </a>
                                                            <?php } ?>
                                                        </td>
                                                        <!-- // Table row END --><?php
                                                        $i++;

                                                    endforeach;

                                                endif;
                                                ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- // Content END -->

<div class="modal fade" id="modal-placement-history" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" >
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">Ã—</button>
                <h3>VPD Detail</h3>
            </div>
            <div class="modal-body" id="modal-body-contents"></div>
        </div>
    </div>
</div>
