<?php
error_reporting(0);
/**
 *  phtml for Vpd
 */
?>
<style>
    .error {color: #FF0000;}

</style>
<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title" style="padding-left:20px;">
            <?php echo $this->translate("VPD Case Entry Form"); ?>
        </h3>
        <div class="row">

            <div class="col-md-offset-1 col-md-10 " style="margin-left:9%;padding-left:-8%; background-color:#EAEAEB; padding:15px;  border-radius: 5px;">
                <form method="POST" name="search-vpd" id="search-vpd" action="" >
                    <!-- Row -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-2" >
                                <div class="form-group">
                                    <label class="control-label" for="t_o_case1">
                                        Date from
                                    </label>
                                    <input class="form-control"  type="text"  id="date_from" name="date_from" readonly="" value="<?php echo date('1/m/Y') ?>">

                                </div>
                            </div>
                            <div class="col-md-2" >
                                <div class="form-group">
                                    <label class="control-label" for="t_o_case1">
                                        Date to
                                    </label>
                                    <input class="form-control "  type="text"  name="date_to" id="date_to" readonly=""  value="<?php echo date('d/m/Y') ?>">

                                </div>

                            </div>
                            <div class="col-md-2" >
                                <div class="form-group">
                                    <label class="control-label" for="t_o_case1">
                                        Type of Case
                                    </label>
                                    <?php
                                    if ($this->type_o_case) {
                                        
                                    }
                                    ?>
                                    <select class="form-control" id="t_o_case1" name="t_o_case1">

                                        <?php
                                        foreach ($this->type_case as $row) {
                                            if ($this->type_o_case == $row['pkId']) {
                                                $sel = "selected=''";
                                            } else {
                                                $sel = "";
                                            }
                                            ?>
                                            <option value="<?php echo $row['pkId']; ?>"  <?php echo $sel; ?> >
                                                <?php echo $row['listValue']; ?>
                                            </option>
                                            <?php
                                        }
                                        ?>

                                    </select>

                                </div>
                            </div>

                            <div class="col-md-2" style="margin-top:2.5%">

                                <button data-loading-text="Searching"  class="btn btn-sm btn-outline green filter-submit" type="button" name="search" id="search" ><i class="fa fa-search"></i>
                                    <?php echo $this->translate("Search") ?></button>
                                <button type="reset" class="btn btn-sm yellow default btn-outline filter-cancel" id="reset"><i class="fa fa-times"></i>
                                    Reset</button>

                            </div>
                            <div class="col-md-2" >
                                <a id="issue-print" class="btn btn-md default btn-outline" onclick="window.open('print-empty-vpd?id=', '_blank', 'scrollbars=1,width=840,height=595');" href="javascript:void(0);" style="background-color:#9fa7a7;padding-left:10px;padding-right:10px;padding-top:10px;padding-bottom:10px;margin-top:12%;"><strong><?php echo 'Print Blank Form'; ?> <i class="fa fa-print" ></i></strong>

                                </a>
                            </div>
                        </div>

                    </div>



                </form>
            </div>
            <a id="notific8_show" href="javascript:;" class="hide"></a>
            <div id="notific8_heading" class="hide">Your Data</div>
            <div id="notific8_life" class="hide">5000</div>
            <div id="notific8_text" class="hide">has been saved as draft.</div>
            <?php if (!empty($this->arr_data['success']) && $this->arr_data['success'] == 1) { ?>
                <div class="row margin-top-10 margin-bottom-10">

                    <div class="col-md-5" style="margin-left:20px; margin-top: 5px;">
                        <div  style="color: #468847;
                              background-color: #dff0d8;
                              border-color: #d6e9c6;
                              padding-right: 35px;
                              padding: 15px;">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                            <strong>VPD Case Saved Successfully!</strong>  <a href="" class="alert-link" onclick="window.open('print-vpd?id=<?php echo $this->master_id; ?>', '_blank', 'scrollbars=1,width=840,height=595');">Print</a>
                        </div>
                    </div>

                </div>
            <?php } ?>
            <div class="col-md-12">
                <?php
                ?>
            </div>

            <div class="row margin-top-10 margin-bottom-10">
                <?php if (!empty($this->is_draft)) { ?>


                    <div id="pulsate-regular" class="col-md-4" style="background-color:#F2DEDE; margin-left:20px;">
                        <strong>Draft!</strong> Displaying Draft Data.
                    </div>

                <?php } ?>

            </div>
            <form method="POST"  action="" id="register-form" name="register-form"  >

                <?php if ($this->role_id == 61) { ?>

                    <div class="col-md-offset-3 col-md-5 " style="margin-left:29%;/*! padding-left:-8%; */ background-color:#88DD9B; padding:15px;  border-radius: 5px;color:white">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-md-3">
                                        <label class="control-label" for="district_admin">
                                            District <span style="color:red;">*</span>
                                        </label>
                                    </div>


                                    <div class="col-md-6">
                                        <select class="form-control" id="district_admin" name="district_admin">
                                            <option value=""><?php echo $this->translate("Select"); ?></option>
                                            <?php
                                            foreach ($this->district_admin as $row) {
                                                if ($this->result[0]['district_id'] == $row['pkId']) {
                                                    $sel = "selected='selected'";
                                                } else {
                                                    $sel = "";
                                                }
                                                ?>
                                                <option value="<?php echo $row['pkId']; ?>" <?php echo $sel; ?> >
                                                    <?php echo $row['locationName']; ?>
                                                </option>
                                                <?php
                                            }
                                            ?>

                                        </select>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>

                <?php } ?>
                <div class="row"></div>
                <div class="col-md-5 well" style="margin-top:2%;padding-left:0%;padding-right:0%">
                    <div class="">
                        <h4 class="form-section" style="color:white;margin-top:-2.75%;background-color: #58d68d;padding:5px  12px 12px 20px">Type of Case</h4>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">

                                    <div class="col-md-5" >
                                        <label class="control-label" for="date">
                                            Entry Date:  <span style="color:red;">*</span>
                                        </label>
                                    </div>
                                    <div class="input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years" style="padding-left:3%">

                                        <input class="form-control" type="text"  id="date" name="date"  readonly="" value="<?php
                                        if (!empty($this->result)) {
                                            echo $this->result[0]['date'];
                                        } else {
                                            echo date('d/m/Y');
                                        }
                                        ?>"  />

                                    </div>


                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-md-5">
                                        <label class="control-label" for="week">
                                            Week  <span style="color:red;">*</span>
                                        </label>
                                    </div>
                                    <div class="col-md-6">
                                        <select class="form-control" id="week" name="week">
                                            <option value=""><?php echo $this->translate("Select"); ?></option>
                                            <?php
                                            for ($i = 1; $i < 53; $i++) {
                                                if ($this->result[0]['week'] == $i) {
                                                    $sel = "selected='selected'";
                                                } else {
                                                    $sel = "";
                                                }
                                                ?>
                                                <option value="<?php echo $i; ?>" <?php echo $sel; ?> >
                                                    <?php echo $i; ?>
                                                </option>
                                                <?php
                                            }
                                            ?>

                                        </select>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-md-5">
                                        <label class="control-label" for="t_o_case">
                                            Type of Case  <span style="color:red;">*</span>
                                        </label>
                                    </div>
                                    <div class="col-md-6">
                                        <select class="form-control" id="t_o_case" name="t_o_case">

                                            <?php
                                            foreach ($this->type_case as $row) {
                                                if ($this->result[0]['type_case'] == $row['pkId']) {
                                                    $sel = "selected='selected'";
                                                } else {
                                                    $sel = "";
                                                }
                                                ?>
                                                <option value="<?php echo $row['pkId']; ?>" <?php echo $sel; ?> >
                                                    <?php echo $row['listValue']; ?>
                                                </option>
                                                <?php
                                            }
                                            ?>

                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div id="case_type" >
                            <h4 class="form-section" style="color:white;background-color: #58d68d;padding:5px  12px 12px 20px">Reporting Sites</h4>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="district">
                                                Reporting <?php //echo $this->distrcit_name[0]['locationName'];                                                                                                                                                          ?> UCs <span style="color:red;">*</span>
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <select class="form-control" id="district_ucs" name="district_ucs">
                                                <option value=""><?php echo $this->translate("Select"); ?></option>
                                                <?php
                                                foreach ($this->distrcit_ucs as $row) {
                                                    if ($this->result[0]['from_uc_id'] == $row['pkId']) {
                                                        $sel = "selected='selected'";
                                                    } else {
                                                        $sel = "";
                                                    }
                                                    ?>
                                                    <option value="<?php echo $row['pkId']; ?>" <?php echo $sel; ?> >
                                                        <?php echo $row['locationName']; ?>
                                                    </option>
                                                    <?php
                                                }
                                                ?>

                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="case_health_facility">
                                                Surveillance Sites
                                            </label>
                                        </div>
                                        <div class="col-md-6">

                                            <select class="form-control" id="case_health_facility" name="case_health_facility">
                                                <option value=""><?php echo $this->translate("Select"); ?></option>
                                                <?php
                                                foreach ($this->distrcit_ssites as $row) {
                                                    if ($this->result[0]['hf_id'] == $row['pk_id']) {
                                                        $sel = "selected='selected'";
                                                    } else {
                                                        $sel = "";
                                                    }
                                                    ?>
                                                    <option value="<?php echo $row['pk_id']; ?>" <?php echo $sel; ?> >
                                                        <?php echo $row['sentinel_site_name']; ?>
                                                    </option>
                                                    <?php
                                                }
                                                ?>

                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="other_case_health_facility">
                                                Other
                                            </label>
                                        </div>
                                        <div class="col-md-6 input-group" style="padding-left:3%">
                                            <span class="input-group-addon">
                                                <span class=""><input type="checkbox" id="check" name="check"></span>
                                            </span>
                                            <input class="form-control" type="text"  id="other_case_health_facility" name="other_case_health_facility" readonly="">
                                        </div>



                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="cross_notification">
                                                Cross Notification
                                            </label>
                                        </div>
                                        <div class="btn-group col-md-6" data-toggle="buttons" >
                                            <label class="btn btn-default active" >
                                                <input class="toggle" name="cross_notification" id="dyes" value="1"   type="radio" checked=""> Yes
                                            </label>
                                            <label class="btn btn-default ">
                                                <input class="toggle" name="cross_notification" id="dno" value="0" type="radio"> No
                                            </label>

                                        </div>
                                    </div>


                                </div>
                            </div>

                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="date_Notification">
                                                Patient Visited Date (Health Facility)
                                            </label>
                                        </div>

                                        <div class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years" style="padding-left:3%">
                                            <input class="form-control" type="text"  id="datepicker_patient_visited" name="datepicker_patient_visited" readonly="" value="<?php
                                            if (!empty($this->result)) {
                                                echo $this->result[0]['patient_visited_date'];
                                            }
                                            ?>">
                                            <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type='button' id='remove_pt' name='remove_pt'><i class="fa fa-trash-o"></i></button>
                                            </span>  </div>

                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="date_Notification">
                                                Date of Notification <span style="color:red;">*</span>
                                            </label>
                                        </div>

                                        <div class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years" style="padding-left:3%">
                                            <input class="form-control" type="text"  id="datepicker_Notification" name="datepicker_Notification" readonly="" value="<?php
                                            if (!empty($this->result)) {
                                                echo $this->result[0]['date_notification'];
                                            }
                                            ?>"/>
                                            <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type='button' id='remove_noti' name='remove_noti'><i class="fa fa-trash-o"></i></button>
                                            </span>  </div>

                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="date_Onset">
                                                Date of Onset <span style="color:red;">*</span>
                                            </label>
                                        </div>


                                        <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                            <input class="form-control" type="text"  id="datepicker_Onset" name="datepicker_Onset" readonly="" value="<?php
                                            if (!empty($this->result)) {
                                                echo $this->result[0]['date_onset'];
                                            }
                                            ?>">
                                            <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type='button' id='remove_onset' name='remove_onset'><i class="fa fa-trash-o"></i></button>
                                            </span>  </div>

                                    </div>
                                </div>
                            </div>

                            <div class="row">


                                <input type="hidden" name="case_no" id="case_no" value="">




                            </div>

                            <h4 class="form-section" style="color:white;background-color: #58d68d;padding:5px  12px 12px 20px">Case Details</h4>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="province">
                                                Province
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <select class="form-control" id="province" name="province">
                                                <option value=""><?php echo $this->translate("Select"); ?></option>
                                                <?php
                                                foreach ($this->province as $row) {
                                                    if ($this->result[0]['province_id'] == $row['pkId']) {
                                                        $sel = "selected='selected'";
                                                    } else {
                                                        $sel = "";
                                                    }
                                                    ?>
                                                    <option value="<?php echo $row['pkId']; ?>" <?php echo $sel; ?> >
                                                        <?php echo $row['locationName']; ?>
                                                    </option>
                                                    <?php
                                                }
                                                ?>

                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="district">
                                                District  <span style="color:red;">*</span>
                                            </label>
                                        </div>

                                        <input type="hidden" id="tehsil_id_hidden" name="tehsil_id_hidden" value="<?php
                                        if (!empty($this->result)) {
                                            echo $this->result[0]['tehsil_id'];
                                        }
                                        ?>">
                                        <input type="hidden" id="uc_id_hidden" name="uc_id_hidden" value="<?php
                                        if (!empty($this->result)) {
                                            echo $this->result[0]['uc_id'];
                                        }
                                        ?>">

                                        <input type="hidden" id="hf_id_hidden" name="hf_id_hidden" value="<?php
                                        if (!empty($this->result)) {
                                            echo $this->result[0]['hf_id'];
                                        }
                                        ?>">

                                        <input type="hidden" id="vpd_id" name="vpd_id" value="<?php
                                        if (empty($this->is_draft)) {
                                            if (!empty($this->result)) {
                                                echo $this->result[0]['pk_id'];
                                            }
                                        }
                                        ?>">
                                        <input type="hidden" id="district_code" name="district_code" value="">
                                        <div class="col-md-6">
                                            <select class="form-control" id="district" name="district">
                                                <option value=""><?php echo $this->translate("Select"); ?></option>
                                                <?php
                                                foreach ($this->district as $row) {
                                                    if ($this->result[0]['district_id'] == $row['pkId']) {
                                                        $sel = "selected='selected'";
                                                    } else {
                                                        $sel = "";
                                                    }
                                                    ?>
                                                    <option value="<?php echo $row['pkId']; ?>" <?php echo $sel; ?> >
                                                        <?php echo $row['locationName']; ?>
                                                    </option>
                                                    <?php
                                                }
                                                ?>

                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="tehsil">
                                                Tehsil/Taluka
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <select class="form-control" id="tehsil" name="tehsil">
                                                <option value=""><?php echo $this->translate("Please Select District"); ?></option>


                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">

                                        <div class="col-md-5">
                                            <label class="control-label" for="ucs">
                                                UC
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <select class="form-control" id="ucs" name="ucs">
                                                <option value=""><?php echo $this->translate("Please Select Tehsil"); ?></option>

                                            </select>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="address_town">
                                                Village/Area  <span style="color:red;">*</span>
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <textarea class="form-control"  id="address_town" name="address_town" rows="1"><?php
                                                if (!empty($this->result)) {
                                                    echo $this->result[0]['address_village'];
                                                }
                                                ?></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="address1">
                                                House # OR Nearest Area<span style="color:red;">*</span>
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <textarea class="form-control"  id="address1" name="address1" rows="1"><?php
                                                if (!empty($this->result)) {
                                                    echo $this->result[0]['complete_address'];
                                                }
                                                ?></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">


                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="child_name">
                                                Child Name <span style="color:red;">*</span>
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <input class="form-control" type="text" id="child_name" name="child_name"  value="<?php
                                            if (!empty($this->result)) {
                                                echo $this->result[0]['child_name'];
                                            }
                                            ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="father_name">
                                                Father Name <span style="color:red;">*</span>
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <input class="form-control" type="text" id="father_name" name="father_name"  value="<?php
                                            if (!empty($this->result)) {
                                                echo $this->result[0]['father_name'];
                                            }
                                            ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="contact_number">
                                                Contact Number
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <input class="form-control" type="text" name="contact_number" id="contact_number"  value="<?php
                                            if (!empty($this->result)) {
                                                echo $this->result[0]['contact_number'];
                                            }
                                            ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="gender">
                                                Gender
                                            </label>
                                        </div>


                                        <div class="btn-group col-md-6" data-toggle="buttons">
                                            <label class="btn btn-default active" >
                                                <input class="toggle" name="gender" id="male" value="1"   type="radio" checked="" > Male
                                            </label>
                                            <label class="btn btn-default ">
                                                <input class="toggle" name="gender" id="female" value="0"  type="radio"> Female
                                            </label>

                                        </div>
                                    </div>
                                </div>


                            </div>
                            <br>

                            <div class="row">





                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="date">
                                                Date of Birth
                                            </label>
                                        </div>


                                        <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                            <input class="form-control" type="text"  id="birth_date" name="birth_date" readonly="" value="<?php
                                            if (!empty($this->result)) {
                                                echo $this->result[0]['dob'];
                                            }
                                            ?>"><i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>


                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type='button' id='remove_dob' name='remove_dob'><i class="fa fa-trash-o"></i></button>
                                            </span>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-5">
                                        <label class="control-label" for="age_month">
                                            <span id="l_age">  Age in Month </span> <span style="color:red;">*</span>
                                        </label>
                                    </div>
                                    <div class="form-group">
                                        <div class="input-group col-md-6 " style="padding-left:3%">
                                            <div class="input-group-btn">
                                                <select id="age_unit" name="age_unit" class="btn default" style="margin-right: 0 !important;  height:33px !important;"><option value="1">Months</option><option value="2">Days</option><option value="3">Year</option></select>
                                            </div>
                                            <!-- /btn-group -->
                                            <input class="form-control"  type="text" name="age_month" id="age_month" value="<?php
                                            if (!empty($this->result)) {
                                                echo $this->result[0]['age_in_month'];
                                            }
                                            ?>">
                                        </div>
                                    </div>

                                </div>


                            </div>
                            <br>
                            <div class="form-group" id="place_birth_div" style="display:none;">
                                <div class="col-md-5" >
                                    <label class="control-label" for="place_of_birth" >
                                        Place of Birth
                                    </label>
                                </div>
                                <div class="col-md-6">
                                    <select class="form-control" id="place_of_birth" name="place_of_birth">
                                        <option value=""><?php echo $this->translate("Select"); ?></option>
                                        <?php
                                        foreach ($this->place_of_birth as $row) {
                                            if ($this->result[0]['place_of_birth'] == $row['pkId']) {
                                                $sel = "selected='selected'";
                                            } else {
                                                $sel = "";
                                            }
                                            ?>
                                            <option value="<?php echo $row['pkId']; ?>" <?php echo $sel; ?>>
                                                <?php echo $row['listValue']; ?>
                                            </option>
                                            <?php
                                        }
                                        ?>

                                    </select>
                                </div>
                                <br>
                            </div>

                            <div class="form-group" id="birth_attendee_div" style="display:none;">
                                <br>
                                <div class="col-md-5" >
                                    <label class="control-label" for="birth_attendee" >
                                        Birth Attendee
                                    </label>
                                </div>
                                <div class="col-md-6">
                                    <select class="form-control" id="birth_attendee" name="birth_attendee">
                                        <option value=""><?php echo $this->translate("Select"); ?></option>
                                        <?php
                                        foreach ($this->birth_attendee as $row) {
                                            if ($this->result[0]['birth_attendee'] == $row['pkId']) {
                                                $sel = "selected='selected'";
                                            } else {
                                                $sel = "";
                                            }
                                            ?>
                                            <option value="<?php echo $row['pkId']; ?>" <?php echo $sel; ?>>
                                                <?php echo $row['listValue']; ?>
                                            </option>
                                            <?php
                                        }
                                        ?>

                                    </select>
                                </div>
                                <br>
                            </div>


                            <h4 class="form-section" style="color:white;background-color: #58d68d;padding:5px  12px 12px 20px">Investigation Detail</h4>
                            <div class="row">


                                <div class="col-md-12">
                                    <div class="col-md-5">
                                        <label>EPID Number</label>
                                    </div>
                                    <div class="col-md-6">
                                        <input class="form-control " type="text" id="epid_number" name="epid_number"  value="<?php
                                        if (!empty($this->result)) {
                                            echo $this->result[0]['epid_number'];
                                        }
                                        ?>">
                                        <p class="help-block">E.g PK/SD/District Code/Year/Case/Case No</p>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="date_Investigation">
                                                Date of Investigation<span style="color:red;">*</span>
                                            </label>
                                        </div>


                                        <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                            <input class="form-control" type="text"  id="datepicker_Investigation" name="datepicker_Investigation" readonly="" value="<?php
                                            if (!empty($this->result)) {
                                                echo $this->result[0]['date_investigation'];
                                            }
                                            ?>">
                                            <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type='button' id='remove_inv' name='remove_inv'><i class="fa fa-trash-o"></i></button>
                                            </span>  </div>

                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12" id="has_received">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="has_child_received">
                                                <span id="has_vacc">  Has Child Received </span>
                                            </label>
                                        </div>

                                        <div class="btn-group col-md-6" data-toggle="buttons">
                                            <label class="btn btn-default active" >
                                                <input class="toggle" name="has_child_received" id="hyes" value="1"   type="radio" checked=""> Yes
                                            </label>
                                            <label class="btn btn-default ">
                                                <input class="toggle" name="has_child_received" id="hno" value="0" type="radio"> No
                                            </label>
                                            <label class="btn btn-default ">
                                                <input class="toggle" name="has_child_received" id="hna" value="0" type="radio"> DK
                                            </label>

                                        </div>
                                    </div>


                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12" id="vacc_dose_rec">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="Vaccine_Doses_Recived">
                                                No of Vaccine Doses Received
                                            </label>
                                        </div>
                                        <div class="col-md-6">
                                            <select class="form-control" id="Vaccine_Doses_Recived" name="Vaccine_Doses_Recived">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                                <option value="6">6</option>
                                                <option value="7">7</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div  id="vacc_div">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label" for="l_v_d_received">
                                                    Date of Last Vaccine Dose Received
                                                </label>
                                            </div>
                                            <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                                <input class="form-control" type="text"  id="l_v_d_received" name="l_v_d_received" readonly="" value="<?php
                                                if (!empty($this->result)) {
                                                    echo $this->result[0]['date_last_dose_received'];
                                                }
                                                ?>">
                                                <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                                <span class="input-group-btn">
                                                    <button class="btn btn-default" type='button' id='remove_date' name='remove_date'><i class="fa fa-trash-o"></i></button>
                                                </span>

                                            </div>

                                        </div>

                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">

                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label" for="check_l_v_d_received">
                                                    No. of months before <span style="color:red;">*</span>
                                                </label>
                                            </div>
                                            <div class="col-md-6 input-group" style="padding-left:3%">
                                                <span class="input-group-addon">
                                                    <span class=""><input type="checkbox" id="check_l_v_d_received" name="check_l_v_d_received"></span>
                                                </span>
                                                <input class="form-control" type="text"  id="l_v_d_received_other" name="l_v_d_received_other" readonly="">
                                            </div>



                                        </div>
                                    </div>
                                </div>
                                <div  id="pab" style="display:none;">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <div class="col-md-5">
                                                    <label class="control-label" for="is_child_protected">
                                                        Is the Child Protected at Birth PAB
                                                    </label>
                                                </div>

                                                <div class="col-md-6 btn-group" data-toggle="buttons">
                                                    <label class="btn btn-default active" >
                                                        <input class="toggle" name="is_child_protected" id="hyes" value="1"   type="radio" checked=""> Yes
                                                    </label>
                                                    <label class="btn btn-default ">
                                                        <input class="toggle" name="is_child_protected" id="hno" value="0" type="radio"> No
                                                    </label>
                                                    <a data-toggle="modal" title="view" href="#is_pbas">Guide</a>
                                                </div>

                                            </div>


                                        </div>

                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label">Sign & Symptoms<span style="color:red;">*</span></label>
                                            </div>
                                            <?php
                                            foreach ($this->clinical_presentation as $row2) {

                                                $sel_array[] = $row2['clinical_presentation_id'];
                                            }
                                            ?>
                                            <div class="col-md-5">
                                                <select style="width: 151px !important;" id="clinical_presentation" name="clinical_presentation[]" class="form-control " multiple="" tabindex="-1">

                                                    <?php
                                                    foreach ($this->result_sign as $row) {

                                                        if (in_array($row['pkId'], $sel_array)) {

                                                            $sel_var = 'selected="selected"';
                                                        } else {
                                                            $sel_var = '';
                                                        }
                                                        ?>
                                                        <option value="<?php echo $row['pkId']; ?>" <?php echo $sel_var; ?> >
                                                            <?php echo $row['listValue']; ?>
                                                        </option>
                                                        <?php
                                                    }
                                                    ?>


                                                </select>

                                            </div>
                                            <div class="col-md-2">
                                                <a style="margin-left:-70px; " title="<?php echo $this->translate("Add New Catalogue"); ?>" href="#modal-new-catalogue" data-toggle="modal" onclick="javascript:void(0);" class="btn default btn-small">
                                                    <?php echo $this->translate("Add"); ?>
                                                </a>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                                <h4 class="form-section" style="color:white;background-color: #58d68d;padding:5px  12px 12px 20px">Specimen Collection & Result</h4>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label" for="Specimen_Collection">
                                                    Specimen Collection
                                                </label>
                                            </div>

                                            <div class="btn-group col-md-6" data-toggle="buttons" id="specimen">
                                                <label class="btn btn-default active"  >
                                                    <input class="toggle"  name="Specimen_Collection" value="1" id="Yes"  type="radio" checked=""> Yes
                                                </label>
                                                <label class="btn btn-default ">
                                                    <input class="toggle" name="Specimen_Collection" value="0" id="No" type="radio" > No
                                                </label>

                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <br>

                                <div   id="div_specimen_sent">
                                    <div class="row">
                                        <div class="col-md-12" >
                                            <div class="form-group">
                                                <div class="col-md-5">
                                                    <label class="control-label" for="date_of_specimen_sent" id="d1" name="d1">
                                                        Date of Specimen Sent1
                                                    </label>
                                                </div>
                                                <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                                    <input class="form-control" type="text"  id="date_of_specimen_sent" name="date_of_specimen_sent" readonly="" value="<?php
                                                    if (!empty($this->result)) {
                                                        echo $this->result[0]['date_specimen_sent'];
                                                    }
                                                    ?>">
                                                    <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                                    <span class="input-group-btn">
                                                        <button class="btn btn-default" type='button' id='remove_sp_1' name='remove_sp_1'><i class="fa fa-trash-o"></i></button>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12" >
                                            <div class="form-group">
                                                <div class="col-md-5">
                                                    <label class="control-label" for="date_of_specimen_sent1" id="d2" name="d2">
                                                        Date of Specimen Sent2
                                                    </label>
                                                </div>

                                                <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                                    <input class="form-control" type="text"  id="date_of_specimen_sent1" name="date_of_specimen_sent1" readonly="" value="<?php
                                                    if (!empty($this->result)) {
                                                        echo $this->result[0]['date_specimen_sent1'];
                                                    }
                                                    ?>">
                                                    <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                                    <span class="input-group-btn">
                                                        <button class="btn btn-default" type='button' id='remove_sp_2' name='remove_sp_2'><i class="fa fa-trash-o"></i></button>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12" id="div_StoolSampleDate1" style="display:none;">
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label" for="StoolSampleDate1" >
                                                Stool Sample Date 1
                                            </label>
                                        </div>


                                        <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                            <input class="form-control" type="text"  id="StoolSampleDate1" name="StoolSampleDate1" readonly="" value="<?php
                                            if (!empty($this->result)) {
                                                echo $this->result[0]['stool_sample_date1'];
                                            }
                                            ?>">
                                            <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type='button' id='remove_st1' name='remove_st1'><i class="fa fa-trash-o"></i></button>
                                            </span>
                                        </div>
                                    </div>
                                    <br>
                                </div>


                                <div class="row">
                                    <div class="col-md-12"id="div_StoolSampleDate2" style="display:none;">
                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label" for="StoolSampleDate2" >
                                                    Stool Sample Date 2
                                                </label>
                                            </div>
                                            <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                                <input class="form-control" type="text"  id="StoolSampleDate2" name="StoolSampleDate2" readonly="" value="<?php
                                                if (!empty($this->result)) {
                                                    echo $this->result[0]['stool_sample_date2'];
                                                }
                                                ?>">
                                                <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                                <span class="input-group-btn">
                                                    <button class="btn btn-default" type='button' id='remove_st2' name='remove_st2'><i class="fa fa-trash-o"></i></button>
                                                </span>
                                            </div>
                                        </div>
                                        <br>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-12" id="div_Blood_Sample_Date" style="display:none;">
                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label" for="Blood_Sample_Date">
                                                    Blood Sample Collection Date
                                                </label>
                                            </div>

                                            <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                                <input class="form-control" type="text"  id="Blood_Sample_Date" name="Blood_Sample_Date" readonly="" value="<?php
                                                if (!empty($this->result)) {
                                                    echo $this->result[0]['blood_sample_date'];
                                                }
                                                ?>">
                                                <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                                <span class="input-group-btn">
                                                    <button class="btn btn-default" type='button' id='remove_bt1' name='remove_bt1'><i class="fa fa-trash-o"></i></button>
                                                </span>
                                            </div>
                                        </div>
                                        <br>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12" id="div_Throad_Swab_Date" style="display:none;">
                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label" for="Throad-Swab_Date">
                                                    Throat-Swab Collection Date
                                                </label>
                                            </div>
                                            <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                                <input class="form-control" type="text"  id="Throad_Swab_Date" name="Throad_Swab_Date" readonly="" value="<?php
                                                if (!empty($this->result)) {
                                                    echo $this->result[0]['blood_sample_date'];
                                                }
                                                ?>">
                                                <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                                <span class="input-group-btn">
                                                    <button class="btn btn-default" type='button' id='remove_t2' name='remove_t2'><i class="fa fa-trash-o"></i></button>
                                                </span>
                                            </div>
                                        </div>
                                        <br>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12" id="div_Naso_Pharyngeal_Swab_Date" style="display:none;">
                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label" for="Naso_Pharyngeal_Swab_Date">
                                                    Naso Pharyngeal Swab Date
                                                </label>
                                            </div>

                                            <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                                <input class="form-control" type="text"  id="Naso_Pharyngeal_Swab_Date" name="Naso_Pharyngeal_Swab_Date" readonly="" value="<?php
                                                if (!empty($this->result)) {
                                                    echo $this->result[0]['blood_sample_date'];
                                                }
                                                ?>">
                                                <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                                <span class="input-group-btn">
                                                    <button class="btn btn-default" type='button' id='remove_n1' name='remove_n1'><i class="fa fa-trash-o"></i></button>
                                                </span>
                                            </div>
                                        </div>
                                        <br>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12" id="div_Sputum_Collection_Date_1" style="display:none;">
                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label" for="Sputum_Collection_Date_1">
                                                    Sputum Collection Date 1
                                                </label>
                                            </div>

                                            <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                                <input class="form-control" type="text"  id="Sputum_Collection_Date_1" name="Sputum_Collection_Date_1" readonly="" value="<?php
                                                if (!empty($this->result)) {
                                                    echo $this->result[0]['blood_sample_date'];
                                                }
                                                ?>">
                                                <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                                <span class="input-group-btn">
                                                    <button class="btn btn-default" type='button' id='remove_spt1' name='remove_spt1'><i class="fa fa-trash-o"></i></button>
                                                </span>
                                            </div>
                                        </div>
                                        <br> </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12" id="div_Sputum_Collection_Date_2" style="display:none;">
                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label" for="Sputum_Collection_Date_2">
                                                    Sputum Collection Date 2
                                                </label>
                                            </div>

                                            <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                                <input class="form-control" type="text"  id="Sputum_Collection_Date_2" name="Sputum_Collection_Date_2" readonly="" value="<?php
                                                if (!empty($this->result)) {
                                                    echo $this->result[0]['blood_sample_date'];
                                                }
                                                ?>">
                                                <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                                <span class="input-group-btn">
                                                    <button class="btn btn-default" type='button' id='remove_spt2' name='remove_spt2'><i class="fa fa-trash-o"></i></button>
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <h4 class="form-section" style="color:white;background-color: #58d68d;padding:5px  12px 12px 20px">Present Status</h4>
                                <div class="row">
                                    <div class="col-md-12" id="div_lab_result">
                                        <div class="form-group" >
                                            <div class="col-md-5">
                                                <label class="control-label" for="lab_result_test">
                                                    Lab Result of the Test
                                                </label>
                                            </div>

                                            <div class="col-md-6">
                                                <select class="form-control" id="lab_result_test" name="lab_result_test">
                                                    <option value=""><?php echo $this->translate("Select"); ?></option>
                                                    <?php
                                                    foreach ($this->lab_result as $row) {
                                                        if ($this->result[0]['lab_result'] == $row['pkId']) {
                                                            $sel = "selected='selected'";
                                                        } else {
                                                            $sel = "";
                                                        }
                                                        ?>
                                                        <option value="<?php echo $row['pkId']; ?>" <?php echo $sel; ?>>
                                                            <?php echo $row['listValue']; ?>
                                                        </option>
                                                        <?php
                                                    }
                                                    ?>

                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>   <br>
                                <div class="row">
                                    <div class="col-md-12" id="div_specimen_sent1">
                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label" for="date_of_lab_resulted">
                                                    Date of Lab Result Received
                                                </label>
                                            </div>
                                            <div style="padding-left:3%" class="col-md-6 input-group input-medium date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                                <input class="form-control" type="text"  id="date_of_lab_resulted" name="date_of_lab_resulted" readonly="" value="<?php
                                                if (!empty($this->result)) {
                                                    echo $this->result[0]['date_of_lab_resulted'];
                                                }
                                                ?>">
                                                <i class="fa fa-calendar form-control-feedback" style="margin-top:-14px;margin-right:14%;"></i></input>

                                                <span class="input-group-btn">
                                                    <button class="btn btn-default" type='button' id='remove_lab' name='remove_lab'><i class="fa fa-trash-o"></i></button>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>   <br>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label" for="final_classification">
                                                    Final Classification <span style="color:red;">*</span>
                                                </label>
                                            </div>
                                            <div class="col-md-6">
                                                <select class="form-control" id="final_classification" name="final_classification">
                                                    <option value=""><?php echo $this->translate("Select"); ?></option>
                                                    <?php
                                                    foreach ($this->final_class as $row) {
                                                        if ($this->result[0]['final_classification'] == $row['pkId']) {
                                                            $sel = "selected='selected'";
                                                        } else {
                                                            $sel = "";
                                                        }
                                                        ?>

                                                        <option value="<?php echo $row['pkId']; ?>" <?php echo $sel; ?> >
                                                            <?php echo $row['listValue']; ?>
                                                        </option>
                                                        <?php
                                                    }
                                                    ?>

                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>   <br>
                                <div class="row">

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="col-md-5">
                                                <label class="control-label" for="outcome">
                                                    Outcome <span style="color:red;">*</span>
                                                </label>
                                            </div>
                                            <div class="col-md-6">
                                                <select class="form-control" id="outcome" name="outcome">
                                                    <option value=""><?php echo $this->translate("Select"); ?></option>
                                                    <?php
                                                    foreach ($this->outcome as $row) {
                                                        if ($this->result[0]['outcome'] == $row['pkId']) {
                                                            $sel = "selected='selected'";
                                                        } else {
                                                            $sel = "";
                                                        }
                                                        ?>
                                                        <option value="<?php echo $row['pkId']; ?>" <?php echo $sel; ?>>
                                                            <?php echo $row['listValue']; ?>
                                                        </option>
                                                        <?php
                                                    }
                                                    ?>

                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>


                        </div>
                        <div class="form-actions fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-offset-3 col-md-9">
                                        <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit">
                                            <i class="glyphicon glyphicon-ok"></i>   <?php echo $this->translate("Save"); ?>
                                        </button>
                                        <button type="button" class="btn default" id="reset_form" name="reset_form">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>






                    </div>

                </div>
            </form>

            <div class="col-md-7" style="margin-top:2%">
                <div class="portlet box green">
                    <div class="portlet-title" style="background-color:#58d68d;">
                        <div class="caption">
                            <?php echo $this->translate("Vaccine Preventable Disease Report") ?>
                        </div>
                        <div class="tools">

                            <a href="javascript:;" class="reload" style="visibility: hidden"></a>

                        </div>

                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="dataTables_wrapper form-inline table-responsive" id="ajax-table" >

                                    <table class="table table-striped table-bordered table-hover dataTable no-footer" id="sample_29">
                                        <!-- Table heading -->


                                        <thead>
                                            <tr>
                                                <th rowspan="2">S.No</th>
                                                <th colspan="3" class="center">Type of Case</th>
                                                <th colspan="7" class="center">Reporting Sites</th>
                                                <th colspan="14" class="center">Case Details</th>
                                                <th colspan="6" class="center">Investigation Detail</th>
                                                <th colspan="5" class="center">Specimen Collection & Result</th>
                                                <th colspan="4" class="center">Present Status</th>



                                                <th class="nonprint" rowspan="2">&nbsp;</th>
                                            </tr>
                                            <tr>

                                                <th>Reporting Date</th>
                                                <th>Week</th>
                                                <th>Type of case</th>




                                                <th>Reporting Ucs</th>
                                                <th>Surveillance Sites</th>
                                                <th>Cross Notificaion</th>
                                                <th>Patient Visited Date</th>
                                                <th>Date of Onset</th>
                                                <th>Date of Notification</th>
                                                <th>EPID Number</th>



                                                <th>Province</th>
                                                <th>District</th>
                                                <th>Tehsil/Taluka</th>
                                                <th>UC</th>
                                                <th>Village/Town</th>
                                                <th>Address</th>
                                                <th>Child Name</th>
                                                <th>Father Name</th>
                                                <th>Contact Number</th>
                                                <th>Gender</th>
                                                <th>Date of Birth</th>
                                                <th>Age</th>
                                                <th>Place of Birth</th>
                                                <th>Birth Attendee</th>


                                                <th>Date of Investigation</th>
                                                <th>Vaccine Received</th>
                                                <th>No of Vaccine Doses Received</th>
                                                <th>Date of Last Vaccine Dose Received</th>
                                                <th>No. of months before</th>
                                                <th>Sign & Symptoms</th>



                                                <th>Specimen Collection</th>
                                                <th>Date of Specimen Sent 1 </th>
                                                <th>Date of Specimen Sent 2 </th>
                                                <th id="d1" name="d1">Stool Sample Date 1 </th>
                                                <th id="d2" name="d2">Stool Sample Date 2  </th>
                                    <!--            <th >Sputum Collection Date 1  </th>
                                                <th  >Sputum Collection Date 2 </th>
                                                <th  >Throat-Swab Collection Date (Diptheria) </th>
                                                <th  >Naso Pharyngeal Swab Date (Diptheria)</th>
                                                <th  >Blood Sample Collection Date(Measles)</th>
                                                <th  >Throat-Swab Collection Date (Measles)</th>
                                                <th  >Blood Sample Collection Date (NNT)</th>
                                                <th  >Throat-Swab Collection Date (NNT) </th>

                                                <th  >Throat-Swab Collection Date(Pertussis) </th>
                                                <th  >Naso Pharyngeal Swab Date (Pertussis)</th>-->


                                                <th>Lab Result of the Test</th>
                                                <th>Date of Lab Result Received</th>
                                                <th>Final Classification</th>
                                                <th>Outcome</th>

                                            </tr>
                                        </thead>
                                        <!-- // Table heading END -->
                                        <!-- Table body -->

                                        <!-- // Table body END -->
                                        <tbody >
                                            <?php
                                            $m_res = array();
                                            $i = 1;
                                            if ($this->search_result && count($this->search_result) > 0) :
                                                foreach ($this->search_result as $row):
                                                    ?>
                                                    <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                        <td class="center" width="25"><?php echo $i; ?></td>
                                                        <td><?php echo date("d/m/Y", strtotime($row['date'])); ?></td>
                                                        <td><?php echo $row['week']; ?></td>
                                                        <td><?php echo $row['typeCase']; ?></td>
                                                        <td><?php echo $row['from_uc']; ?></td>
                                                        <td><?php echo $row['s_site']; ?></td>
                                                        <td><?php
                                                            if ($row['cross_notification'] == 1) {
                                                                echo 'Yes';
                                                            } else {
                                                                echo 'No';
                                                            }
                                                            ?></td>
                                                        <td><?php
                                                            if (strtotime($row['patient_visited_date']) == null) {
                                                                echo '';
                                                            } else {

                                                                echo date("d/m/Y", strtotime($row['patient_visited_date']));
                                                            }
                                                            ?></td>
                                                        <td><?php
                                                            if (empty(strtotime($row['date_onset']))) {
                                                                echo '';
                                                            } else if (!empty(strtotime($row['date_onset']))) {


                                                                echo date("d/m/Y", strtotime($row['date_onset']));
                                                            }
                                                            ?></td>
                                                        <td><?php
                                                            if (empty(strtotime($row['date_notification']))) {
                                                                echo '';
                                                            } else if (!empty(strtotime($row['date_notification']))) {

                                                                echo date("d/m/Y", strtotime($row['date_notification']));
                                                            }
                                                            ?></td>
                                                        <td><?php echo $row['epid_number']; ?></td>

                                                        <td><?php echo $row['province']; ?></td>
                                                        <td><?php echo $row['district']; ?></td>
                                                        <td><?php echo $row['tehsil']; ?></td>
                                                        <td><?php echo $row['uc']; ?></td>
                                                        <td><?php echo $row['address_village']; ?></td>
                                                        <td><?php echo $row['address1']; ?></td>
                                                        <td><?php echo $row['child_name']; ?></td>
                                                        <td><?php echo $row['father_name']; ?></td>
                                                        <td><?php echo $row['contact_number']; ?></td>

                                                        <td><?php
                                                            if ($row['gender'] == 1) {
                                                                echo 'Male';
                                                            } else {
                                                                echo 'Female';
                                                            }
                                                            ?></td>
                                                        <td><?php
                                                            if (empty(strtotime($row['dob']))) {
                                                                echo '';
                                                            } else if (!empty(strtotime($row['dob']))) {
                                                                echo date("d/m/Y", strtotime($row['dob']));
                                                            }
                                                            ?></td>
                                                        <td><?php
                                                            echo $row['age'] . '';
                                                            if ($row['age_unit'] == 1) {
                                                                echo " month/s";
                                                            } else if ($row['age_unit'] == 2) {
                                                                echo " day/s";
                                                            } else if ($row['age'] == null) {

                                                                echo '';
                                                            } else {
                                                                echo " year/s";
                                                            }
                                                            ?></td>
                                                        <td><?php
                                                            if ($row['place_of_birth'] != null) {
                                                                echo $row['place_of_birth'];
                                                            } else {
                                                                echo '';
                                                            }
                                                            ?></td>
                                                        <td><?php
                                                            if ($row['attendee'] != null) {
                                                                echo $row['attendee'];
                                                            } else {
                                                                echo '';
                                                            }
                                                            ?></td>
                                                        <td><?php
                                                            if (empty(strtotime($row['date_investigation']))) {
                                                                echo '';
                                                            } else if (!empty(strtotime($row['date_investigation']))) {
                                                                echo date("d/m/Y", strtotime($row['date_investigation']));
                                                            }
                                                            ?></td><td><?php
                                                            if ($row['has_child_received_opv'] == 1) {
                                                                echo "Yes";
                                                            } else {
                                                                echo "No";
                                                            }
                                                            ?></td>
                                                        <td><?php echo $row['specific_dose_received']; ?></td>
                                                        <td><?php
                                                            if (strtotime($row['date_last_dose_received']) == null) {
                                                                echo '';
                                                            } else if (strtotime($row['date_last_dose_received']) != null) {
                                                                echo date("d/m/Y", strtotime($row['date_last_dose_received']));
                                                            }
                                                            ?></td>
                                                        <td><?php echo $row['number_of_months']; ?></td>
                                                        <td><?php echo $row['sign']; ?></td>
                                                        <td><?php
                                                            if ($row['specimen_collection'] == 1) {
                                                                echo "Yes";
                                                            } else {
                                                                echo "No";
                                                            }
                                                            ?></td>
                                                        <td><?php
                                                            if (strtotime($row['date_specimen_sent']) == null) {
                                                                echo '';
                                                            } else {
                                                                echo date("d/m/Y", strtotime($row['date_specimen_sent']));
                                                            }
                                                            ?></td>
                                                        <td><?php
                                                            if (strtotime($row['date_specimen_sent1']) == null) {
                                                                echo '';
                                                            } else {
                                                                echo date("d/m/Y", strtotime($row['date_specimen_sent1']));
                                                            }
                                                            ?></td>
                                                        <td ><?php
                                                            if ($row['typeCase'] == 'AFP' && strtotime($row['stool_sample_date_1']) != null) {
                                                                echo date("d/m/Y", strtotime($row['stool_sample_date_1']));
                                                            } else if ($row['typeCase'] == 'Childhood TB' && strtotime($row['blood_sample_date']) != null) {
                                                                echo date("d/m/Y", strtotime($row['blood_sample_date']));
                                                            } else if ($row['typeCase'] == 'Diptheria' && strtotime($row['blood_sample_month']) != null) {
                                                                echo date("d/m/Y", strtotime($row['blood_sample_month']));
                                                            } else if ($row['typeCase'] == 'Measles' && strtotime($row['blood_sample_date']) != null) {
                                                                echo date("d/m/Y", strtotime($row['blood_sample_date']));
                                                            } else if ($row['typeCase'] == 'NNT' && strtotime($row['blood_sample_date']) != null) {
                                                                echo date("d/m/Y", strtotime($row['blood_sample_date']));
                                                            } else if ($row['typeCase'] == 'Pertussis' && strtotime($row['blood_sample_month']) != null) {
                                                                echo date("d/m/Y", strtotime($row['blood_sample_month']));
                                                            } else {

                                                                echo '';
                                                            }
                                                            ?> </td>
                                                        <td  ><?php
                                                            if ($row['typeCase'] == 'AFP' && strtotime($row['stool_sample_date_2']) != null) {
                                                                echo date("d/m/Y", strtotime($row['stool_sample_date_2']));
                                                            } else if ($row['typeCase'] == 'Childhood TB' && strtotime($row['blood_sample_month']) != null) {
                                                                echo date("d/m/Y", strtotime($row['blood_sample_month']));
                                                            } else if ($row['typeCase'] == 'Diptheria' && strtotime($row['blood_sample_date']) != null) {
                                                                echo date("d/m/Y", strtotime($row['blood_sample_date']));
                                                            } else if ($row['typeCase'] == 'Measles' && strtotime($row['blood_sample_month']) != null) {
                                                                echo date("d/m/Y", strtotime($row['blood_sample_month']));
                                                            } else if ($row['typeCase'] == 'NNT' && strtotime($row['blood_sample_month']) != null) {
                                                                echo date("d/m/Y", strtotime($row['blood_sample_month']));
                                                            } else if ($row['typeCase'] == 'Pertussis' && strtotime($row['blood_sample_date']) != null) {
                                                                echo date("d/m/Y", strtotime($row['blood_sample_date']));
                                                            } else {

                                                                echo '';
                                                            }
                                                            ?></td>

                                                        <td><?php echo $row['lab']; ?></td>
                                                        <td><?php
                                                            if (strtotime($row['date_of_lab_resulted']) != null) {
                                                                echo date("d/m/Y", strtotime($row['date_of_lab_resulted']));
                                                            } else
                                                                echo '';
                                                            ?></td>

                                                        <td><?php echo $row['final']; ?></td>
                                                        <td><?php
                                                            if ($row['outcome'] != null) {
                                                                echo $row['outcome'];
                                                            } else {
                                                                echo '';
                                                            }
                                                            ?></td>




                                                        <td>
                                                            <a href="<?php echo $this->baseUrl(); ?>/surveillance/vpd?id=<?php echo $row['pk_id']; ?>" class="update-locations btn btn-xs green" ><i class="fa fa-edit"></i><?php echo $this->translate("Edit") ?>
                                                            </a>
                                                            <?php if ($row['type_case'] != "No Case") { ?>
                                                                <input type="hidden" id="hdn_vpd_id" name="hdn_vpd_id" value="<?php echo $row['pk_id']; ?>">
                                                                <a pkid="<?php echo $row['pk_id']; ?>"  onclick="window.open('print-vpd?id=<?php echo $row['pk_id']; ?>', '_blank', 'scrollbars=1,width=840,height=595');" title="VPD Detail"  class="btn default btn-xs green-stripe detail">View</a>
                                                            <?php } ?>
                                                        </td>
                                                        <!-- // Table row END --><?php
                                                        $i++;

                                                    endforeach;

                                                endif;
                                                ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="modal fade" id="is_pbas" tabindex="-1" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">Ã—</button>
                        <h3>Time Schedule</h3>
                    </div>
                    <div class="modal-body" id="modal-body-contents">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Dose</th>
                                    <th>Time Schedule</th>
                                    <th>Protection</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1st</td>
                                    <td>At First Contact</td>
                                    <td>Nil</td>
                                </tr>
                                <tr class="success">
                                    <td>2nd</td>
                                    <td>4 weeks after 1st dose</td>
                                    <td>3 Years</td>
                                </tr>
                                <tr class="danger">
                                    <td>3rd</td>
                                    <td>6 weeks after 2nd dose</td>
                                    <td>5 Years</td>
                                </tr>
                                <tr class="info">
                                    <td>4th</td>
                                    <td>1 year after 3rd dose</td>
                                    <td>10 Years</td>
                                </tr>
                                <tr class="warning">
                                    <td>5th</td>
                                    <td>1 year after 4th dose</td>
                                    <td>Life Time</td>
                                </tr>

                            </tbody>
                        </table>


                    </div>
                </div>
            </div>
        </div>
        <!-- // Content END -->
        <!-- // Asset Add Popup  add-new-make-model-->
        <form name="asset_add_popup" id="asset_add_popup" action="" method="POST">
            <div class="modal fade" id="modal-new-catalogue"  tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <!--    <div id="modal-new-catalogue" class="modal hide fade in" style="display: none;" aria-hidden="false">-->
                        <!-- Modal heading -->
                        <div class="modal-header">
                            <button aria-hidden="true" data-dismiss="modal" class="close" type="button">Ã—</button>
                            <h4 class="modal-title"><?php echo $this->translate("Suggest new Sign & Symptoms"); ?></h4>
                        </div>
                        <!-- Modal body -->
                        <div class="modal-body">
                            <!-- BODY HERE -->
                            <div class="row">
                                <div class="col-md-12 margin-bottom" >
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label" for="catalogueid" ><?php echo $this->translate("Sign & Symptoms"); ?> <span class="red">*</span></label>
                                            <input class="form-control" type="text" id="sign" name="sign">
                                        </div>


                                    </div>

                                </div>

                            </div>
                            <!-- // Modal body END -->

                            <!-- Modal footer -->
                            <div class="modal-footer">
                                <a data-dismiss="modal" class="btn btn-default" href="#"><?php echo $this->translate("Close"); ?></a>
                                <button class="btn btn-primary btn-small pull-right btn-icon" type="submit" id="asset_add_popup-save" name="asset_add_popup-save">
                                    <?php echo $this->translate("Save"); ?>
                                </button>


                            </div>
                            <!-- // Modal footer END -->
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!-- // Asset Add Popup END  -->
        <div class="modal fade" id="modal-placement-history" tabindex="-1" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header" >
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">Ã—</button>
                        <h3>VPD Detail</h3>
                    </div>
                    <div class="modal-body" id="modal-body-contents"></div>
                </div>
            </div>
        </div>

        <script>
            $(document).ready(function () {

                $('#pulsate-regular').pulsate({
                    color: "#bf1c56"
                });
            });
        </script>