AefiForm:
  type: entity
  table: aefi_form
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    date:
      type: datetime
      nullable: true
    districtId:
      type: integer
      unsigned: false
      nullable: true
      column: district_id
    districtId1:
      type: integer
      unsigned: false
      nullable: true
      column: district_id1
    tehsilId:
      type: integer
      unsigned: false
      nullable: true
      column: tehsil_id
    tehsilId1:
      type: integer
      unsigned: false
      nullable: true
      column: tehsil_id1
    ucId:
      type: integer
      unsigned: false
      nullable: true
      column: uc_id
    ucId:
      type: integer
      unsigned: false
      nullable: true
      column: uc_id
    caseEpi:
      type: integer
      unsigned: false
      nullable: true
      column: case_epi
    hfId:
      type: integer
      unsigned: false
      nullable: true
      column: hf_id
    hfId1:
      type: integer
      unsigned: false
      nullable: true
      column: hf_id1
    hfName:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: hf_name
    otherCaseEpi:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: other_case_epi
    typeCase:
      type: integer
      unsigned: false
      nullable: true
      column: type_case  
    gender:
      type: integer
      unsigned: false
      nullable: true
    dob:
      type: datetime
      nullable: true
    expiryDate:
      type: datetime
      nullable: true
      column: expiry_date
    ageInMonths:
      type: integer
      unsigned: false
      nullable: true
      column: age_in_months
    dateVaccineGiven:
      type: datetime
      nullable: true
      column: date_vaccine_given
    dateAefiOnset:
      type: datetime
      nullable: true
      column: date_aefi_onset
    dateOfInvestigation:
      type: datetime
      nullable: true
      column: date_of_investigation
    aefi:
      type: integer
      unsigned: false
      nullable: true
    aefiOther:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: aefi_other
    hospitalization:
      type: integer
      unsigned: false
      nullable: true
    death:
      type: integer
      unsigned: false
      nullable: true
    vaccineAntigen:
      type: integer
      unsigned: false
      nullable: true
      column: vaccine_antigen
    batchId:
      type: integer
      unsigned: false
      nullable: true
      column: batch_id
    batchNumber:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: batch_number
    week:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: week 
    vaccinatorName:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: vaccinator_name
    designation:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: designation
    reportingStatus:
      type: integer
      unsigned: false
      nullable: true
      column: reporting_status
    childName:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: child_name
    fatherName:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: father_name
    address1:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: address1
    address2:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: address2
    addressVillage:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: address_village 
    contactNumber:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: contact_number
    ageUnit:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: age_unit
    dateNotification:
      type: datetime
      nullable: true
      column: date_notification
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    createdBy:
      type: integer
      unsigned: false
      nullable: true
      column: created_by
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
    modifiedBy:
      type: integer
      unsigned: false
      nullable: true
      column: modified_by
  lifecycleCallbacks: {  }
