EmailVerification:
  type: entity
  table: email_verification
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    userId:
      type: integer
      unsigned: false
      nullable: true
      column: user_id
    emailAddress:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: email_address
    isVerified:
      type: integer
      unsigned: false
      nullable: true
      column: is_verified
    createdDate:
      type: datetime
      nullable: true
      column: created_date
  lifecycleCallbacks: {  }
