LocationLog:
  type: entity
  table: location_log
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    locationName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: location_name
    population:
      type: integer
      unsigned: false
      nullable: true
      column: population
    ccmLocationId:
      type: integer
      unsigned: false
      nullable: true
      column: ccm_location_id   
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    district:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        district_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    geoLevel:
      targetEntity: GeoLevels
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        geo_level_id:
          referencedColumnName: pk_id
      orphanRemoval: false
   
    province:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        province_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    location:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        location_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    parent:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        parent_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
## YAML Template.
 
