ShipmentsReceive:
  type: entity
  table: shipments_receive
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    quantity:
      type: decimal
      nullable: true
    counter:
      type: integer
      unsigned: false
      nullable: true
      column: counter  
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    shipmentProductBatch:
      targetEntity: ShipmentProductBatch
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        shipment_product_batch_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    placementLocation:
      targetEntity: PlacementLocations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        placement_location_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    vvmStage:
      targetEntity: VvmStages
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        vvm_stage:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
