ShipmentProductBatch:
  type: entity
  table: shipment_product_batch
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    number:
      type: string
      length: 100
      fixed: false
      nullable: true
    expiryDate:
      type: date
      nullable: true
      column: expiry_date
    unitPrice:
      type: float
      nullable: true
      column: unit_price
    quantity:
      type: bigint
      nullable: true  
    draft:
      type: boolean
      nullable: true   
    productionDate:
      type: date
      nullable: true
      column: production_date
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    vvmType:
      targetEntity: VvmTypes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        vvm_type_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    shipment:
      targetEntity: Shipments
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        shipment_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stakeholderItemPackSize:
      targetEntity: StakeholderItemPackSizes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stakeholder_item_pack_size_id:
          referencedColumnName: pk_id
      orphanRemoval: false  
    itemPackSize:
      targetEntity: ItemPackSizes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_pack_size_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }