Survey:
  type: entity
  table: survey
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
    email:
      type: string
      length: 255
      fixed: false
      nullable: false
    department:
      type: string
      length: null
      fixed: false
      nullable: false
    office:
      type: string
      length: null
      fixed: false
      nullable: false
    cellNumber:
      type: integer
      unsigned: false
      nullable: false
      column: cell_number
    q1DataDifficulty:
      type: text
      nullable: true
      column: q1_data_difficulty
    q2Report:
      type: text
      nullable: true
      column: q2_report
    comment:
      type: text
      nullable: true
    q1YN:
      type: text
      nullable: false
      column: q1_y_n
    q2YN:
      type: text
      nullable: false
      column: q2_y_n
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    user:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
