UserClickPaths:
  type: entity
  table: user_click_paths
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    sessionId:
      type: string
      length: 255
      fixed: false
      nullable: false
      column: session_id
    createdDate:
      type: datetime
      nullable: false
      column: created_date
  oneToOne:
    user:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    resource:
      targetEntity: Resources
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        resource_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    province:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        province_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    role:
      targetEntity: Roles
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        role_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
