VarElectronicDevice:
  type: entity
  table: var_electronic_device
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    boxNumber:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: box_number
    lotNo:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: lot_no 
    less45:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: less_45   
    less30:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: less_30
    less10:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: less_10  
    less5:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: less_5
    coldChainA:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: cold_chain_a 
    coldChainB:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: cold_chain_b
    coldChainC:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: cold_chain_c
    coldChainD:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: cold_chain_d
    dayOfInspection:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: day_of_inspection
    dateOfInspection:
      type: date
      nullable: true
      column: date_of_inspection
   
    createdDate:
      type: date
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    varDetail:
      targetEntity: VarDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        var_detail_id:
          referencedColumnName: pk_id
      orphanRemoval: false  
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
