<?php
/**
 *  phtml for Print Issue
 */
?>
<?php
ob_start();
?>
<style>
    #content_print {
        margin-left: 55px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #444;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #444;
    }
    table#mytable tr th {
        border: 1px solid #444;
    }
</style>

<style type="text/css" media="print">
    .page{
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print{    
        #printButt{
            display: none !important;
        }
    }
</style>
<?php
$row = $this->result[0];
$transaction_number = $row['transaction_number'];
$transaction_date = $row['shipment_date'];
$warehouse_name = $row['wh_name'];
//$comments = $row['comments'];
$reference = $row['reference_number'];

$master_id = $row['pk_id'];
$purpose = $row['activity'];
?>
<div class="row">
    <div class="col-md-12">
        <table style="width:100%;">
            <tr>
                <td class="center" colspan="4"><b style="font-size: 16px;"><?php echo $this->print_title; ?></b></td>
            </tr>
            <tr>
                <td colspan="4" class="right"><b style="font-size: 16px;">Shipment Voucher # <span style="font-family: Verdana; "><?php echo $transaction_number; ?></span> </b></td>
            </tr>
            <tr>
                <td colspan="4"><b>Date of Shipment:</b> <?php echo date("d/m/Y", strtotime($transaction_date)); ?></td>
            </tr>
            <tr>
                <?php if (!empty($purpose)) { ?>
                    <td><b>Purpose:</b> <?php echo $purpose; ?></td>
                <?php } ?>
                <td><b>Ref. Number:</b> <?php echo (!empty($reference)) ? $reference : 'N/A'; ?></td>
                <td><b>Recipient:</b> <?php echo $warehouse_name; ?></td>

            </tr>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-10">
        <table id="mytable" cellpadding="2">
            <tr >
                <th  width="5%"><?php echo $this->translate("Sr No"); ?></th>
                <th ><?php echo $this->translate("Product"); ?></th>
                <th ><?php echo $this->translate("Batch"); ?></th>
                <th ><?php echo $this->translate("Received Quanity"); ?></th>
                <th ><?php echo $this->translate("Unit"); ?></th>
                <th ><?php echo $this->translate("Manufacturer"); ?></th>
                <th ><?php echo $this->translate("Expiry Date"); ?></th>
                <th ><?php echo $this->translate("Placed Quanity"); ?></th>
                <th ><?php echo $this->translate("VVM Stage"); ?></th>
                <th ><?php echo $this->translate("Placement Location"); ?></th>


            </tr>

            <tbody>
                <?php
                $i = 0;
                if (!empty($this->result)) {
                    foreach ($this->result as $val) {
                        $i++;
                        ?>
                        <tr>
                            <td align="center"><?php echo $i; ?></td>
                            <td>
                                <?php echo $val['item_name']; ?>
                            </td>
                            <td class="id" >
                                <?php echo $val['number']; ?>
                            </td>
                            <td class="right" >
                                <?php echo number_format(abs($val['quantity'])); ?>
                            </td>
                            <td>
                                <?php echo $val['item_unit_name']; ?>
                            </td>
                            <td>
                                <?php echo $val['manufacturer']; ?>
                            </td>


                            <td>
                                <?php echo App_Controller_Functions::dateToUserFormat($val['expiry_date']); ?>
                            </td>

                            <td  class="right">
                                <?php echo number_format(abs($val['placed_qty'])); ?>
                            </td>
                            <td>
                                <?php echo $val['vvm_stage_value']; ?>
                            </td>
                            <td>
                                <?php echo $val['asset_id']; ?>
                            </td>

                        </tr>

                        <?php
                    }
                }
                ?>
            </tbody>
        </table>
        <br />
    </div>
</div>




<div class="row" style="clear: both; padding-top: 20px;">

</div><br>
<div class="row" style="clear: both;">
    <table width="100%">
        <tr>

            <td width="33%"><b>Printed By:</b> <?php echo $this->username; ?></td>            

        </tr>
    </table>
</div>

<div class="row" style="clear: both;">
    <div class="col-md-12 left">
        <b>Print Date:</b> <?php echo date("d/m/Y"); ?>
    </div>
</div>

<div class="col-md-12" class="widget">
    <div class="widget-body right">
        <button id="print" name="print" value="1" type="button" class="btn btn-primary" ><?php echo $this->translate("Print"); ?></button>
    </div>
</div>