<?php
/**
 *  phtml for Pipeline Consignments
 */
?>
<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content"> 

        <?php if (isset($this->error)) { ?>
            <div class="alert alert-danger alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button"></button>
                <strong>Error!</strong> <?php echo $this->msg; ?>
            </div>
        <?php } ?>
        <?php
        if (!empty($this->shipments_receive_voucher)) {
            $res = $this->shipments_receive_voucher;
            ?>
            <div class="note note-info">

                <?php echo $this->msg; ?>                                        
                Stock has been received successfully. Your voucher number is <a id="receive-print" onclick="window.open('print-receive?id=<?php echo $res[0]['pk_id']; ?>', '_blank', 'scrollbars=1,width=840,height=595');" href="javascript:void(0);"> <strong><?php echo $res[0]['voucher']; ?></strong></a>
            </div>    
        <?php } else { ?>

            <div class="row">
                <div class="col-md-12">
                    <div class="portlet box green">
                        <div class="portlet-title">

                            <div class="caption">
                               <a style="color:#fff;" href="<?php echo $this->baseUrl()?>/stock/search-procurements" >Back to Search Procurements  </a>  
                        
                            </div>
                            <div class="tools">
                                <a href="javascript:;" class="collapse">
                                </a>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <form id="rec" name="rec" action='' method="POST">
                                <div class="col-md-12">
                                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                                    <div class="portlet light bordered">
                                        <?php if (count($this->shipment_receive) > 0) { ?>
                                            <h3>Edit Receive</h3>
                                        <?php } else { ?>
                                            <h3>Receive</h3>
                                        <?php } ?>
                                        <div class="portlet-body">
                                            <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_PR">
                                                <thead>
                                                    <tr>
                                                        <th class="all">Product</th>
                                                        <th class="min-phone-l">Batch</th>
                                                        <th class="min-phone-l" style="display:none"></th>
                                                        <th class="min-phone-l" style="display:none"></th>
                                                        <th class="min-phone-l" style="display:none"></th>
                                                        <th class="min-phone-l" style="display:none"></th>
                                                        <th class="min-phone-l" style="display:none"></th>

                                                        <th class="min-tablet">Quantity</th>
                                                        <th class="none">Unit</th>
                                                        <th class="none">Manufacturer</th>


                                                    </tr>
                                                </thead>
                                                <tbody>

                                                    <?php
                                                    $i = 0;
                                                    foreach ($this->batch_list as $row) {
                                                        ?>
                                                        <tr>
                                                    <input type=hidden name="<?php echo $i; ?>-product_batch_id" id="<?php echo $i; ?>-product_batch_id" value="<?php echo $row['pk_id']; ?>">
                                                    <td><?php echo $row['item_name']; ?></td>
                                                    <td><?php echo $row['number']; ?></td>
                                                    
                                                    <?php
                                                    
                                                    
                                                    if (count($this->getShipmentsReceiveCount($row['pk_id'])) > 0) { ?>
                                                        <input type=hidden name="<?php echo $row['pk_id']; ?>-def_counter" id="<?php echo $row['pk_id']; ?>-def_counter" value="<?php echo count($this->getShipmentsReceiveCount($row['pk_id'])); ?>">
                                                    <?php } else { ?>
                                                        <input type=hidden name="<?php echo $row['pk_id']; ?>-def_counter" id="<?php echo $row['pk_id']; ?>-def_counter" value="3">
                                                    <?php } ?>
                                                    <td style="display:none" >
                                                        <?php echo $row['pk_id'] ?>


                                                    </td>
                                                    <td style="display:none" >
                                                        <?php echo $this->placments_location; ?>


                                                    </td>
                                                    <td style="display:none" >
                                                        <?php echo $row['item_category_id'] ?>


                                                    </td>
                                                    <td style="display:none" >
                                                        <?php echo $this->non_placments_location; ?>


                                                    </td>
                                                    <td style="display:none" >
                                                        <?php echo $this->item_vvm; ?>


                                                    </td>


                                                    <td align='right'><?php echo number_format($row['quantity']) ?></td>
                                                    <td><?php echo $row['item_unit_name']; ?></td>
                                                    <td><?php echo $row['stakeholder_name'] ?></td>



                                                    </tr>
                                                    <?php
                                                    $i++;
                                                }
                                                ?>

                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <!-- END EXAMPLE TABLE PORTLET-->
                                </div>


                                <div class="row">
                                    <div class="col-md-4">   


                                    </div>
                                    <div class="col-md-5">   
                                        <?php if (count($this->shipment_receive) > 0) { ?>

                                            <button type="submit" class="btn btn-primary" name="create_voucher" id="created_voucher" value="1">
                                                <?php echo $this->translate("Create Voucher"); ?>
                                            </button>                                    
                                        <?php } ?>
                                    </div>  
                                    <div class="col-md-3">   
                                        <?php if (count($this->shipment_receive) > 0) { ?>
                                            <button id="print_receive" type="button" class="btn btn-success">
                                                <?php echo $this->translate("Print"); ?>
                                            </button>
                                        <?php } ?>
                                        <button type="submit"  class="btn btn-primary">
                                            <?php if (count($this->shipment_receive) > 0) { ?>
                                                <input type="hidden" name="action" id="action" value="1">
                                                <?php echo $this->translate("Update"); ?>
                                            <?php } else { ?>
                                                <input type="hidden" name="action" id="action" value="1">
                                                <?php echo $this->translate("Save"); ?>
                                            <?php } ?>
                                        </button>  
                                        <input type="hidden" value="<?php echo $this->shipment_id ?>" name="shipment_id" id="shipment_id" />

                                        <input type="hidden" value="<?php echo $i; ?>" name="end_product" id="end_product" />

                                        
                                    </div>                                


                                </div>
                            </form>

                            <?php
                            $shipment_receive = $this->shipment_receive;
                            $i = 0;
                            if (count($shipment_receive) > 0) {
                                foreach ($shipment_receive as $res) {
                                    ?>
                                    <input type="hidden" name="<?php echo $res['counter']; ?>-<?php echo $res['shipment_product_batch_id'] ?>-quantity" id="<?php echo $res['counter']; ?>-<?php echo $res['shipment_product_batch_id'] ?>-quantity" value="<?php echo $res['quantity'] ?>">
                                    <input type="hidden" name="<?php echo $res['counter']; ?>-<?php echo $res['shipment_product_batch_id'] ?>-vvm_stage" id="<?php echo $res['counter']; ?>-<?php echo $res['shipment_product_batch_id'] ?>-vvm_stage" value="<?php echo $res['vvm_stage'] ?>">
                                    <input type="hidden" name="<?php echo $res['counter']; ?>-<?php echo $res['shipment_product_batch_id'] ?>-locations" id="<?php echo $res['counter']; ?>-<?php echo $res['shipment_product_batch_id'] ?>-locations" value="<?php echo $res['location_id'] ?>">
                                    <?php
                                    $i++;
                                }
                            }
                            ?>

                        </div>
                    </div>
                </div>
            </div>
            </form>
        <?php } ?>
    </div>
</div>
<script>
    $(function () {
        $("input[id$='-quantity']").focus(function (e) {
            alert($(this).val());
            var val = $(this).val();
            if (val == 0) {
                $(this).val('');
            }

        });
    });
</script>