<?php
/**
 *  phtml for Shipments Search
 */
?>
<style>
    .dashboard-stat .details .number{
        font-size: 20px !important;
    }
</style>
<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">
            <?php echo $this->translate("Shipments Search"); ?>
        </h3>
        <div class="row">
            <?php if (!empty($this->voucher)) { ?>
                <div class="col-md-12">
                    <div class="alert alert-info">
                        <button data-dismiss="alert" class="close" type="button">
                            ×
                        </button>
                        Stock has been received successfully. Your receive voucher number is <a onclick="window.open('<?php echo $this->baseUrl(); ?>/stock/print-receive?id=<?php echo $this->master_id; ?>', '_blank', 'scrollbars=1,width=860,height=595');" href="javascript:void(0);"><strong><?php echo $this->voucher; ?></strong></a>
                    </div>                                
                </div>
            <?php } ?>
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Filters"); ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse"></a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form name="search-pipeline" id="search-pipeline" method="post" action="">
                            <div class="row">
                                <div class="col-md-3">
                                    <!-- Group Receive No-->
                                    <div class="control-group">
                                        <label class="control-label" for="from_warehouse_id">
                                            <?php echo $this->translate("Source"); ?>
                                        </label>
                                        <div class="controls">
                                            <?php echo $this->form->from_warehouse_id; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="control-group">
                                        <label class="control-label" for="from_date">
                                            <?php echo $this->translate("From Date"); ?>
                                        </label>
                                        <div class="controls">
                                            <?php echo $this->form->from_date; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="control-group">
                                        <label class="control-label" for="to_date">
                                            <?php echo $this->translate("To Date"); ?>
                                        </label>
                                        <div class="controls">
                                            <?php echo $this->form->to_date; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="control-group">
                                        <label class="control-label" for="item_pack_size_id">
                                            <?php echo $this->translate("Products"); ?>
                                        </label>
                                        <div class="controls">
                                            <?php echo $this->form->item_pack_size_id; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="control-label" for="status">
                                        <?php echo $this->translate("Status"); ?>
                                    </label>
                                    <div class="controls">
                                        <?php echo $this->form->status; ?>
                                    </div>
                                </div>                                      
                                <div class="col-md-9 right">
                                    <label class="control-label">&nbsp;</label>  
                                    <div class="controls">
                                        <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit">
                                            <?php echo $this->translate("Search"); ?>
                                        </button>
                                        <button type="reset" class="btn btn-info" id="reset">
                                            <?php echo $this->translate("Reset"); ?>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <?php if ($this->arr_data && count($this->arr_data) > 0) { ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <?php echo $this->translate("Shipments List"); ?>
                            </div>
                            <div class="tools">
                                <a href="javascript:;" class="collapse">
                                </a>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php
                                    echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                                    ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-striped table-bordered table-condensed" id="sample_3">
                                        <!-- Table heading -->
                                        <thead>
                                            <tr>

                                                <th>
                                                    <?php echo $this->translate("Shipment Date"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("Shipment No."); ?>
                                                </th>

                                                <th>
                                                    <?php echo $this->translate("Ref. No."); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("Product"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("Funding Source"); ?>
                                                </th>

                                                <th>
                                                    <?php echo $this->translate("Purpose"); ?>
                                                </th>

                                                <th>
                                                    <?php echo $this->translate("Status"); ?>
                                                </th>
                                                <th>
                                                    <?php echo $this->translate("Action"); ?>
                                                </th>
                                            </tr>
                                        </thead>
                                        <!-- // Table heading END -->

                                        <!-- Table body -->
                                        <tbody>
                                            <!-- Table row -->
                                            <?php
                                            $i = 1;
                                            foreach ($this->arr_data as $row) {
                                                ?>
                                                <tr class="gradeX">
                                                    <td>
                                                        <?php echo App_Controller_Functions::dateToUserFormat($row['shipment_date']);  //$row->getExpectedArrivalDate()->format("d-m-Y"); ?>
                                                    </td>


                                                    <td>
                                                        <?php echo $row['transaction_number']; ?>

                                                    </td>
                                                    <td nowrap>
                                                        <?php echo $row['reference_number']; ?>
                                                    </td>

                                                    <td>
                                                        <?php echo $row['item_name']; ?>
                                                    </td>
                                                    <td>
                                                        <?php echo $row['warehouse_name']; ?>
                                                    </td>

                                                    <td>
                                                        <?php echo $row['activity']; ?>
                                                    </td>
                                                    <td>
                                                        <?php echo $row['status']; ?>
                                                    </td>
                                                    <td>
                                                        <div>

                                                            <?php if (empty($this->getShipmentsReceive($row['pk_id']))) { ?>
                                                                <a pkid="<?php echo $row['pk_id']; ?> " pkId2="<?php echo $row['shipment_date']; ?>" pkId3="(<?php echo $row['transaction_number']; ?>)"  class="btn btn-info btn-sm update-eta white"  data-toggle="modal" title="Update ETA" href="#modal-update-eta">
                                                                    ETA   </a> 
                                                                <a pkid="<?php echo $row['pk_id']; ?> " class="btn btn-info btn-sm update-eta white"  href="<?php echo $this->baseUrl(); ?>/stock/procurements-detail?id=<?php echo $row['pk_id']; ?>" >
                                                                    PSA   </a> 
                                                            <?php } else { ?>
                                                                <a pkid="<?php echo $row['pk_id']; ?> " pkId2="<?php echo $row['shipment_date']; ?>" pkId3="(<?php echo $row['transaction_number']; ?>)" class="btn btn-info btn-sm update-eta grey"  >
                                                                    ETA   </a>
                                                                <a pkid="<?php echo $row['pk_id']; ?> " class="btn btn-info btn-sm update-eta grey"  >
                                                                    PSA   </a> 
                                                            <?php } ?>
                                                            <?php if (!empty($this->getShipmentsDetails($row['pk_id']))) { ?>


                                                                <a pkid="<?php echo $row['pk_id']; ?> " class="btn btn-info btn-sm update-eta white"   href="<?php echo $this->baseUrl(); ?>/stock/procurements-receive?id=<?php echo $row['pk_id']; ?>" >
                                                                    RCV   </a>  
                                                            <?php } ?>



                                                        </div>

                                                    </td>
                                                </tr>
                                                <?php
                                                $i++;
                                            }
                                            ?>
                                            <!-- // Table row END -->
                                        </tbody>
                                        <!-- // Table body END -->
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php
        } else {
            ?>
            <div class="row">
                <div class="col-md-12">
                    <h4>No data found</h4>
                </div>
            </div>
        <?php } ?>
        <div id="future_arrival_details"></div>
    </div>
</div>


<div class="modal fade" id="modal-update-eta" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3  >Update ETA with Space Status</h3><h6 id="t_eta"></h6>
            </div>
            <div class="modal-body" id="modal-body-contents">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet box green">
                            <div class="portlet-title">
                                <div class="caption">
                                    <?php echo $this->translate("Update ETA"); ?>
                                </div>
                                <div class="tools">
                                    <a href="javascript:;" class="collapse">
                                    </a>
                                </div>
                            </div>

                            <div class="portlet-body" >
                                <form name="update-eta" id="update-eta" method="post" action="<?php echo $this->baseUrl(); ?>/stock/update-eta">
                                    <div class="row">

                                        <div class="col-md-6">
                                            <div class="control-group">
                                                <label class="control-label" for="to_date">
                                                    <?php echo $this->translate("Select ETA"); ?>
                                                </label>
                                                <div class="controls">
                                                    <?php echo $this->form->eta; ?>
                                                    <input type="hidden" name="shipment_id" id="shipment_id" value="">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <label class="control-label">&nbsp;</label>  
                                            <div class="controls">
                                                <button data-loading-text="Please Wait ..." class="btn btn-primary" id="btn-loading" type="submit">
                                                    <?php echo $this->translate("Update"); ?>
                                                </button>

                                            </div>
                                        </div>

                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="space-estimate">
                    <div style="text-align: center; " ><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>    
                </div>

            </div>
        </div>
    </div>
</div>

<div style="text-align: center;" id="loader" name="loader"><img src='<?php echo $this->baseUrl(); ?>/images/loader.gif'/></div>