    <table class="table table-condensed table-hover" cellpadding="4" cellspacing="0" border="1">
        <tr>
            <th nowrap>S.No</th>
            <th nowrap>Username</th>
            <th nowrap>Designation</th>
            <th nowrap>Department</th>   
            <th nowrap>Province</th> 
            <th nowrap>District</th> 
        </tr>
        <?php
        $count = 1;
        foreach ($this->result as $row) {
            ?>
            <tr>
                <td><?php echo $count; ?></td>
                <td><?php echo $row['user_name']; ?></td>
                <td><?php echo $row['designation']; ?></td>
                <td><?php echo $row['department']; ?></td>
                <td><?php echo $row['Province']; ?></td>
                <td><?php echo $row['District']; ?></td>
            </tr>
            <?php
            $count++;
        }
        ?>
    </table>