<?php
/**
 *  phtml for Register User
 */
?>
<!-- BEGIN CONTAINER -->
<style>
    .form-group{
        padding-top:  5px;
    }
    textarea {
        resize: none;
    }
    .col-md-offset-4_5 {
        margin-left: 29.175%;
    }
    .col-sm-offset-4_5 {
        margin-left: 29.175%;
    }
    .form-control, .thumbnail {
        border-radius: 2px;
    }
    .btn-danger {
        background-color: #B73333;
    }

    /* File Upload */
    .fake-shadow {
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
    }
    .fileUpload {
        position: relative;
        overflow: hidden;
    }
    .fileUpload #logo-id {
        position: absolute;
        top: 0;
        right: 0;
        margin: 0;
        padding: 0;
        font-size: 33px;
        cursor: pointer;
        opacity: 0;
        filter: alpha(opacity=0);
    }
    .img-preview {
        max-width: 100%;
    }
</style>
<div class="page-container">
    <!-- BEGIN CONTENT -->
    <div class=" page-content-wrapper">
        <div class="page-content landing-content">
            <br/>

            <div class="col-md-4 col-md-offset-4">
                <?php if ($this->saved == true) { ?>
                    <div class="alert alert-info" id="saved">
                        <button data-dismiss="alert" class="close" type="button">
                            ×
                        </button>
                        Your request is submitted successfully. <br>

                    </div>
                <?php } ?>
            </div>



            <div class="col-md-6 col-md-offset-3 col-sm-offset-0">

                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-user"></i>Register
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form name="register" id="register" method="post" action="">
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="form-group">
                                        <label for="name" class="col-md-3 control-label">
                                            <?php echo $this->translate("Name"); ?><span class="red">*</span>
                                        </label>
                                        <div class="col-md-9">
                                            <?php echo $this->form->name; ?>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-group">
                                        <label for="organization" class="col-md-3 control-label">
                                            <?php echo $this->translate("Organization"); ?><span class="red">*</span>
                                        </label>
                                        <div class="col-md-9">
                                            <?php echo $this->form->organization; ?>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-group" style="display: none" id="other">
                                        <label for="e_mail" class="col-md-3 control-label">
                                            <?php echo $this->translate("Other"); ?><span class="red">*</span>
                                        </label>
                                        <div class="col-md-9">
                                            <?php echo $this->form->other; ?>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-group">
                                        <label for="e_mail" class="col-md-3 control-label">
                                            <?php echo $this->translate("Designation"); ?><span class="red">*</span>
                                        </label>
                                        <div class="col-md-9">
                                            <?php echo $this->form->designation; ?>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-group">
                                        <label for="e_mail" class="col-md-3 control-label">
                                            <?php echo $this->translate("Email"); ?><span class="red">*</span>
                                        </label>
                                        <div class="col-md-9">
                                            <?php echo $this->form->e_mail; ?>
                                        </div>
                                    </div>
                                    <br>

                                    <div class="form-group">
                                        <label for="e_mail" class="col-md-3 control-label">
                                            <?php echo $this->translate("Contact No"); ?><span class="red">*</span>
                                        </label>
                                        <div class="col-md-9">
                                            <?php echo $this->form->contact; ?>
                                        </div>
                                    </div>
                                    <br>

                                </div>
                                <div class="col-md-3">


                                    <div class="form-group">
                                        <div class="main-img-preview">
                                            <img class="thumbnail img-preview" src="<?php echo $this->baseUrl(); ?>/images/no-image.png" title="Preview Logo">
                                        </div>
                                        <div class="input-group">
                                            <input id="fakeUploadLogo" class="form-control fake-shadow" placeholder="Choose File" disabled="disabled">
                                            <div class="input-group-btn">
                                                <div class="fileUpload btn btn-danger fake-shadow">
                                                    <span><i class="glyphicon glyphicon-upload"></i>Photo</span>
                                                    <input id="logo-id" name="photo" type="file" class="attachment_upload">
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                </div>

                            </div>

                            <div class="form-group">
                                <label for="country" class="col-md-2 control-label" style="margin-right:13px">
                                    <?php echo $this->translate("Level"); ?>
                                </label>
                                <div class="col-md-9">
                                    <?php echo $this->form->level; ?>

                                </div>
                            </div>
                            <br>
                            <div class="form-group">
                                <label for="country" class="col-md-2 control-label" style="margin-right:13px">
                                    <?php echo $this->translate("Request for"); ?>
                                </label>
                                <div class="col-md-9">
                                    <div class="mt-checkbox-inline">
                                        <label class="mt-checkbox">
                                            <input id="inlineCheckbox21" value="option1" type="checkbox"> Inventory
                                            <span></span>
                                        </label>
                                        <label class="mt-checkbox">
                                            <input id="inlineCheckbox22" value="option2" type="checkbox"> Consumption
                                            <span></span>
                                        </label>
                                        <label class="mt-checkbox">
                                            <input id="inlineCheckbox22" value="option2" type="checkbox"> Cold Chain
                                            <span></span>
                                        </label>
                                        <label class="mt-checkbox">
                                            <input id="inlineCheckbox22" value="option2" type="checkbox"> Analytics
                                            <span></span>
                                        </label>

                                    </div>

                                </div>
                            </div>
                            <br>
                            <div class="form-group">
                                <label for="address" class="col-md-2 control-label" style="margin-right:13px">
                                    <?php echo $this->translate("Address"); ?>
                                </label>
                                <div class="col-md-9">
                                    <?php echo $this->form->address; ?>
                                </div>
                            </div>
                            <br>
                            <div class="form-group">
                                <label for="address" class="col-md-2 control-label" style="margin-right:13px">
                                    <?php echo $this->translate("Province"); ?><span class="red">*</span>
                                </label>
                                <div class="col-md-9">
                                    <?php echo $this->form->province; ?>
                                </div>
                            </div>
                            <br>
                            <div class="form-group">
                                <label for="address" class="col-md-2 control-label" style="margin-right:13px">
                                    <?php echo $this->translate("District"); ?><span class="red">*</span>
                                </label>
                                <div class="col-md-9">
                                    <?php echo $this->form->district; ?>
                                </div>
                            </div>
                            <br>
                            <div class="form-group">
                                <label for="address" class="col-md-2 control-label" style="margin-right:13px">
                                    <?php echo $this->translate("Comments"); ?>
                                </label>
                                <div class="col-md-9">
                                    <textarea name="comments" id="comments" class="form-control"></textarea>
                                </div>
                            </div>
                            <br>

                            <div class="form-group">
                                <label for="captcha" class="col-md-2 control-label" style="margin-right:13px">
                                    <?php echo $this->translate("Please enter the code"); ?><span class="red">*</span>
                                </label>
                                <div class="col-md-9">
                                    <?php echo $this->form->captcha; ?>
                                </div>
                            </div>
                            <br>

                            <div class="form-group">
                                <div class="pull-right" style="padding-top: 5px">
                                    <div class="col-md-6">
                                        <button type="reset" id="reset" value="Reset" class="btn btn-info">
                                            <?php echo $this->translate("Reset"); ?>
                                        </button>
                                    </div>
                                    <div class="col-md-6">
                                        <button name="send_contact" id="send_contact" type="submit" class="form-control btn btn-success green">Register</button>
                                    </div>
                                </div>
                            </div>


                            <br>

                        </form>

                        <div class="clearfix margin-bottom-20">
                        </div>

                    </div>
                </div>

            </div>

        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        var brand = document.getElementById('logo-id');
        brand.className = 'attachment_upload';
        brand.onchange = function () {
            document.getElementById('fakeUploadLogo').value = this.value.substring(12);
        };

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('.img-preview').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        $("#logo-id").change(function () {
            readURL(this);
        });
    });
</script>