<?php
/**
*  phtml for FAQs
*/
?>
<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN CONTENT -->
    <div class=" page-content-wrapper">
        <div class="page-content landing-content">
        <br/>
            <div class="col-md-12 "> 
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-folder"></i>Uptime Robot
                        </div>
                    </div>
                    <div class="portlet-body">
                        <iframe style="border:none;" width="100%" height="1000" src="https://stats.uptimerobot.com/MZzZpCVXk/779326963"></iframe>
                    </div>
                </div>
            </div>
        </div></div>
