<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">

            <div class="col-md-12">
                <!-- BEGIN ALERTS PORTLET-->
                <div class="portlet yellow box">
                    <div class="portlet-title">
                        <div class="caption"><i class="icon-cogs"></i>Notes</div>
                        <div class="tools">
                         <a href="javascript:;" class="collapse"></a>

                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="note note-success">
                            <h2 class="block">Coming Soon!</h2>
                        </div>
                    </div>
                </div>
                <!-- END ALERTS PORTLET-->
            </div>
        </div>
    </div>
</div>