<?php
/**
 *  phtml for Ajax Edit Routine
 */
?>
<div class="row">
    <?php echo $this->routineEditCombo($this->warehouse_id, $this->role_id); ?>  
</div>
<div class="row">
    <div class="col-md-4">
        <div class="form-group ">
            <label class="control-label" ><?php echo $this->translate("Default Store"); ?></label>
            <?php echo $this->form->default_warehouse_update; ?>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group ">
            <label class="control-label" ><?php echo $this->translate("User Name"); ?></label>
            <?php echo $this->form->user_name_update; ?>
        </div>
    </div>
</div>
<?php echo $this->form->user_id; ?>
<?php echo $this->form->office_id_edit; ?>
<?php echo $this->form->province_id_edit; ?>
<?php echo $this->form->district_id_edit; ?> 
<?php echo $this->form->tehsil_id_edit; ?> 
<?php echo $this->form->parent_id_edit; ?>
<?php echo $this->form->warehouse_users_id_edit; ?>
<?php echo $this->form->default_warehouse_update_hidden; ?>
<?php echo $this->form->user_name_update_hidden; ?>
<input type="hidden" name="hdn_warehouse_id" id="hdn_warehouse_id" value="<?php echo $this->warehouse_id; ?>">
<input type="hidden" name="hdn_role_id" id="hdn_role_id" value="<?php echo $this->role_id; ?>">

