<?php
/**
 *  phtml for Ajax Edit Policy
 */
?>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-6">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("Login ID"); ?></label>
                <div class="controls">
                    <?php echo $this->form->login_id_update; ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("Username"); ?></label>
                <div class="controls">
                    <?php echo $this->form->user_name_update; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-6">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("Email"); ?></label><span class="red">*</span>
                <div class="controls">
                    <?php echo $this->form->email_update; ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("Phone"); ?></label><span class="red">*</span>
                <div class="controls">
                    <?php echo $this->form->phone_update; ?>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <?php echo $this->usersEditCombo($this->combos_1, $this->role_id); ?>
    </div>
</div>
<div class="row"> 
    <div class="col-md-12">
        <div class="col-md-6">
            <div class="control-group ">
                <label class="control-label" ><?php echo $this->translate("Role"); ?></label><span class="red">*</span>
                <div class="controls">
                    <?php echo $this->form->role_policy_update; ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group ">
                <label class="control-label" ><?php echo $this->translate("Default Store"); ?></label>
                <?php echo $this->form->default_warehouse_update; ?>
            </div>
        </div>
    </div>
</div>

<?php echo $this->form->user_id; ?>
<?php echo $this->form->office_id_edit; ?>
<?php echo $this->form->province_id_edit; ?>
<?php echo $this->form->district_id_edit; ?> 
<?php echo $this->form->tehsil_id_edit; ?> 
<?php echo $this->form->parent_id_edit; ?>
<?php echo $this->form->warehouse_users_id_edit; ?>
<?php echo $this->form->user_name_update_hidden; ?>
<?php echo $this->form->default_warehouse_update_hidden; ?>
<input type="hidden" name="hdn_warehouse_id" id="hdn_warehouse_id" value="<?php echo $this->warehouse_id; ?>">
<input type="hidden" name="hdn_role_id" id="hdn_role_id" value="<?php echo $this->role_id; ?>">
