<table class="table table-striped table-bordered table-hover dataTable no-footer" id="sample_2">
    <!-- Table heading -->
    <?php
    $fields = array(
        's_no' => 'S.No',
        'user_name' => 'UserName',
        'Uc' => 'UC',
        'district' => 'District',
        'province' => 'Province'
    );
    $this->tableHeading($this->order, $this->sort, $fields);
    ?>
    <!-- // Table heading END -->
    <!-- Table body -->

    <!-- // Table body END -->
    <tbody>
        <?php
        $m_res = array();
        $i = 1;
        if ($this->paginator && count($this->paginator) > 0) :
            foreach ($this->paginator as $row):
                ?>
                  <tr class="<?php
                if ($row['loginId'] == $this->locations_add && $this->action == 1) {
                    echo 'danger';
                } else if ($row['loginId'] == $this->locations_edit && $this->action == 2) {
                    echo 'danger';
                }
                ?>">
                    <td class="center" width="25"> <?php
                        if ($row['loginId'] == $this->locations_add && $this->action == '1') {
                            echo "<span class='label label-sm label-info'>New</span>";
                        } else if ($row['loginId'] == $this->locations_edit && $this->action == '2') {
                            echo "<span class='label label-sm label-info'>Edited</span>";
                        }
                        ?> <?php echo $i; ?></td>
                    <td><?php echo $row['loginId']; ?></td>
                    <td><?php echo $row['Parent']; ?></td>
                    <td><?php echo $row['districtName']; ?></td>
                    <td><?php echo $row['ProvinceName']; ?></td>
                    <td><a itemid="<?php echo $row['pkId']; ?>" class="update-stores btn btn-xs green" data-toggle="modal" href="#modal-update-stores"><i class="fa fa-edit"></i><?php echo $this->translate("Edit") ?></a>
                        <?php if ($row['role'] == 6 || $row['role'] == 21) { ?>
                            <a itemid="<?php echo $row['pkId']; ?>" class="update-role btn btn-xs green" data-toggle="modal" href="#modal-update-role"><?php echo $this->translate("Role") ?></a>
                        <?php } ?>
                    </td> 
                    <?php //if ($this->userDelete($row['pkId'])) { ?>
                    <?php //} else { ?>
                     <!-- <a data-toggle="notyfy" data-bind="<?php echo $row['pkId']; ?>" data-type="confirm" data-layout="top" class="btn-link btn-danger btn-mini"><?php echo $this->translate("Delete"); ?>
                         </a> -!>
                    <?php // } ?>                                                     
                    <!-- // Table row END --><?php
                    $i++;
                endforeach;
            endif;
            ?>
    </tbody>
</table>