<?php
/**
*  phtml for Get Default Warehouse by Level
*/
?>
<?php
if ($this->data != false) {
    ?>
    <option value=""><?php echo $this->translate("Select"); ?></option>
    <?php
    foreach ($this->data as $row) {
        ?>
        <option value="<?php echo $row['pk_id']; ?>"><?php echo $row['role_name']; ?></option>
        <?php
    }
} else {
    ?>
    <option value=""><?php echo $this->translate("Select"); ?></option>
    <?php
}
?>