<?php
/**
 *  phtml for Index
 */
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            District info cards
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <iframe width="100%" height="700" src="https://app.powerbi.com/view?r=eyJrIjoiOWYwNWY4ZTItMjJjNy00ZWQ4LWFlNzEtYTBjMDk1NTk0MjM0IiwidCI6IjdjMWYyNGE2LTdkMzktNDUyYy04MjM3LTA3MjZlM2IxOWE3MyIsImMiOjF9" frameborder="0" allowFullScreen="true"></iframe>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>