<?php
/**
 *  phtml for Index
 */
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <h3 class="col-md-6">
                Statistics
            </h3>
            <div class="col-md-6">

            </div>                
        </div>
        <!-- END PAGE HEADER-->
        <div class="row">
            <div class="col-md-12">
                <div class="widget widget-tabs">
                    <div class="widget-head dashboard-widget">
                        <ul>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/iadmin/index/aw-stats">
                                    <div class="dashboard-stat_custom">
                                        <div class="visual" style="width: auto;">
                                            <i style="line-height: 0px; margin-left: 0px; font-size: 35px;" class="fa fa-bar-chart-o"></i>
                                        </div>
                                        <div class="details" style="float: left;">
                                            <div class="dashboard-title-1">AW</div>
                                            <div class="dashboard-title-2">Stats</div>
                                        </div>
                                    </div>
                                </a>
                            </li>  
                            <li class="active">
                                <a href="#">
                                    <div class="dashboard-stat_custom">
                                        <div class="visual" style="width: auto;">
                                            <i style="line-height: 0px; margin-left: 0px; font-size: 35px;" class="fa fa-bar-chart-o"></i>
                                        </div>
                                        <div class="details" style="float: left;">
                                            <div class="dashboard-title-1">Uptime</div>
                                            <div class="dashboard-title-2">Stats</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                             <li>
                                <a target="_blank" href="<?php echo $this->baseUrl(); ?>/click-paths/user-path">
                                    <div class="dashboard-stat_custom">
                                        <div class="visual" style="width: auto;">
                                            <i style="line-height: 0px; margin-left: 0px; font-size: 35px;" class="fa fa-bar-chart-o"></i>
                                        </div>
                                        <div class="details" style="float: left;">
                                            <div class="dashboard-title-1">Click Path</div>
                                            <div class="dashboard-title-2">Stats</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a  href="<?php echo $this->baseUrl(); ?>/iadmin/index/user-stats">
                                    <div class="dashboard-stat_custom">
                                        <div class="visual" style="width: auto;">
                                            <i style="line-height: 0px; margin-left: 0px; font-size: 35px;" class="fa fa-bar-chart-o"></i>
                                        </div>
                                        <div class="details" style="float: left;">
                                            <div class="dashboard-title-1">User</div>
                                            <div class="dashboard-title-2">Stats</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="widget-body">
                        <div class="tab-content">
                            <div class="tab-pane active">
                                <div class = "row">
                                    <div class="col-md-12">
                                        <iframe style="border:none;" width="100%" height="1000" src="https://stats.uptimerobot.com/MZzZpCVXk/779326963"></iframe>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
                <!-- // Tabs END -->                
            </div>
        </div>
    </div>
</div>