<?php
/**
 *  phtml for Index
 */
?>
<style>
    table#tbl tr td{font-size:11px;padding:5px; color: #000;}

</style>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <h3 class="col-md-6">
                Statistics
            </h3>
            <div class="col-md-6">

            </div>                
        </div>
        <!-- END PAGE HEADER-->
        <div class="row">
            <div class="col-md-12">
                <div class="widget widget-tabs">
                    <div class="widget-head dashboard-widget">
                        <ul>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/iadmin/index/aw-stats">
                                    <div class="dashboard-stat_custom">
                                        <div class="visual" style="width: auto;">
                                            <i style="line-height: 0px; margin-left: 0px; font-size: 35px;" class="fa fa-bar-chart-o"></i>
                                        </div>
                                        <div class="details" style="float: left;">
                                            <div class="dashboard-title-1">AW</div>
                                            <div class="dashboard-title-2">Stats</div>
                                        </div>
                                    </div>
                                </a>
                            </li>  
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/iadmin/index/uptime">
                                    <div class="dashboard-stat_custom">
                                        <div class="visual" style="width: auto;">
                                            <i style="line-height: 0px; margin-left: 0px; font-size: 35px;" class="fa fa-bar-chart-o"></i>
                                        </div>
                                        <div class="details" style="float: left;">
                                            <div class="dashboard-title-1">Uptime</div>
                                            <div class="dashboard-title-2">Stats</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a target="_blank" href="<?php echo $this->baseUrl(); ?>/click-paths/user-path">
                                    <div class="dashboard-stat_custom">
                                        <div class="visual" style="width: auto;">
                                            <i style="line-height: 0px; margin-left: 0px; font-size: 35px;" class="fa fa-bar-chart-o"></i>
                                        </div>
                                        <div class="details" style="float: left;">
                                            <div class="dashboard-title-1">Click Path</div>
                                            <div class="dashboard-title-2">Stats</div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="active">
                                <a href="<?php echo $this->baseUrl(); ?>/iadmin/index/user-stats">
                                    <div class="dashboard-stat_custom">
                                        <div class="visual" style="width: auto;">
                                            <i style="line-height: 0px; margin-left: 0px; font-size: 35px;" class="fa fa-bar-chart-o"></i>
                                        </div>
                                        <div class="details" style="float: left;">
                                            <div class="dashboard-title-1">User</div>
                                            <div class="dashboard-title-2">Stats</div>
                                        </div>
                                    </div>
                                </a>
                            </li>

                        </ul>
                    </div>
                    <div class="widget-body">
                        <div class="tab-content">

                            <div class="tab-pane active">

                                <div class = "row">
                                    <div class="col-md-12">
                                        <div class="portlet">
                                            <div class="portlet-title">
                                                <div class="caption"><i class="fa fa-bell"></i>Development Partners Use</div>
                                                <div class="tools">
                                                    <a href="javascript:;" class="collapse"></a>

                                                </div>
                                            </div>
                                            <div class="portlet-body" style="display: block;">

                                                <table class="table table-striped table-bordered table-advance table-hover" style="font-size: 11px;" id="tbl">
                                                    <thead>
                                                        <tr>
                                                            <th class="center" style="width:7%;"><i class="fa fa-long-arrow-down"></i>Months</th>
                                                            <?php
                                                            foreach ($this->role_partners as $row) {
                                                                ?>
                                                                <th class="center"><?php echo $row['role_name'] ?></th>
                                                            <?php } ?>



                                                        </tr>
                                                    </thead>

                                                    <tbody>


                                                        <?php
                                                        if (count($this->data) > 0) {
                                                            $i = 1;
                                                            $q = 1;
                                                            ?>
                                                            <?php
                                                            $year = date("Y");
                                                            $month = date("M");
                                                            $end_date1 = $year . '-' . ($month) . '-01';
                                                            $end_date = date('Y-m-d', strtotime("-1 days", strtotime("+1 month", strtotime($end_date1))));
                                                            $start_date = date('Y-m-d', strtotime("-5 month", strtotime($end_date1)));

                                                            $begin = new DateTime($start_date);
                                                            $end = new DateTime($end_date);
                                                            $interval = DateInterval::createFromDateString('1 month');
                                                            $period = new DatePeriod($begin, $interval, $end);
                                                            ?>
                                                            <?php foreach ($period as $date) { ?>
                                                                <tr>

                                                                    <td class="highlight"><?php echo $date->format("M-y"); ?></td>
                                                                    <?php
                                                                    foreach ($this->role_partners as $row) {

                                                                        if (!empty($this->userStats()->userStats1($row['role_name'], $date->format("Y-m")))) {
                                                                            foreach ($this->userStats()->userStats1($row['role_name'], $date->format("Y-m")) as $row) {
                                                                                ?>

                                                                                <td class="right"><?php echo $row['page_count']; ?></td>


                                                                                <?php
                                                                            }
                                                                        } else {
                                                                            ?>

                                                                            <td class="right">0</td> 

                                                                            <?php
                                                                        }
                                                                    }
                                                                }
                                                                ?>
                                                            </tr>

                                                            <?php
                                                            $i++;
                                                            ?>
                                                            <?php
                                                        } else {
                                                            ?>
                                                            <tr>
                                                                <td colspan="12" class="center">No data found</td>


                                                            </tr> 
                                                        <?php } ?>
                                                    </tbody>

                                                </table>

                                            </div>
                                        </div>
                                        <div class="portlet">
                                            <div class="portlet-title">
                                                <div class="caption"><i class="fa fa-bell"></i>National Level Use</div>
                                                <div class="tools">
                                                    <a href="javascript:;" class="collapse"></a>

                                                </div>
                                            </div>
                                            <div class="portlet-body" style="display: block;">



                                                <table class="table table-striped table-bordered table-advance table-hover" style="font-size: 11px;" id="tbl">

                                                    <thead>
                                                        <tr>
                                                            <th class="center" style="width:7%;"><i class="fa fa-long-arrow-down"></i>Months</th>

                                                            <?php
                                                            foreach ($this->role_national as $row) {
                                                                ?>
                                                                <th class="center"><?php
                                                                    if ($row['role_name'] == 'nAsgharEPI') {
                                                                        echo "Assitant Director EPI";
                                                                    } else {
                                                                        echo $row['role_name'];
                                                                    }
                                                                    ?></th>
                                                            <?php } ?>



                                                        </tr>
                                                    </thead>

                                                    <tbody>


                                                        <?php
                                                        if (count($this->data) > 0) {
                                                            $i = 1;
                                                            $q = 1;
                                                            ?>
                                                            <?php
                                                            $year = date("Y");
                                                            $month = date("M");
                                                            $end_date1 = $year . '-' . ($month) . '-01';
                                                            $end_date = date('Y-m-d', strtotime("-1 days", strtotime("+1 month", strtotime($end_date1))));
                                                            $start_date = date('Y-m-d', strtotime("-5 month", strtotime($end_date1)));

                                                            $begin = new DateTime($start_date);
                                                            $end = new DateTime($end_date);
                                                            $interval = DateInterval::createFromDateString('1 month');
                                                            $period = new DatePeriod($begin, $interval, $end);
                                                            ?>
                                                            <?php foreach ($period as $date) { ?>
                                                                <tr>

                                                                    <td class="center"><?php echo $date->format("M-y"); ?></td>
                                                                    <?php
                                                                    foreach ($this->role_national as $row) {

                                                                        if (!empty($this->userStats()->userStats1($row['role_name'], $date->format("Y-m")))) {
                                                                            foreach ($this->userStats()->userStats1($row['role_name'], $date->format("Y-m")) as $row) {
                                                                                ?>

                                                                                <td class="right"><?php echo $row['page_count']; ?></td>


                                                                                <?php
                                                                            }
                                                                        } else {
                                                                            ?>

                                                                            <td class="right">0</td> 

                                                                            <?php
                                                                        }
                                                                    }
                                                                }
                                                                ?>
                                                            </tr>
                                                            <?php
                                                            $i++;
                                                            ?>
                                                            <?php
                                                        } else {
                                                            ?>
                                                            <tr>
                                                                <td colspan="12" class="center">No data found</td>


                                                            </tr> 
                                                        <?php } ?>
                                                    </tbody>

                                                </table>
                                            </div>
                                        </div>
                                        <div class="portlet">
                                            <div class="portlet-title">
                                                <div class="caption"><i class="fa fa-bell"></i>Provincial Level Use</div>
                                                <div class="tools">
                                                    <a href="javascript:;" class="collapse"></a>

                                                </div>
                                            </div>
                                            <div class="portlet-body" style="display: block;">

                                                <table class="table table-striped table-bordered table-advance table-hover" style="font-size: 11px;" id="tbl">


                                                    <thead>
                                                        <tr>
                                                            <th class="center" style="width:7%;"><i class="fa fa-long-arrow-down"></i>Months</th>

                                                            <?php
                                                            foreach ($this->role_provincial as $row) {
                                                                ?>
                                                                <th class="center"><?php
                                                                    echo $row['role_name'];
                                                                    ?></th>
                                                            <?php } ?>



                                                        </tr>
                                                    </thead>

                                                    <tbody>


                                                        <?php
                                                        if (count($this->data) > 0) {
                                                            $i = 1;
                                                            $q = 1;
                                                            ?>
                                                            <?php
                                                            $year = date("Y");
                                                            $month = date("M");
                                                            $end_date1 = $year . '-' . ($month) . '-01';
                                                            $end_date = date('Y-m-d', strtotime("-1 days", strtotime("+1 month", strtotime($end_date1))));
                                                            $start_date = date('Y-m-d', strtotime("-5 month", strtotime($end_date1)));

                                                            $begin = new DateTime($start_date);
                                                            $end = new DateTime($end_date);
                                                            $interval = DateInterval::createFromDateString('1 month');
                                                            $period = new DatePeriod($begin, $interval, $end);
                                                            ?>
                                                            <?php foreach ($period as $date) { ?>
                                                                <tr>

                                                                    <td class="center"><?php echo $date->format("M-y"); ?></td>
                                                                    <?php
                                                                    foreach ($this->role_provincial as $row) {

                                                                        if (!empty($this->userStats()->userStatsProvince($row['role_id'], $date->format("Y-m")))) {
                                                                            foreach ($this->userStats()->userStatsProvince($row['role_id'], $date->format("Y-m")) as $row) {
                                                                                ?>

                                                                                <td class="right"><?php echo $row['page_count']; ?></td>


                                                                                <?php
                                                                            }
                                                                        } else {
                                                                            ?>

                                                                            <td class="right">0</td> 

                                                                            <?php
                                                                        }
                                                                    }
                                                                }
                                                                ?>
                                                            </tr>
                                                            <?php
                                                            $i++;
                                                            ?>
                                                            <?php
                                                        } else {
                                                            ?>
                                                            <tr>
                                                                <td colspan="12" class="center">No data found</td>


                                                            </tr> 
                                                        <?php } ?>
                                                    </tbody>

                                                </table>

                                            </div>
                                        </div>
                                        <div class="portlet">
                                            <div class="portlet-title">
                                                <div class="caption"><i class="fa fa-bell"></i>Division,District Level Use</div>
                                                <div class="tools">
                                                    <a href="javascript:;" class="collapse"></a>

                                                </div>
                                            </div>
                                            <div class="portlet-body" style="display: block;">

                                                <table class="table table-striped table-bordered table-advance table-hover" style="font-size: 11px;" id="tbl">


                                                    <thead>
                                                        <tr>
                                                            <th class="center" style="width:7%;"><i class="fa fa-long-arrow-down"></i>Months</th>

                                                            <?php
                                                            foreach ($this->role_district as $row) {
                                                                ?>
                                                                <th class="center"><?php
                                                                    echo $row['role_name'];
                                                                    ?></th>
                                                            <?php } ?>



                                                        </tr>
                                                    </thead>

                                                    <tbody>


                                                        <?php
                                                        if (count($this->data) > 0) {
                                                            $i = 1;
                                                            $q = 1;
                                                            ?>
                                                            <?php
                                                            $year = date("Y");
                                                            $month = date("M");
                                                            $end_date1 = $year . '-' . ($month) . '-01';
                                                            $end_date = date('Y-m-d', strtotime("-1 days", strtotime("+1 month", strtotime($end_date1))));
                                                            $start_date = date('Y-m-d', strtotime("-5 month", strtotime($end_date1)));

                                                            $begin = new DateTime($start_date);
                                                            $end = new DateTime($end_date);
                                                            $interval = DateInterval::createFromDateString('1 month');
                                                            $period = new DatePeriod($begin, $interval, $end);
                                                            ?>
                                                            <?php foreach ($period as $date) { ?>
                                                                <tr>

                                                                    <td class="center"><?php echo $date->format("M-y"); ?></td>
                                                                    <?php
                                                                    foreach ($this->role_district as $row) {

                                                                        if (!empty($this->userStats()->userStatsDistricts($row['role_id'], $date->format("Y-m")))) {
                                                                            foreach ($this->userStats()->userStatsDistricts($row['role_id'], $date->format("Y-m")) as $row) {
                                                                                ?>

                                                                                <td class="right"><?php echo $row['page_count']; ?></td>


                                                                                <?php
                                                                            }
                                                                        } else {
                                                                            ?>

                                                                            <td class="right">0</td> 

                                                                            <?php
                                                                        }
                                                                    }
                                                                }
                                                                ?>
                                                            </tr>
                                                            <?php
                                                            $i++;
                                                            ?>
                                                            <?php
                                                        } else {
                                                            ?>
                                                            <tr>
                                                                <td colspan="12" class="center">No data found</td>


                                                            </tr> 
                                                        <?php } ?>
                                                    </tbody>

                                                </table>
                                            </div>
<div class="col-md-12">

                <span class="red">*&nbsp;&nbsp;&nbsp;&nbsp;</span> - Page Counts <br>
              
            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
                <!-- // Tabs END -->                
            </div>
        </div>
    </div>
</div>
