<?php
/**
 *  phtml for BCG Coverage Detail
 */
?>
<?php
$from_sel_month = $this->from_month_sel;
$from_sel_year = $this->from_year_sel;
$year = $this->year_sel;
$month = $this->month_sel;
$sel_prov = $this->prov_sel;
$sel_dist = $this->district_id;
$sel_tehsil = $this->tehsil;
$wh_type = $this->wh_type;
$province = $this->prov_sel;
$report_type = $this->report_type;

// Headers of the Grid
if ($wh_type == 2 && $report_type == 1) {
    $header = 'Sr.No.,District, Target';
    $header1 = '#rspan,#rspan,#rspan';
    $cspan = '#cspan,#cspan,#cspan';
    $width = '50,150,80';
    $ro = 'ro,ro,ro';
} else if ($wh_type == 2 && $report_type == 2) {
    $header = 'Sr.No.,District,Tehsil/Taluka,UC, Target';
    $header1 = '#rspan,#rspan,#rspan,#rspan,#rspan';
    $cspan = '#cspan,#cspan,#cspan,#cspan,#cspan';
    $width = '50,150,150,150,80';
    $ro = 'ro,ro,ro,ro,ro';
} else if ($wh_type == 4 && $report_type == 1) {
    $header = 'Sr.No.,Tehsil/Taluka,Target';
    $header1 = '#rspan,#rspan,#rspan';
    $cspan = '#cspan,#cspan,#cspan';
    $width = '50,150,80';
    $ro = 'ro,ro,ro';
} else if ($wh_type == 4 && $report_type == 2) {
    $header = 'Sr.No.,Tehsil/Taluka,UC, Target';
    $header1 = '#rspan,#rspan,#rspan,#rspan';
    $cspan = '#cspan,#cspan,#cspan,#cspan';
    $width = '50,150,150,80';
    $ro = 'ro,ro,ro,ro';
}

$cspan .= ',#cspan,#cspan,#cspan,#cspan,#cspan,#cspan,#cspan,#cspan';
$header .= ",<div style='text-align:center;'>Fixed</div>,#cspan";
$header .= ",<div style='text-align:center;'>Referral</div>,#cspan";
$header .= ",<div style='text-align:center;'>Outreach</div>,#cspan";
$header .= ",<div style='text-align:center;'>Total</div>";
$header .= ",<div style='text-align:center;'>Coverage(%)</div>";
$width .= ',*,*,*,*,*,*,*,100';

$header1 .= ',<span>M</span>, <span>F</span>';
$header1 .= ',<span>M</span>, <span>F</span>';
$header1 .= ',<span>M</span>, <span>F</span>';
$header1 .= ',<span>BCG</span>';
$header1 .= ',<span>BCG</span>';
$ro .= ',ro,ro,ro,ro,ro,ro,ro,ro';



$xml_store = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_store .= "<rows>";

$sum_arr = array();

$query = $this->reports()->bcgCoverageReport($wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type);
$j = 1;


foreach ($query as $row) {

    $location_id = $row['location_id'];
    $data_arr[$location_id][] = $j;
    if ($wh_type == 2 && $report_type == 1) {
        $data_arr[$location_id][] = $row['district'];
    } else if ($wh_type == 2 && $report_type == 2) {
        $data_arr[$location_id][] = $row['district'];
        $data_arr[$location_id][] = $row['tehsil'];
        $data_arr[$location_id][] = $row['ucs'];
    } else if ($wh_type == 4 && $report_type == 1) {

        $data_arr[$location_id][] = $row['tehsil'];
    } else if ($wh_type == 4 && $report_type == 2) {

        $data_arr[$location_id][] = $row['tehsil'];
        $data_arr[$location_id][] = $row['ucs'];
    }
    $data_arr[$location_id][] = $row['lbt'];
    $data_arr[$location_id][] = $row['fixed_inside_uc_male'];
    $data_arr[$location_id][] = $row['fixed_inside_uc_female'];
    $data_arr[$location_id][] = $row['male_doses'];
    $data_arr[$location_id][] = $row['female_doses'];
    $data_arr[$location_id][] = $row['outreach_male'];
    $data_arr[$location_id][] = $row['outreach_female'];
    $data_arr[$location_id][] = $row['consumption'];
    $data_arr[$location_id][] = $row['consumptionPercentage'];

    $j++;
}


foreach ($data_arr as $dis_id => $sub_arr) {

    $xml_store .= "<row>";
    if ($wh_type == 2 && $report_type == 1) {
        $xml_store .= "<cell>$sub_arr[0]</cell>";
        $xml_store .= "<cell>$sub_arr[1]</cell>";
    } else if ($wh_type == 2 && $report_type == 2) {
        $xml_store .= "<cell>$sub_arr[0]</cell>";
        $xml_store .= "<cell>$sub_arr[1]</cell>";
        $xml_store .= "<cell>$sub_arr[2]</cell>";
        $xml_store .= "<cell>$sub_arr[3]</cell>";
    } else if ($wh_type == 4 && $report_type == 1) {
        $xml_store .= "<cell>$sub_arr[0]</cell>";
        $xml_store .= "<cell>$sub_arr[1]</cell>";
    } else if ($wh_type == 4 && $report_type == 2) {
        $xml_store .= "<cell>$sub_arr[0]</cell>";
        $xml_store .= "<cell>$sub_arr[1]</cell>";
        $xml_store .= "<cell>$sub_arr[2]</cell>";
    }


    foreach ($sub_arr as $key => $value) {

        if (!isset($sum_arr[$key])) {
            $sum_arr[$key] = 0;
        }
        $sum_arr[$key] += $value;
        if ($wh_type == 2 && $report_type == 1) {
            if ($key > 1) {

                $xml_store .= "<cell style=\"text-align:right;\">$value </cell>";
            }
        } else if ($wh_type == 2 && $report_type == 2) {
            if ($key > 3) {

                $xml_store .= "<cell style=\"text-align:right;\">$value </cell>";
            }
        } else if ($wh_type == 4 && $report_type == 1) {
            if ($key > 1) {

                $xml_store .= "<cell style=\"text-align:right;\">$value </cell>";
            }
        } else if ($wh_type == 4 && $report_type == 2) {
            if ($key > 2) {

                $xml_store .= "<cell style=\"text-align:right;\">$value </cell>";
            }
        }
    }
    $xml_store .= "</row>";
}

// To show Total
array_shift($sum_arr);

$xml_store .= "<row>";
if ($wh_type == 2 && $report_type == 1) {
    $xml_store .= "<cell></cell>";
} else if ($wh_type == 2 && $report_type == 2) {
    $xml_store .= "<cell></cell>";
    $xml_store .= "<cell></cell>";
    $xml_store .= "<cell></cell>";
} else if ($wh_type == 4 && $report_type == 1) {
    $xml_store .= "<cell></cell>";
} else if ($wh_type == 4 && $report_type == 2) {
    $xml_store .= "<cell></cell>";
    $xml_store .= "<cell></cell>";
}

$xml_store .= "<cell style=\"font-weight:bold\">Total</cell>";
foreach ($sum_arr as $key => $value) {

    if ($wh_type == 2 && $report_type == 1) {
        if ($key == 1) {
            $total_wh = $value;
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
        } else if ($key > 1 && $key < 8) {
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
        } else if ($key == 8) {
            $total_val = $value;
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
        } else if ($key == 9) {
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($total_val / $total_wh) * 100) . " %</cell>";
        }
    } else if ($wh_type == 2 && $report_type == 2) {
        if ($key == 3) {
            $total_wh = $value;
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
        } else if ($key > 3 && $key < 10) {
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
        } else if ($key == 10) {
            $total_val = $value;
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
        } else if ($key == 11) {
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($total_val / $total_wh) * 100) . " %</cell>";
        }
    } else if ($wh_type == 4 && $report_type == 1) {
        if ($key == 1) {
            $total_wh = $value;
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
        } else if ($key > 1 && $key < 8) {
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
        } else if ($key == 8) {
            $total_val = $value;
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
        } else if ($key == 9) {
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($total_val / $total_wh) * 100) . " %</cell>";
        }
    } else if ($wh_type == 4 && $report_type == 2) {
        if ($key == 2) {
            $total_wh = $value;
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
        } else if ($key > 2 && $key < 9) {
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
        } else if ($key == 9) {
            $total_val = $value;
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . number_format($value) . "</cell>";
        } else if ($key == 10) {
            $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($total_val / $total_wh) * 100) . " %</cell>";
        }
    }
}

$xml_store .= "</row>";

$xml_store .= "</rows>";
?>
<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $report_title; ?></h3>
        <h5 style="color: red">
            Note: Please check and provide feedback at support@lmis.gov.pk
        </h5>
        <div class="innerLR">
            <script>
                var mygrid;
                function doInitGrid() {
                    mygrid = new dhtmlXGridObject('mygrid_container');
                    mygrid.selMultiRows = true;
                    mygrid.setImagePath("<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
                    //mygrid.setHeader("Province,Consumption,AMC,On Hand,MOS,#cspan");
                    mygrid.setHeader(",<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'><?php echo "'$report_title at  $this->loc_name'   for (" . date('F', mktime(0, 0, 0, $this->from_month_sel)) . '-' . $this->from_year_sel . ') to (' . date('F', mktime(0, 0, 0, $this->month_sel)) . '-' . $this->from_year_sel; ?>)  (Doses)</div>,<?php echo substr($cspan, 0, -14); ?>");
                    mygrid.attachHeader("<?php echo $header; ?>");
                    mygrid.attachHeader("<?php echo $header1; ?>");
                    mygrid.setInitWidths("<?php echo $width; ?>");
                    mygrid.setColTypes("<?php echo $ro; ?>");
                    mygrid.enableRowsHover(true, 'onMouseOver');
                    mygrid.setSkin("light");
                    mygrid.init();
                    mygrid.clearAll();
                    $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($xml_store); ?></textarea>');
                    mygrid.loadXMLString(document.getElementById('xml_string').value);
                }
            </script>
            <table width="99%">
                <tr>
                    <td colspan="2">
                        <?php
                        echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                        ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?php echo $this->render('inventory-management/reports-header_coverage.phtml') ?>
                    </td>
                </tr>

                <tr>
                    <td style="text-align:right; padding-bottom:10px;">
                        <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="<?php echo $this->translate("Export to PDF"); ?>"/>&nbsp;&nbsp;
                        <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="<?php echo $this->translate("Export to Excel"); ?>" />
                    </td>
                </tr>

            </table>

            <table width="99%" cellpadding="0" cellspacing="0">
                <tr>
                    <td>
                        <div id="mygrid_container" style="width:100%; height:700px;"></div>
                    </td>
                </tr>
                <tr>
                    <td>
                        Total Consumption = Fixed +  Outreach
                    </td></tr>
            </table>
        </div>
    </div>
</div>

<script>

    var whType = <?php echo $wh_type; ?>;
    var province = <?php echo $sel_prov; ?>;
    var district = <?php echo $sel_dist; ?>;
    var tehsil = <?php echo $sel_tehsil; ?>;

</script>


