<?php
error_reporting(0);
/**
 *  phtml for Pentavalent Coverage Detail
 */
?>
<?php
$from_sel_month = $this->from_month_sel;
$from_sel_year = $this->from_year_sel;
$year = $this->year_sel;
$month = $this->month_sel;
$sel_prov = $this->prov_sel;
$sel_dist = $this->district_id;
$sel_tehsil = $this->tehsil;
$wh_type = $this->wh_type;
$report_type = $this->report_type;
// Headers of the Grid
?>

<?php
//echo $year = $this->year_sel;
//exit;
?>



<?php
$sum_arr = array();

$query = $this->reports()->pentaCoverageReport($wh_type, $year, $month, $from_sel_month, $from_sel_year, $sel_prov, $sel_dist, $sel_tehsil, Model_ListDetail::AGE_0_11, 1, 0, 11, $report_type);
$j = 1;
foreach ($query as $row) {
    $location_id = $row['location_id'];
    $data_arr[$location_id][] = $j;

    if ($wh_type == 2 && $report_type == 1) {
        $data_arr[$location_id][] = $row['district'];
    } else if ($wh_type == 2 && $report_type == 2) {
        $data_arr[$location_id][] = $row['district'];
        $data_arr[$location_id][] = $row['tehsil'];
        $data_arr[$location_id][] = $row['ucs'];
    } else if ($wh_type == 2 && $report_type == 3) {
        $data_arr[$location_id][] = $row['district'];
        $data_arr[$location_id][] = $row['tehsil'];
        $data_arr[$location_id][] = $row['ucs'];
        $data_arr[$location_id][] = $row['hfs'];
    } else if ($wh_type == 4 && $report_type == 1) {

        $data_arr[$location_id][] = $row['tehsil'];
    } else if ($wh_type == 4 && $report_type == 2) {

        $data_arr[$location_id][] = $row['tehsil'];
        $data_arr[$location_id][] = $row['ucs'];
    } else if ($wh_type == 4 && $report_type == 3) {

        $data_arr[$location_id][] = $row['tehsil'];
        $data_arr[$location_id][] = $row['ucs'];
        $data_arr[$location_id][] = $row['hfs'];
    }
    if ($from_sel_year >= '2018' && $sel_prov==2) {
        $data_arr[$location_id][] = $row['lbt'];
        $data_arr[$location_id][] = $row['fixed_inside_uc_male_1_0_11'];
        $data_arr[$location_id][] = $row['fixed_inside_uc_female_1_0_11'];
        $data_arr[$location_id][] = $row['outreach_male_1_0_11'];
        $data_arr[$location_id][] = $row['outreach_female_1_0_11'];
        $data_arr[$location_id][] = $row['outreach_outside_male'];
        $data_arr[$location_id][] = $row['outreach_outside_female'];
        $data_arr[$location_id][] = $row['fixed_outside_uc_male'];
        $data_arr[$location_id][] = $row['fixed_outside_uc_female'];
        $data_arr[$location_id][] = $row['male_doses'];
        $data_arr[$location_id][] = $row['female_doses'];

        $data_arr[$location_id][] = $row['fixed_inside_uc_male_1_0_11'] + $row['fixed_inside_uc_female_1_0_11'] + $row['outreach_male_1_0_11'] + $row['outreach_female_1_0_11'] + $row['male_doses'] + $row['female_doses'];
        $data_arr[$location_id][] = @Round((($row['fixed_inside_uc_male_1_0_11'] + $row['fixed_inside_uc_female_1_0_11'] + $row['outreach_male_1_0_11'] + $row['outreach_female_1_0_11'] + $row['male_doses'] + $row['female_doses']) / $row['lbt']) * 100);


        $data_arr[$location_id][] = $row['fixed_inside_uc_male_1_0_11'] + $row['fixed_inside_uc_female_1_0_11'] + $row['outreach_male_1_0_11'] + $row['outreach_female_1_0_11'] + $row['fixed_outside_uc_male'] + $row['fixed_outside_uc_female'] + $row['male_doses'] + $row['female_doses'];
        $data_arr[$location_id][] = @Round((($row['fixed_inside_uc_male_1_0_11'] + $row['fixed_inside_uc_female_1_0_11'] + $row['outreach_male_1_0_11'] + $row['outreach_female_1_0_11'] + $row['fixed_outside_uc_male'] + $row['fixed_outside_uc_female'] + $row['male_doses'] + $row['female_doses']) / $row['lbt']) * 100);
    } else {
        $data_arr[$location_id][] = $row['lbt'];
        $data_arr[$location_id][] = $row['fixed_inside_uc_male_1_0_11'];
        $data_arr[$location_id][] = $row['fixed_inside_uc_female_1_0_11'];
        $data_arr[$location_id][] = $row['male_doses'];
        $data_arr[$location_id][] = $row['female_doses'];
        $data_arr[$location_id][] = $row['outreach_male_1_0_11'];
        $data_arr[$location_id][] = $row['outreach_female_1_0_11'];
        $data_arr[$location_id][] = $row['consumption_1_0_11'];
        $data_arr[$location_id][] = $row['consumptionPercentage_1_0_11'];
        $total_consumpiton[$location_id][] = $row['consumption_1_0_11'];
    }
    $j++;
}
$query1 = $this->reports()->pentaCoverageReport($wh_type, $year, $month, $from_sel_month, $from_sel_year, $sel_prov, $sel_dist, $sel_tehsil, Model_ListDetail::AGE_0_11, 2, 0, 11, $report_type);

foreach ($query1 as $row1) {

    $location_id1 = $row1['location_id'];
    if ($from_sel_year >= '2018' && $sel_prov==2) {

        $data_arr[$location_id1][] = $row1['fixed_inside_uc_male_1_0_11'];
        $data_arr[$location_id1][] = $row1['fixed_inside_uc_female_1_0_11'];
        $data_arr[$location_id1][] = $row1['outreach_male_1_0_11'];
        $data_arr[$location_id1][] = $row1['outreach_female_1_0_11'];

        $data_arr[$location_id1][] = $row1['outreach_outside_male'];
        $data_arr[$location_id1][] = $row1['outreach_outside_female'];

        $data_arr[$location_id1][] = $row1['fixed_outside_uc_male'];
        $data_arr[$location_id1][] = $row1['fixed_outside_uc_female'];

        $data_arr[$location_id1][] = $row1['male_doses'];
        $data_arr[$location_id1][] = $row1['female_doses'];

        $data_arr[$location_id1][] = $row1['fixed_inside_uc_male_1_0_11'] + $row1['fixed_inside_uc_female_1_0_11'] + $row1['outreach_male_1_0_11'] + $row1['outreach_female_1_0_11'] + $row1['male_doses'] + $row1['female_doses'];
        $data_arr[$location_id1][] = @Round((($row1['fixed_inside_uc_male_1_0_11'] + $row1['fixed_inside_uc_female_1_0_11'] + $row1['outreach_male_1_0_11'] + $row1['outreach_female_1_0_11'] + $row1['male_doses'] + $row1['female_doses']) / $row1['lbt']) * 100);


        $data_arr[$location_id1][] = $row1['fixed_inside_uc_male_1_0_11'] + $row1['fixed_inside_uc_female_1_0_11'] + $row1['outreach_male_1_0_11'] + $row1['outreach_female_1_0_11'] + $row1['fixed_outside_uc_male'] + $row1['fixed_outside_uc_female'] + $row1['male_doses'] + $row1['female_doses'];
        $data_arr[$location_id1][] = @Round((($row1['fixed_inside_uc_male_1_0_11'] + $row1['fixed_inside_uc_female_1_0_11'] + $row1['outreach_male_1_0_11'] + $row1['outreach_female_1_0_11'] + $row1['fixed_outside_uc_male'] + $row1['fixed_outside_uc_female'] + $row1['male_doses'] + $row1['female_doses']) / $row1['lbt']) * 100);
    } else {
        $data_arr[$location_id1][] = $row1['fixed_inside_uc_male_1_0_11'];
        $data_arr[$location_id1][] = $row1['fixed_inside_uc_female_1_0_11'];
        $data_arr[$location_id1][] = $row1['male_doses'];
        $data_arr[$location_id1][] = $row1['female_doses'];
        $data_arr[$location_id1][] = $row1['outreach_male_1_0_11'];
        $data_arr[$location_id1][] = $row1['outreach_female_1_0_11'];
        $data_arr[$location_id1][] = $row1['consumption_1_0_11'];
        $data_arr[$location_id1][] = $row1['consumptionPercentage_1_0_11'];
        $total_consumpiton[$location_id1][] = $row1['consumption_1_0_11'];
    }
}
$query2 = $this->reports()->pentaCoverageReport($wh_type, $year, $month, $from_sel_month, $from_sel_year, $sel_prov, $sel_dist, $sel_tehsil, Model_ListDetail::AGE_0_11, 3, 0, 11, $report_type);


foreach ($query2 as $row2) {
    $location_id2 = $row2['location_id'];
    if ($from_sel_year >= '2018' && $sel_prov==2) {

        $data_arr[$location_id2][] = $row2['fixed_inside_uc_male_1_0_11'];
        $data_arr[$location_id2][] = $row2['fixed_inside_uc_female_1_0_11'];
        $data_arr[$location_id2][] = $row2['outreach_male_1_0_11'];
        $data_arr[$location_id2][] = $row2['outreach_female_1_0_11'];

        $data_arr[$location_id2][] = $row2['outreach_outside_male'];
        $data_arr[$location_id2][] = $row2['outreach_outside_female'];

        $data_arr[$location_id2][] = $row2['fixed_outside_uc_male'];
        $data_arr[$location_id2][] = $row2['fixed_outside_uc_female'];

        $data_arr[$location_id2][] = $row2['male_doses'];
        $data_arr[$location_id2][] = $row2['female_doses'];

        $data_arr[$location_id2][] = $row2['fixed_inside_uc_male_1_0_11'] + $row2['fixed_inside_uc_female_1_0_11'] + $row2['outreach_male_1_0_11'] + $row2['outreach_female_1_0_11'] + $row2['male_doses'] + $row2['female_doses'];
        $data_arr[$location_id2][] = @Round((($row2['fixed_inside_uc_male_1_0_11'] + $row2['fixed_inside_uc_female_1_0_11'] + $row2['outreach_male_1_0_11'] + $row2['outreach_female_1_0_11'] + $row2['male_doses'] + $row2['female_doses']) / $row2['lbt']) * 100);


        $data_arr[$location_id2][] = $row2['fixed_inside_uc_male_1_0_11'] + $row2['fixed_inside_uc_female_1_0_11'] + $row2['outreach_male_1_0_11'] + $row2['outreach_female_1_0_11'] + $row2['fixed_outside_uc_male'] + $row2['fixed_outside_uc_female'] + $row2['male_doses'] + $row2['female_doses'];
        $data_arr[$location_id2][] = @Round((($row2['fixed_inside_uc_male_1_0_11'] + $row2['fixed_inside_uc_female_1_0_11'] + $row2['outreach_male_1_0_11'] + $row2['outreach_female_1_0_11'] + $row2['fixed_outside_uc_male'] + $row2['fixed_outside_uc_female'] + $row2['male_doses'] + $row2['female_doses']) / $row2['lbt']) * 100);
    } else {
        $data_arr[$location_id2][] = $row2['fixed_inside_uc_male_1_0_11'];
        $data_arr[$location_id2][] = $row2['fixed_inside_uc_female_1_0_11'];
        $data_arr[$location_id2][] = $row2['male_doses'];
        $data_arr[$location_id2][] = $row2['female_doses'];
        $data_arr[$location_id2][] = $row2['outreach_male_1_0_11'];
        $data_arr[$location_id2][] = $row2['outreach_female_1_0_11'];
        $data_arr[$location_id2][] = $row2['consumption_1_0_11'];
        $data_arr[$location_id2][] = $row2['consumptionPercentage_1_0_11'];
        $total_consumpiton[$location_id2][] = $row2['consumption_1_0_11'];
    }
}

$query_t_1year = $this->reports()->pentaCoverageReport($wh_type, $year, $month, $from_sel_month, $from_sel_year, $sel_prov, $sel_dist, $sel_tehsil, Model_ListDetail::AGE_12_23, 3, 12, 23, $report_type);


foreach ($query_t_1year as $row_t_1year) {
    if ($from_sel_year >= '2018' && $sel_prov==2) {
        //   $location_id_t_1year = $row_t_1year['location_id'];
        //   $data_arr[$location_id_t_1year][] = @round((array_sum($total_consumpiton[$location_id_t_1year]) / $row_t_1year['lbt']) * 100);
    } else {
        $location_id_t_1year = $row_t_1year['location_id'];

        $data_arr[$location_id_t_1year][] = array_sum($total_consumpiton[$location_id_t_1year]);
        $data_arr[$location_id_t_1year][] = @round((array_sum($total_consumpiton[$location_id_t_1year]) / $row_t_1year['lbt']) * 100);
    }
}

$query3 = $this->reports()->pentaCoverageReport($wh_type, $year, $month, $from_sel_month, $from_sel_year, $sel_prov, $sel_dist, $sel_tehsil, Model_ListDetail::AGE_12_23, 1, 12, 23, $report_type);

foreach ($query3 as $row3) {
    $location_id3 = $row3['location_id'];
    if ($from_sel_year >= '2018' && $sel_prov==2) {
        $data_arr[$location_id3][] = $row3['target2'];
        $data_arr[$location_id3][] = $row3['fixed_inside_uc_male_1_0_11'];
        $data_arr[$location_id3][] = $row3['fixed_inside_uc_female_1_0_11'];
        $data_arr[$location_id3][] = $row3['outreach_male_1_0_11'];
        $data_arr[$location_id3][] = $row3['outreach_female_1_0_11'];

        $data_arr[$location_id3][] = $row3['outreach_outside_male'];
        $data_arr[$location_id3][] = $row3['outreach_outside_female'];

        $data_arr[$location_id3][] = $row3['fixed_outside_uc_male'];
        $data_arr[$location_id3][] = $row3['fixed_outside_uc_female'];

        $data_arr[$location_id3][] = $row3['male_doses'];
        $data_arr[$location_id3][] = $row3['female_doses'];

        $data_arr[$location_id3][] = $row3['fixed_inside_uc_male_1_0_11'] + $row3['fixed_inside_uc_female_1_0_11'] + $row3['outreach_male_1_0_11'] + $row3['outreach_female_1_0_11'] + $row3['male_doses'] + $row3['female_doses'];
        $data_arr[$location_id3][] = @Round((($row3['fixed_inside_uc_male_1_0_11'] + $row3['fixed_inside_uc_female_1_0_11'] + $row3['outreach_male_1_0_11'] + $row3['outreach_female_1_0_11'] + $row3['male_doses'] + $row3['female_doses']) / $row3['target2']) * 100);


        $data_arr[$location_id3][] = $row3['fixed_inside_uc_male_1_0_11'] + $row3['fixed_inside_uc_female_1_0_11'] + $row3['outreach_male_1_0_11'] + $row3['outreach_female_1_0_11'] + $row3['fixed_outside_uc_male'] + $row3['fixed_outside_uc_female'] + $row3['male_doses'] + $row3['female_doses'];
        $data_arr[$location_id3][] = @Round((($row3['fixed_inside_uc_male_1_0_11'] + $row3['fixed_inside_uc_female_1_0_11'] + $row3['outreach_male_1_0_11'] + $row3['outreach_female_1_0_11'] + $row3['fixed_outside_uc_male'] + $row3['fixed_outside_uc_female'] + $row3['male_doses'] + $row3['female_doses']) / $row3['target2']) * 100);
    } else {
        $data_arr[$location_id3][] = $row3['target2'];
        $data_arr[$location_id3][] = $row3['fixed_inside_uc_male_1_0_11'];
        $data_arr[$location_id3][] = $row3['fixed_inside_uc_female_1_0_11'];
        $data_arr[$location_id3][] = $row3['male_doses'];
        $data_arr[$location_id3][] = $row3['female_doses'];
        $data_arr[$location_id3][] = $row3['outreach_male_1_0_11'];
        $data_arr[$location_id3][] = $row3['outreach_female_1_0_11'];
        $data_arr[$location_id3][] = $row3['consumption_1_0_11'];
        $data_arr[$location_id3][] = $row3['consumptionPercentage_2'];
        $total_consumpiton2[$location_id3][] = $row3['consumption_1_0_11'];
        $total_consumpiton[$location_id3][] = $row3['consumption_1_0_11'];
    }
}

$query4 = $this->reports()->pentaCoverageReport($wh_type, $year, $month, $from_sel_month, $from_sel_year, $sel_prov, $sel_dist, $sel_tehsil, Model_ListDetail::AGE_12_23, 2, 12, 23, $report_type);


foreach ($query4 as $row4) {

    $location_id4 = $row4['location_id'];
    if ($from_sel_year >= '2018' && $sel_prov==2) {

        $data_arr[$location_id4][] = $row4['fixed_inside_uc_male_1_0_11'];
        $data_arr[$location_id4][] = $row4['fixed_inside_uc_female_1_0_11'];
        $data_arr[$location_id4][] = $row4['outreach_male_1_0_11'];
        $data_arr[$location_id4][] = $row4['outreach_female_1_0_11'];

        $data_arr[$location_id4][] = $row4['outreach_outside_male'];
        $data_arr[$location_id4][] = $row4['outreach_outside_female'];

        $data_arr[$location_id4][] = $row4['fixed_outside_uc_male'];
        $data_arr[$location_id4][] = $row4['fixed_outside_uc_female'];

        $data_arr[$location_id4][] = $row4['male_doses'];
        $data_arr[$location_id4][] = $row4['female_doses'];

        $data_arr[$location_id4][] = $row4['fixed_inside_uc_male_1_0_11'] + $row4['fixed_inside_uc_female_1_0_11'] + $row4['outreach_male_1_0_11'] + $row4['outreach_female_1_0_11'] + $row4['male_doses'] + $row4['female_doses'];
        $data_arr[$location_id4][] = @Round((($row4['fixed_inside_uc_male_1_0_11'] + $row4['fixed_inside_uc_female_1_0_11'] + $row4['outreach_male_1_0_11'] + $row4['outreach_female_1_0_11'] + $row4['male_doses'] + $row4['female_doses']) / $row4['target2']) * 100);


        $data_arr[$location_id4][] = $row4['fixed_inside_uc_male_1_0_11'] + $row4['fixed_inside_uc_female_1_0_11'] + $row4['outreach_male_1_0_11'] + $row4['outreach_female_1_0_11'] + $row4['fixed_outside_uc_male'] + $row4['fixed_outside_uc_female'] + $row4['male_doses'] + $row4['female_doses'];
        $data_arr[$location_id4][] = @Round((($row4['fixed_inside_uc_male_1_0_11'] + $row4['fixed_inside_uc_female_1_0_11'] + $row4['outreach_male_1_0_11'] + $row4['outreach_female_1_0_11'] + $row4['fixed_outside_uc_male'] + $row4['fixed_outside_uc_female'] + $row4['male_doses'] + $row4['female_doses']) / $row4['target2']) * 100);
    } else {
        $data_arr[$location_id4][] = $row4['fixed_inside_uc_male_1_0_11'];
        $data_arr[$location_id4][] = $row4['fixed_inside_uc_female_1_0_11'];
        $data_arr[$location_id4][] = $row4['male_doses'];
        $data_arr[$location_id4][] = $row4['female_doses'];
        $data_arr[$location_id4][] = $row4['outreach_male_1_0_11'];
        $data_arr[$location_id4][] = $row4['outreach_female_1_0_11'];
        $data_arr[$location_id4][] = $row4['consumption_1_0_11'];
        $data_arr[$location_id4][] = $row4['consumptionPercentage_2'];
        $total_consumpiton2[$location_id4][] = $row4['consumption_1_0_11'];
        $total_consumpiton[$location_id4][] = $row4['consumption_1_0_11'];
    }
}

$query5 = $this->reports()->pentaCoverageReport($wh_type, $year, $month, $from_sel_month, $from_sel_year, $sel_prov, $sel_dist, $sel_tehsil, Model_ListDetail::AGE_12_23, 3, 12, 23, $report_type);


foreach ($query5 as $row5) {

    $location_id5 = $row5['location_id'];
    if ($from_sel_year >= '2018' && $sel_prov==2) {

        $data_arr[$location_id5][] = $row5['fixed_inside_uc_male_1_0_11'];
        $data_arr[$location_id5][] = $row5['fixed_inside_uc_female_1_0_11'];
        $data_arr[$location_id5][] = $row5['outreach_male_1_0_11'];
        $data_arr[$location_id5][] = $row5['outreach_female_1_0_11'];

        $data_arr[$location_id5][] = $row5['outreach_outside_male'];
        $data_arr[$location_id5][] = $row5['outreach_outside_female'];

        $data_arr[$location_id5][] = $row5['fixed_outside_uc_male'];
        $data_arr[$location_id5][] = $row5['fixed_outside_uc_female'];

        $data_arr[$location_id5][] = $row5['male_doses'];
        $data_arr[$location_id5][] = $row5['female_doses'];

        $data_arr[$location_id5][] = $row5['fixed_inside_uc_male_1_0_11'] + $row5['fixed_inside_uc_female_1_0_11'] + $row5['outreach_male_1_0_11'] + $row5['outreach_female_1_0_11'] + $row5['male_doses'] + $row5['female_doses'];
        $data_arr[$location_id5][] = @Round((($row5['fixed_inside_uc_male_1_0_11'] + $row5['fixed_inside_uc_female_1_0_11'] + $row5['outreach_male_1_0_11'] + $row5['outreach_female_1_0_11'] + $row5['male_doses'] + $row5['female_doses']) / $row5['target2']) * 100);


        $data_arr[$location_id5][] = $row5['fixed_inside_uc_male_1_0_11'] + $row5['fixed_inside_uc_female_1_0_11'] + $row5['outreach_male_1_0_11'] + $row5['outreach_female_1_0_11'] + $row5['fixed_outside_uc_male'] + $row5['fixed_outside_uc_female'] + $row5['male_doses'] + $row5['female_doses'];
        $data_arr[$location_id5][] = @Round((($row5['fixed_inside_uc_male_1_0_11'] + $row5['fixed_inside_uc_female_1_0_11'] + $row5['outreach_male_1_0_11'] + $row5['outreach_female_1_0_11'] + $row5['fixed_outside_uc_male'] + $row5['fixed_outside_uc_female'] + $row5['male_doses'] + $row5['female_doses']) / $row5['target2']) * 100);
    } else {
        $data_arr[$location_id5][] = $row5['fixed_inside_uc_male_1_0_11'];
        $data_arr[$location_id5][] = $row5['fixed_inside_uc_female_1_0_11'];
        $data_arr[$location_id5][] = $row5['male_doses'];
        $data_arr[$location_id5][] = $row5['female_doses'];
        $data_arr[$location_id5][] = $row5['outreach_male_1_0_11'];
        $data_arr[$location_id5][] = $row5['outreach_female_1_0_11'];
        $data_arr[$location_id5][] = $row5['consumption_1_0_11'];
        $data_arr[$location_id5][] = $row5['consumptionPercentage_2'];
        $total_consumpiton2[$location_id5][] = $row5['consumption_1_0_11'];
        $total_consumpiton[$location_id5][] = $row5['consumption_1_0_11'];
    }
}
// total less than 2 years
$query_t_2year = $this->reports()->pentaCoverageReport($wh_type, $year, $month, $from_sel_month, $from_sel_year, $sel_prov, $sel_dist, $sel_tehsil, Model_ListDetail::AGE_12_23, 3, 12, 23, $report_type);


foreach ($query_t_2year as $row_t_2year) {
    if ($from_sel_year >= '2018' && $sel_prov==2) {
        
    }
   else   {
        $location_id_t_2year = $row_t_2year['location_id'];
        $data_arr[$location_id_t_2year][] = array_sum($total_consumpiton2[$location_id_t_2year]);
        $data_arr[$location_id_t_2year][] = @round((array_sum($total_consumpiton2[$location_id_t_2year]) / $row_t_2year['target2']) * 100);
    }
}



$query6 = $this->reports()->pentaCoverageReport($wh_type, $year, $month, $from_sel_month, $from_sel_year, $sel_prov, $sel_dist, $sel_tehsil, Model_ListDetail::AGE_12_23, 3, 12, 23, $report_type);


foreach ($query6 as $row6) {
     if ($from_sel_year >= '2018' && $sel_prov==2) {
        
    }
   else   {
        $location_id6 = $row6['location_id'];
        $target_avg = ($row6['target2'] + $row6['lbt']);

        $data_arr[$location_id6][] = array_sum($total_consumpiton[$location_id6]);
        $data_arr[$location_id6][] = @round((array_sum($total_consumpiton[$location_id6]) / $target_avg) * 100);
    }
}
?>
<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $report_title; ?></h3>


        <div class="row">
            <table width="99%">
                <tr>
                    <td colspan="2">
                        <?php echo $this->render('inventory-management/header_coverage.phtml') ?>
                    </td>
                </tr>
            </table>
            <div class="col-md-12 right">

                <img src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="tableToExcel('export', 'sheet 1', '<?php echo $report_title; ?>')" alt="Excel" style="cursor:pointer;" />
            </div>
        </div>
        <div>
            &nbsp; &nbsp; &nbsp;
        </div>
        <div class="row" id="export">
            <style>
                table#myTable{margin-top:0px !important; color: #000;}
                table#myTable{margin-top:20px;border-collapse: collapse;border-spacing: 0; border:1px solid #999;}
                table#myTable tr td{font-size:11px;padding:3px; text-align:left; border:1px solid #ddd; color: #000;}
                table#myTable tr:nth-child(even){background-color: #f2f2f2;}

                table#myTable tr:hover {background-color: #ddd;}
                table#myTable tr th{
                    font-size:11px;
                    padding-top: 12px;
                    padding-bottom: 12px;
                    text-align: center;
                    background-color: #4CAF50;
                    border:1px solid #ddd;
                    color: white;}
                table#myTable tr td.TAR{text-align:right; padding:5px;width:50px !important;}
                .sb1NormalFont {color: #444444; font-size: 11px; font-weight: bold; text-decoration: none;}
                p{margin-bottom:5px; font-size:11px !important; line-height:1 !important; padding:0 !important; color: #000;}
                table#headerTable tr td{ font-size:11px; color: #000;}
                h4{margin:0; color: #000; font-size:14px;}
                h5{margin:15px 0 5px 0; color: #000;}
                h6{margin:0; color: #000; font-size:12px;}
                .right{text-align:right !important;}
                .center{text-align:center !important;}

                /* Print styles */
                @media only print
                {
                    table#myTable{margin-top:0px !important;}
                    table#myTable tr th{font-size:8px;padding:3px !important; text-align:center; border:1px solid #999; color: #000;}
                    table#myTable tr td{font-size:8px;padding:3px !important; text-align:left; border:1px solid #999; color: #000;}
                    #doNotPrint{display: none !important;}
                    h4{margin:0; color: #000;}
                    h5{margin:0; color: #000;}
                    h6{margin:0; color: #000;}
                    p{margin-bottom:5px; font-size:11px !important; line-height:1 !important; padding:0 !important; color: #000;}
                }
            </style>


            <script>
                function printContents() {
                    var w = 900;
                    var h = screen.height;
                    var left = Number((screen.width / 2) - (w / 2));
                    var top = Number((screen.height / 2) - (h / 2));
                    var dispSetting = "toolbar=yes,location=no,directories=yes,menubar=yes,scrollbars=yes,left=" + left + ",top=" + top + ",width=" + w + ",height=" + h;
                    var printingContents = document.getElementById("export").innerHTML;
                    var docprint = window.open("", "", dispSetting);
                    docprint.document.open();
                    docprint.document.write('<html><head>');
                    docprint.document.write('</head><body onLoad="self.print();self.close();"><center>');
                    docprint.document.write(printingContents);
                    docprint.document.write('</center></body></html>');
                    docprint.document.close();
                    docprint.focus();
                }

            </script>

            <div class="innerLR" style="overflow:auto;">
                <table width="100%">

                    <td align="center"><h4 class="center">
                            <?php echo "'$report_title at  $this->loc_name'" . '<br>' . " for (" . date('F', mktime(0, 0, 0, $this->from_month_sel, 1)) . '-' . $this->from_year_sel . ') to (' . date('F', mktime(0, 0, 0, $this->month_sel, 1)) . '-' . $this->from_year_sel; ?>)  (Doses)
                        </h4></td>
                    </tr>
                    <tr>
                        <td style="padding-top: 10px;"><table id="myTable" style="<?php if ($from_sel_year <= '2017') { ?>width:4000px<?php } else { ?>width:4000px<?php } ?>" cellspacing="0" align="center">
                                <thead>
                                    <?php if ($this->from_year_sel >= '2018'  && $sel_prov==2) { ?>
                                        <tr>

                                            <?php
                                            if ($wh_type == 2 && $report_type == 1) {
                                                ?>
                                                <th rowspan="5" width="1%">S.No</th>
                                                <th rowspan="5" width="1%">District</th>
                                                <th rowspan="5" width="1%">Target</th>
                                                <?php
                                                $w1 = '1%';
                                                $w2 = '1%';
                                                $w3 = '1%';
                                                ?>
                                                <?php
                                            } else if ($wh_type == 2 && $report_type == 2) {
                                                ?>
                                                <th rowspan="5" width="1%">Sr.No.</th>
                                                <th rowspan="5" width="1%">District</th>
                                                <th rowspan="5" width="1%">Tehsil/Taluka</th>
                                                <th rowspan="5" width="1%">UC</th>
                                                <th rowspan="5" width="1%">Target</th>
                                                <?php
                                                $w1 = '1%';
                                                $w2 = '1%';
                                                $w3 = '1%';
                                            } else if ($wh_type == 2 && $report_type == 3) {
                                                ?>
                                                <th rowspan="5" width="1%">Sr.No.</th>
                                                <th rowspan="5" width="1%">District</th>
                                                <th rowspan="5" width="1%">Tehsil/Taluka</th>
                                                <th rowspan="5" width="1%">UC</th>
                                                <th rowspan="5" width="1%">HF</th>
                                                <th rowspan="5" width="1%">Target</th>
                                                <?php
                                                $w1 = '1%';
                                                $w2 = '1%';
                                                $w3 = '1%';
                                                ?>
                                                <?php
                                            } else if ($wh_type == 4 && $report_type == 1) {
                                                ?>
                                                <th rowspan="5" width="1%">Sr.No.</th>

                                                <th rowspan="5" width="1%">Tehsil/Taluka</th>

                                                <th rowspan="5" width="1%">Target</th>
                                                <?php
                                                $w1 = '1%';
                                                $w2 = '1%';
                                                $w3 = '1%';
                                                ?>
                                                <?php
                                            } else if ($wh_type == 4 && $report_type == 2) {
                                                ?>
                                                <th rowspan="5" width="1%">Sr.No.</th>
                                                <th rowspan="5" width="1%">Tehsil/Taluka</th>
                                                <th rowspan="5" width="1%">UC</th>
                                                <th rowspan="5" width="1%">Target</th>
                                                <?php
                                                $w1 = '1%';
                                                $w2 = '1%';
                                                $w3 = '1%';
                                                ?>
                                                <?php
                                            } else if ($wh_type == 4 && $report_type == 3) {
                                                ?>
                                                <th rowspan="5" width="1%">Sr.No.</th>
                                                <th rowspan="5" width="1%">Tehsil/Taluka</th>
                                                <th rowspan="5" width="1%">UC</th>
                                                <th rowspan="5" width="1%">HF</th>
                                                <th rowspan="5" width="1%">Target</th>
                                                <?php
                                                $w1 = '1%';
                                                $w2 = '1%';
                                                $w3 = '1%';
                                                ?>
                                            <?php }
                                            ?>


                                        </tr>
                                    <?php } else { ?>
                                        <tr>

                                            <?php
                                            if ($wh_type == 2 && $report_type == 1) {
                                                ?>
                                                <th rowspan="4" width="2%">S.No</th>
                                                <th rowspan="4" width="3%">District</th>
                                                <th rowspan="4" width="3%">Target</th>
                                                <?php
                                                $w1 = '1%';
                                                $w2 = '1%';
                                                $w3 = '3%';
                                                ?>
                                                <?php
                                            } else if ($wh_type == 2 && $report_type == 2) {
                                                ?>
                                                <th rowspan="4" width="2%">Sr.No.</th>
                                                <th rowspan="4" width="3%">District</th>
                                                <th rowspan="4" width="3%">Tehsil/Taluka</th>
                                                <th rowspan="4" width="3%">UC</th>
                                                <th rowspan="4" width="3%">Target</th>
                                                <?php
                                                $w1 = '1%';
                                                $w2 = '1%';
                                                $w3 = '3%';
                                            } else if ($wh_type == 2 && $report_type == 3) {
                                                ?>
                                                <th rowspan="4" width="2%">Sr.No.</th>
                                                <th rowspan="4" width="3%">District</th>
                                                <th rowspan="4" width="3%">Tehsil/Taluka</th>
                                                <th rowspan="4" width="3%">UC</th>
                                                <th rowspan="4" width="3%">HF</th>
                                                <th rowspan="4" width="2%">Target</th>
                                                <?php
                                                $w1 = '1%';
                                                $w2 = '1%';
                                                $w3 = '3%';
                                                ?>
                                                <?php
                                            } else if ($wh_type == 4 && $report_type == 1) {
                                                ?>
                                                <th rowspan="4" width="2%">Sr.No.</th>

                                                <th rowspan="4" width="3%">Tehsil/Taluka</th>

                                                <th rowspan="4" width="3%">Target</th>
                                                <?php
                                                $w1 = '1%';
                                                $w2 = '1%';
                                                $w3 = '3%';
                                                ?>
                                                <?php
                                            } else if ($wh_type == 4 && $report_type == 2) {
                                                ?>
                                                <th rowspan="4" width="2%">Sr.No.</th>
                                                <th rowspan="4" width="3%">Tehsil/Taluka</th>
                                                <th rowspan="4" width="3%">UC</th>
                                                <th rowspan="4" width="3%">Target</th>
                                                <?php
                                                $w1 = '1%';
                                                $w2 = '1%';
                                                $w3 = '3%';
                                                ?>
                                                <?php
                                            } else if ($wh_type == 4 && $report_type == 3) {
                                                ?>
                                                <th rowspan="4" width="2%">Sr.No.</th>
                                                <th rowspan="4" width="3%">Tehsil/Taluka</th>
                                                <th rowspan="4" width="3%">UC</th>
                                                <th rowspan="4" width="3%">HF</th>
                                                <th rowspan="4" width="2%">Target</th>
                                                <?php
                                                $w1 = '1%';
                                                $w2 = '1%';
                                                $w3 = '3%';
                                                ?>
                                            <?php }
                                            ?>


                                        </tr>
                                    <?php } ?>
                                    <?php if ($this->from_year_sel >= '2018' && $sel_prov==2) { ?>
                                        <tr>
                                            <th tyle='text-align:center;' colspan="14">Coverage Penta-1(0-11 Months) </th>
                                            <th tyle='text-align:center;' colspan="14" >Coverage Penta-2(0-11 Months)</th>
                                            <th tyle='text-align:center;' colspan="14" >Coverage Penta-3(0-11 Months)</th>
                                            <th tyle='text-align:center;' width="2%" rowspan="4" >less than 2 years</th>
                                            <th tyle='text-align:center;' colspan="14">Coverage Penta-1(12-23 Months) </th>
                                            <th tyle='text-align:center;' colspan="14" >Coverage Penta-2(12-23 Months)</th>
                                            <th tyle='text-align:center;' colspan="14" >Coverage Penta-3(12-23 Months)</th>

                                        </tr>
                                        <tr>
                                            <th tyle='text-align:center;'  colspan="6"  width="<?php echo $w1; ?>">Inside UC </th>

                                            <th tyle='text-align:center;' colspan="4" width="<?php echo $w1; ?>">Outside UC</th>

                                            <th tyle='text-align:center;'  rowspan="2" colspan="2" width="<?php echo $w3; ?>">Total Children <br> Vaccinated Inside UC</th>
                                            <th tyle='text-align:center;'  rowspan="2" colspan="2" width="<?php echo $w3; ?>">Total Children <br> Vaccinated Inside + <br> Outside UC </th>

                                            <th tyle='text-align:center;'  colspan="6"  width="<?php echo $w1; ?>">Inside UC </th>

                                            <th tyle='text-align:center;' colspan="4" width="<?php echo $w1; ?>">Outside UC</th>

                                            <th tyle='text-align:center;'  rowspan="2" colspan="2" width="<?php echo $w3; ?>">Total Children <br> Vaccinated Inside UC</th>
                                            <th tyle='text-align:center;'  rowspan="2" colspan="2" width="<?php echo $w3; ?>">Total Children <br> Vaccinated Inside + <br> Outside UC </th>

                                            <th tyle='text-align:center;'  colspan="6"  width="<?php echo $w1; ?>">Inside UC </th>

                                            <th tyle='text-align:center;' colspan="4" width="<?php echo $w1; ?>">Outside UC</th>

                                            <th tyle='text-align:center;'  rowspan="2" colspan="2" width="<?php echo $w3; ?>">Total Children <br> Vaccinated Inside UC</th>
                                            <th tyle='text-align:center;'  rowspan="2" colspan="2" width="<?php echo $w3; ?>">Total Children <br> Vaccinated Inside + <br> Outside UC </th>

                                            <th tyle='text-align:center;'  colspan="6"  width="<?php echo $w1; ?>">Inside UC </th>

                                            <th tyle='text-align:center;' colspan="4" width="<?php echo $w1; ?>">Outside UC</th>

                                            <th tyle='text-align:center;'  rowspan="2" colspan="2" width="<?php echo $w3; ?>">Total Children <br> Vaccinated Inside UC</th>
                                            <th tyle='text-align:center;'  rowspan="2" colspan="2" width="<?php echo $w3; ?>">Total Children <br> Vaccinated Inside + <br> Outside UC </th>

                                            <th tyle='text-align:center;'  colspan="6"  width="<?php echo $w1; ?>">Inside UC </th>

                                            <th tyle='text-align:center;' colspan="4" width="<?php echo $w1; ?>">Outside UC</th>

                                            <th tyle='text-align:center;'  rowspan="2" colspan="2" width="<?php echo $w3; ?>">Total Children <br> Vaccinated Inside UC</th>
                                            <th tyle='text-align:center;'  rowspan="2" colspan="2" width="<?php echo $w3; ?>">Total Children <br> Vaccinated Inside + <br> Outside UC </th>

                                            <th tyle='text-align:center;'  colspan="6"  width="<?php echo $w1; ?>">Inside UC </th>

                                            <th tyle='text-align:center;' colspan="4" width="<?php echo $w1; ?>">Outside UC</th>

                                            <th tyle='text-align:center;'  rowspan="2" colspan="2" width="<?php echo $w3; ?>">Total Children <br> Vaccinated Inside UC</th>
                                            <th tyle='text-align:center;'  rowspan="2" colspan="2" width="<?php echo $w3; ?>">Total Children <br> Vaccinated Inside + <br> Outside UC </th>

                                        </tr>


                                        <tr>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Outreach</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Defaulter <br> Covered</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Referred by LB</th>




                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Outreach</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Defaulter <br> Covered</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Referred by LB</th>



                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Outreach</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Defaulter <br> Covered</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Referred by LB</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Outreach</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Defaulter <br> Covered</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Referred by LB</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Outreach</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Defaulter <br> Covered</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Referred by LB</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Outreach</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Defaulter <br> Covered</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Referred by LB</th>


                                        </tr>
                                        <tr>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>



                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">N</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">%</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">N</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">%</th>


                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>


                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">N</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">%</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">N</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">%</th>


                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>



                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">N</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">%</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">N</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">%</th>

                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>



                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">N</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">%</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">N</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">%</th>

                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>



                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">N</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">%</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">N</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">%</th>

                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>



                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">N</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">%</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">N</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">%</th>

                                        </tr>
                                        <tr>


                                        </tr>
                                    <?php } else { ?>
                                        <tr>
                                            <th tyle='text-align:center;' colspan="8">Coverage Penta-1(0-11 Months) </th>
                                            <th tyle='text-align:center;' colspan="8" >Coverage Penta-2(0-11 Months)</th>
                                            <th tyle='text-align:center;' colspan="8" >Coverage Penta-3(0-11 Months)</th>
                                            <th tyle='text-align:center;' rowspan="3">Total less than 1 year</th>
                                            <th tyle='text-align:center;' rowspan="3">Total % less than 1 year</th>
                                            <th tyle='text-align:center;' rowspan="3">less than 2 years</th>
                                            <th tyle='text-align:center;'  colspan="8">Coverage Pentavalent-1(12-23 Months)</th>
                                            <th tyle='text-align:center;'  colspan="8">Coverage Pentavalent-2(12-23 Months)</th>
                                            <th tyle='text-align:center;' colspan="8">Coverage Pentavalent-3(12-23 Months)</th>
                                            <th tyle='text-align:center;' rowspan="3">Total less than 2 year</th>
                                            <th tyle='text-align:center;' rowspan="3">Total % less than 2 year</th>
                                            <th tyle='text-align:center;' rowspan="3">Total Overall</th>
                                            <th tyle='text-align:center;' rowspan="3">Total Overall %</th>
                                        </tr>


                                        <tr>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>

                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Referral</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Outreach</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Total</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Coverage(%)</th>


                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>

                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Referral</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Outreach</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Total</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Coverage(%)</th>

                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>

                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Referral</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Outreach</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Total</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Coverage(%)</th>

                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>

                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Referral</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Outreach</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Total</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Coverage(%)</th>

                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>

                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Referral</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Outreach</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Total</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Coverage(%)</th>

                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Fixed </th>

                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Referral</th>
                                            <th tyle='text-align:center;' colspan="2" width="<?php echo $w1; ?>">Outreach</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Total</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Coverage(%)</th>
                                        </tr>
                                        <tr>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>



                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Penta-1</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Penta-1</th>


                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>



                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Penta-2</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Penta-2</th>


                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>



                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Penta-3</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Penta-3</th>


                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>



                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Penta-1</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Penta-1</th>


                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>



                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Penta-2</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Penta-2</th>



                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">M </th>
                                            <th tyle='text-align:center;' width="<?php echo $w2; ?>">F</th>



                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Penta-3</th>
                                            <th tyle='text-align:center;' width="<?php echo $w3; ?>">Penta-3</th>

                                        </tr>
                                        <tr>


                                        </tr>
                                    <?php } ?>
                                </thead>
                                <tbody>
                                    <?php
                                    foreach ($data_arr as $dis_id => $sub_arr) {
                                        ?>
                                        <tr>
                                            <?php
                                            if ($wh_type == 2 && $report_type == 1) {
                                                ?>
                                                <td><?php echo $sub_arr[0]; ?></td>
                                                <td><?php echo $sub_arr[1]; ?></td>
                                                <?php
                                            } else if ($wh_type == 2 && $report_type == 2) {
                                                ?>
                                                <td><?php echo $sub_arr[0]; ?></td>
                                                <td><?php echo $sub_arr[1]; ?></td>
                                                <td><?php echo $sub_arr[2]; ?></td>
                                                <td><?php echo $sub_arr[3]; ?></td>
                                                <?php
                                            } else if ($wh_type == 2 && $report_type == 3) {
                                                ?>
                                                <td><?php echo $sub_arr[0]; ?></td>
                                                <td><?php echo $sub_arr[1]; ?></td>
                                                <td><?php echo $sub_arr[2]; ?></td>
                                                <td><?php echo $sub_arr[3]; ?></td>
                                                <td><?php echo $sub_arr[4]; ?></td>
                                                <?php
                                            } else if ($wh_type == 4 && $report_type == 1) {
                                                ?>
                                                <td><?php echo $sub_arr[0]; ?></td>
                                                <td><?php echo $sub_arr[1]; ?></td>
                                                <?php
                                            } else if ($wh_type == 4 && $report_type == 2) {
                                                ?>
                                                <td><?php echo $sub_arr[0]; ?></td>
                                                <td><?php echo $sub_arr[1]; ?></td>
                                                <td><?php echo $sub_arr[2]; ?></td>
                                                <?php
                                            } else if ($wh_type == 4 && $report_type == 3) {
                                                ?>
                                                <td><?php echo $sub_arr[0]; ?></td>
                                                <td><?php echo $sub_arr[1]; ?></td>
                                                <td><?php echo $sub_arr[2]; ?></td>
                                                <td><?php echo $sub_arr[3]; ?></td>
                                                <?php
                                            }

                                            foreach ($sub_arr as $key => $value) {
                                                if (!isset($sum_arr[$key])) {
                                                    $sum_arr[$key] = 0;
                                                }
                                                $sum_arr[$key] += $value;

                                                if ($wh_type == 2 && $report_type == 1) {
                                                    if ($key > 1) {
                                                        ?><td style="text-align:right;"><?php echo number_format($value); ?></td>

                                                        <?php
                                                    }
                                                } else if ($wh_type == 2 && $report_type == 2) {
                                                    if ($key > 3) {
                                                        ?>
                                                        <td style="text-align:right;"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    }
                                                } else if ($wh_type == 2 && $report_type == 3) {
                                                    if ($key > 4) {
                                                        ?>
                                                        <td style="text-align:right;"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    }
                                                } else if ($wh_type == 4 && $report_type == 1) {
                                                    if ($key > 1) {
                                                        ?>
                                                        <td style="text-align:right;"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    }
                                                } else if ($wh_type == 4 && $report_type == 2) {
                                                    if ($key > 2) {
                                                        ?>
                                                        <td style="text-align:right;"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    }
                                                } else if ($wh_type == 4 && $report_type == 3) {
                                                    if ($key > 3) {
                                                        ?>
                                                        <td style="text-align:right;"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    }
                                                }
                                            }
                                        }
                                        if ($from_sel_year <= '2017' && $sel_prov!=2) {
                                            // To show Total
                                            array_shift($sum_arr);
                                            ?>
                                        <tr>
                                            <?php if ($wh_type == 2 && $report_type == 1) {
                                                ?>
                                                <td></td>
                                                <?php
                                            } else if ($wh_type == 2 && $report_type == 2) {
                                                ?>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            <?php } else if ($wh_type == 2 && $report_type == 3) {
                                                ?>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            <?php } else if ($wh_type == 4 && $report_type == 1) {
                                                ?>
                                                <td></td>
                                            <?php } else if ($wh_type == 4 && $report_type == 2) {
                                                ?>
                                                <td></td>
                                                <td></td>
                                            <?php } else if ($wh_type == 4 && $report_type == 3) {
                                                ?>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            <?php }
                                            ?>
                                            <td style="font-weight:bold">Total</td>
                                            <?php
                                            foreach ($sum_arr as $key => $value) {
                                                if ($wh_type == 2 && $report_type == 1) {
                                                    if ($key == 1) {
                                                        $total_wh = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>

                                                        <?php
                                                    } else if ($key > 1 && $key < 8) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 8) {
                                                        $total_val1 = $value;
                                                        ?>    <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 9) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val1 / $total_wh) * 100) . " %"; ?></td>


                                                    <?php } else if ($key > 9 && $key < 16) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 16) {
                                                        $total_val2 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 17) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val2 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    } else if ($key > 17 && $key < 24) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 24) {
                                                        $total_val3 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 25) {
                                                        ?>  <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val3 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    } else if ($key == 26) {
                                                        $total_val3 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 27) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val3 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key > 27 && $key < 35) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 35) {
                                                        $total_val4 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 36) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val4 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    } else if ($key >= 37 && $key < 44) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 44) {
                                                        $total_val5 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 45) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val5 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    } else if ($key > 45 && $key < 51) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 51) {
                                                        $total_val6 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 52) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val6 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    } else if ($key == 53) {
                                                        $total_val7 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 54) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val7 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    } else if ($key == 55) {
                                                        $total_val8 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($total_val8); ?></td>

                                                    <?php } else if ($key > 55) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val8 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    }
                                                } else if ($wh_type == 2 && $report_type == 2) {
                                                    if ($key == 3) {
                                                        $total_wh = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key > 3 && $key < 10) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 10) {
                                                        $total_val1 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 11) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val11 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key > 11 && $key < 18) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 18) {
                                                        $total_val2 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 19) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val12 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    } else if ($key > 19 && $key < 26) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 26) {
                                                        $total_val3 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 27) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val13 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    } else if ($key == 28) {
                                                        $total_val3 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 29) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val13 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key > 29 && $key < 37) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 37) {
                                                        $total_val4 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 38) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val14 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key >= 39 && $key < 46) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 46) {
                                                        $total_val5 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 47) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val15 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key > 47 && $key < 53) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 53) {
                                                        $total_val6 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 54) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val16 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    } else if ($key == 55) {
                                                        $total_val7 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 56) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val17 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    } else if ($key == 57) {
                                                        $total_val8 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($total_val8); ?></td>

                                                    <?php } else if ($key > 57) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val18 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    }
                                                } else if ($wh_type == 2 && $report_type == 3) {
                                                    if ($key == 4) {
                                                        $total_wh = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key > 4 && $key < 11) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 11) {
                                                        $total_val1 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 12) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val11 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key > 12 && $key < 19) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 19) {
                                                        $total_val2 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 20) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val12 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    } else if ($key > 20 && $key < 27) {
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 27) {
                                                        $total_val3 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 28) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val13 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    } else if ($key == 29) {
                                                        $total_val3 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 30) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val13 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key > 30 && $key < 38) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 38) {
                                                        $total_val4 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 39) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val14 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key >= 40 && $key < 46) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 46) {
                                                        $total_val5 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 47) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val15 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key > 47 && $key < 54) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo $key . number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 54) {
                                                        $total_val6 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 55) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val16 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    } else if ($key == 56) {
                                                        $total_val7 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 57) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val17 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    } else if ($key == 58) {
                                                        $total_val8 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($total_val8); ?></td>

                                                    <?php } else if ($key > 58) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val18 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    }
                                                } else if ($wh_type == 4 && $report_type == 1) {
                                                    if ($key == 1) {
                                                        $total_wh = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($total_wh); ?></td>
                                                    <?php } else if ($key > 1 && $key < 8) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 8) {
                                                        $total_val1 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 9) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val1 / $total_wh) * 100) . " %"; ?></td>

                                                    <?php } else if ($key > 9 && $key < 16) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 16) {
                                                        $total_val2 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 17) {
                                                        ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val2 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key > 17 && $key < 24) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 24) {
                                                        $total_val3 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 25) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val3 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    } else if ($key == 26) {
                                                        $total_val3 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 27) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val3 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key > 27 && $key < 35) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 35) {
                                                        $total_val4 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 36) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val4 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key >= 37 && $key < 44) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 44) {
                                                        $total_val5 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 45) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val5 / $total_wh) * 100) . " %"; ?></td>
                                                    <?php } else if ($key > 45 && $key < 51) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 51) {
                                                        $total_val6 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 52) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val6 / $total_wh) * 100) . " %"; ?></td>
                                                        <?php
                                                    } else if ($key == 53) {
                                                        $total_val7 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 54) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val7 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    } else if ($key == 55) {
                                                        $total_val8 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($total_val8); ?></td>

                                                    <?php } else if ($key > 55) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val8 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    }
                                                } else if ($wh_type == 4 && $report_type == 2) {
                                                    if ($key == 2) {
                                                        $total_wh = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key > 2 && $key < 9) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 9) {
                                                        $total_val1 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 10) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val1 / $total_wh) * 100) . " %"; ?></td>

                                                    <?php } else if ($key > 10 && $key < 17) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 17) {
                                                        $total_val2 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 18) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val2 / $total_wh) * 100) . " %"; ?></td>

                                                    <?php } else if ($key > 18 && $key < 25) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 25) {
                                                        $total_val3 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 26) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val3 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    } else if ($key == 27) {
                                                        $total_val3 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 28) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val3 / $total_wh) * 100) . " %"; ?></td>

                                                    <?php } else if ($key > 28 && $key < 36) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 36) {
                                                        $total_val4 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 37) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val4 / $total_wh) * 100) . " %"; ?></td>

                                                    <?php } else if ($key >= 38 && $key < 45) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 45) {
                                                        $total_val5 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 46) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val5 / $total_wh) * 100) . " %"; ?></td>

                                                    <?php } else if ($key > 46 && $key < 52) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 52) {
                                                        $total_val6 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 53) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val6 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    } else if ($key == 54) {
                                                        $total_val7 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 55) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val7 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    } else if ($key == 56) {
                                                        $total_val8 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($total_val8); ?></td>

                                                    <?php } else if ($key > 56) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val8 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    }
                                                } else if ($wh_type == 4 && $report_type == 3) {
                                                    if ($key == 3) {
                                                        $total_wh = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key > 3 && $key < 10) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 10) {
                                                        $total_val1 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 11) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val1 / $total_wh) * 100) . " %"; ?></td>

                                                    <?php } else if ($key > 11 && $key < 18) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 18) {
                                                        $total_val2 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 19) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val2 / $total_wh) * 100) . " %"; ?></td>

                                                    <?php } else if ($key > 19 && $key < 26) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 26) {
                                                        $total_val3 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 27) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val3 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    } else if ($key == 28) {
                                                        $total_val3 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 29) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val3 / $total_wh) * 100) . " %"; ?></td>

                                                    <?php } else if ($key > 29 && $key < 37) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 37) {
                                                        $total_val4 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 38) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val4 / $total_wh) * 100) . " %"; ?></td>

                                                    <?php } else if ($key >= 39 && $key < 45) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 45) {
                                                        $total_val5 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 46) { ?>

                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val5 / $total_wh) * 100) . " %"; ?></td>

                                                    <?php } else if ($key > 46 && $key < 53) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 53) {
                                                        $total_val6 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 54) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val6 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    } else if ($key == 55) {
                                                        $total_val7 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 56) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val7 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    } else if ($key == 57) {
                                                        $total_val8 = $value;
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo number_format($total_val8); ?></td>

                                                    <?php } else if ($key > 57) { ?>
                                                        <td style="text-align:right; font-weight:bold"><?php echo @round(($total_val8 / $total_wh) * 100) . " %"; ?></td>

                                                        <?php
                                                    }
                                                }
                                            }
                                            ?>
                                        </tr>
                                    <?php } else { ?>
                                        <?php array_shift($sum_arr);
                                        ?>

                                        <tr>
                                            <?php if ($wh_type == 2 && $report_type == 1) {
                                                ?>
                                                <td></td>
                                                <?php
                                            } else if ($wh_type == 2 && $report_type == 2) {
                                                ?>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            <?php } else if ($wh_type == 2 && $report_type == 3) {
                                                ?>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            <?php } else if ($wh_type == 4 && $report_type == 1) {
                                                ?>
                                                <td></td>
                                            <?php } else if ($wh_type == 4 && $report_type == 2) {
                                                ?>
                                                <td></td>
                                                <td></td>
                                            <?php } else if ($wh_type == 4 && $report_type == 3) {
                                                ?>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            <?php }
                                            ?>
                                            <td style="font-weight:bold">Total</td>
                                            <?php
                                            foreach ($sum_arr as $key => $value) {
                                                if ($wh_type == 2 && $report_type == 1) {
                                                    if ($key == 1) {
                                                        $total_wh = $value;
                                                        ?>  <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key > 1 && $key < 12) {
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 12) {
                                                        $total_val1 = $value;
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 13) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val1 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 14) {
                                                        $total_val1 = $value;
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 15) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val1 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 15 && $key < 26) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 26) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 27) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 28) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 29) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 29 && $key < 40) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 40) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 41) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 42) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 43) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 44) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key > 44 && $key < 55) {
                                                            ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 55) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 56) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 57) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 58) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 58 && $key < 69) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 69) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 70) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 71) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 72) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 72 && $key < 83) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 83) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 84) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 85) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 86) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    }
                                                } else if ($wh_type == 2 && $report_type == 2) {
                                                    if ($key == 3) {
                                                        $total_wh = $value;
                                                        ?>  <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key > 3 && $key < 14) {
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 14) {
                                                        $total_val1 = $value;
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 15) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val1 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 16) {
                                                        $total_val1 = $value;
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 17) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val1 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 17 && $key < 28) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 28) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 29) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 30) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 31) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 31 && $key < 42) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 42) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 43) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 44) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 45) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 46) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key > 46 && $key < 56) {
                                                            ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 56) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 57) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 58) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 59) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 59 && $key < 70) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 71) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 72) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 73) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 74) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 74 && $key < 84) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 84) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 85) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 86) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 87) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    }
                                                } else if ($wh_type == 2 && $report_type == 3) {
                                                    if ($key == 4) {
                                                        $total_wh = $value;
                                                        ?>  <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key > 4 && $key < 15) {
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 15) {
                                                        $total_val1 = $value;
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 16) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val1 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 17) {
                                                        $total_val1 = $value;
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 18) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val1 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 18 && $key < 29) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 29) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 30) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 31) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 32) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 32 && $key < 43) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 43) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 44) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 45) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 46) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 47) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key > 47 && $key < 57) {
                                                            ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 57) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 58) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 59) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 60) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 60 && $key < 71) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 71) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 72) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 73) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 74) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 74 && $key < 85) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 85) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 86) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 87) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 88) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    }
                                                } else if ($wh_type == 4 && $report_type == 1) {
                                                    if ($key == 1) {
                                                        $total_wh = $value;
                                                        ?>  <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key > 1 && $key < 12) {
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 12) {
                                                        $total_val1 = $value;
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 13) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val1 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 14) {
                                                        $total_val1 = $value;
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 15) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val1 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 15 && $key < 26) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 26) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 27) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 28) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 29) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 29 && $key < 40) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 40) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 41) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 42) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 43) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 44) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key > 44 && $key < 55) {
                                                            ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 55) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 56) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 57) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 58) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 58 && $key < 69) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 69) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 70) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 71) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 72) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 72 && $key < 83) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 83) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 84) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 85) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 86) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    }
                                                } else if ($wh_type == 4 && $report_type == 2) {
                                                    if ($key == 2) {
                                                        $total_wh = $value;
                                                        ?>  <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key > 2 && $key < 13) {
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 13) {
                                                        $total_val1 = $value;
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 14) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val1 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 15) {
                                                        $total_val1 = $value;
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 16) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val1 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 16 && $key < 27) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 27) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 28) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 29) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 30) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 30 && $key < 41) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 41) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 42) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 43) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 44) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 45) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key > 45 && $key < 56) {
                                                            ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 56) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 57) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 58) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 59) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 59 && $key < 70) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 70) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 71) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 72) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 73) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 73 && $key < 84) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 84) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 85) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 86) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 87) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    }
                                                } else if ($wh_type == 4 && $report_type == 3) {
                                                    if ($key == 3) {
                                                        $total_wh = $value;
                                                        ?>  <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key > 3 && $key < 14) {
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 14) {
                                                        $total_val1 = $value;
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 15) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val1 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 16) {
                                                        $total_val1 = $value;
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 17) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val1 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 17 && $key < 28) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 28) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 29) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 30) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 31) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 31 && $key < 42) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 42) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 43) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 44) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 45) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 46) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key > 46 && $key < 56) {
                                                            ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 56) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 57) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 58) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 59) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 59 && $key < 70) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 70) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 71) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 72) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 73) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key > 73 && $key < 84) {
                                                        ?>   <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 84) {
                                                            $total_val2 = $value;
                                                            ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                    } else if ($key == 85) {
                                                        ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    } else if ($key == 86) {
                                                        $total_val2 = $value;
                                                        ?><td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>    <?php
                                                        } else if ($key == 87) {
                                                            ?> <td style="text-align:right; font-weight:bold"><?php
                                                        echo @round(($total_val2 / $total_wh) * 100) . " %</cell>";
                                                    }
                                                }
                                            }
                                            ?>
                                        </tr>                  


                                    <?php } ?>
                                </tbody>
                            </table></td>
                    </tr>
                    <tr>
                        <td style="padding-top: 10px;" colspan="15"><table cellspacing="0" align="left" id="myTable">
                                <tbody>
                                    <tr>
                                        <td> Total Consumption = Fixed + Outreach </td>
                                    </tr>
                                </tbody>
                            </table></td>
                    </tr>
                </table>

            </div>
        </div>
    </div>

</div>
<script>

    var whType = <?php echo $wh_type; ?>;
    var province = <?php echo $sel_prov; ?>;
    var district = <?php echo $sel_dist; ?>;
    var tehsil = <?php echo $sel_tehsil; ?>;
</script>