<?php
/**
 *  phtml for Central Provincial Warehouse
 */
?>
<?php
$sel_month = $this->month_sel;
$sel_year = $this->year_sel;
$counter = 1;

$sel_stk = $this->in_stk;
$sel_prov = $this->prov_sel;
$sel_dist = $this->in_dist;
$sel_indicator = $this->sel_indicator;
$in_col = $this->in_col;
$in_rg = $this->in_rg;
$in_type = $this->in_type;
$stk_sel = $this->stk_sel;
$start_date = $this->start_date;
$end_date = $this->end_date;
$period = $this->period;
$str_indicator = $this->str_indicator;
$wh_type = $this->wh_type;
$warehouse_id = $this->warehouse_id;
?>


<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $report_title . ' ' . $report_month . ' ' . $sel_year; ?></h3>
        <div class="innerLR">
            <table width="99%">
                <tr>
                    <td colspan="2">
                        <?php
                        echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                        ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?php echo $this->render('inventory-management/reports-header_pri.phtml') ?>
                    </td>
                </tr>


            </table>
            <?php
            /**
             *  phtml for Priority Vaccines Distribution Detail Print
             */
            ?>
            <!-- Content -->
            <style>
                #content_print {
                    margin-left: 50px;
                    width: 624px;
                }
                table.mytable {
                    border: 1px solid grey;
                    font-size: 9pt;
                    width: 100%;
                }
                table.mytable tr td {
                    border: 1px solid grey;
                   
                    padding-left: 5px;
                }
                table.mytable tr th {
                    border: 1px solid grey;
                }
            </style>
            <!-- Content -->

            <style type="text/css" media="print">
                .page{
                    -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
                    filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
                }
                @media print{    
                    #printButt{
                        display: none !important;
                    }
                }
            </style>

            <h5 class="page-title">
                Priority Vaccines Distribution (<?php echo $this->warehouse_name;?>)
            </h5>
            <div class="row">
                <div class="col-md-12">
                    <table class="mytable" cellpadding="2">
                        <tr>
                            <th class="col-md-2 bg-priority-head2">Batch status</th>
                            <th class="col-md-10 bg-priority-head2">Description</th>
                        </tr>
                        <tr>
                            <td class="bg-unusable"><b>Unusable</b></td>
                            <td class="bg-unusable">If VVM stage is 3 or 4 or batch is expired.</td>
                        </tr>
                        <tr>
                            <td class="bg-priority1"><b>Priority 1</b></td>
                            <td class="bg-priority1">If VVM stage is 2 or expiry is less than 3 Months.</td>
                        </tr>
                        <tr>
                            <td class="bg-priority2"><b>Priority 2</b></td>
                            <td class="bg-priority2">If VVM stage is 1 and expiry is more than 3 months and less than 12 months.</td>
                        </tr>
                        <tr>
                            <td class="bg-priority3"><b>Priority 3</b></td>
                            <td class="bg-priority3">If VVM stage is 1 and expiry is more than 12 months.</td>
                        </tr>
                    </table>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12">
                    <?php if ($this->detail_summary == 1) { ?>
                        <table class="mytable" cellpadding="2">
                            <thead>
                                <tr class="bg-priority-head2">
                                    <th>
                                    </th>
                                    <th class="right">
                                        Quantity (Vials)
                                    </th>
                                    <th class="right">
                                        Quantity (Doses)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if ($this->products != false) {
                                    $count = 1;
                                    foreach ($this->products as $row) {
                                        $unusabletotal = 0;
                                        $unusabledoses = 0;
                                        $priority1total = 0;
                                        $priority1doses = 0;
                                        $priority2total = 0;
                                        $priority2doses = 0;
                                        $priority3total = 0;
                                        $priority3doses = 0;

                                        $data4 = $this->priorityVaccinesDistributionSummary($this->warehouse_id, $row['pkId'], 4);
                                        $data1 = $this->priorityVaccinesDistributionSummary($this->warehouse_id, $row['pkId'], 1);
                                        $data2 = $this->priorityVaccinesDistributionSummary($this->warehouse_id, $row['pkId'], 2);
                                        $data3 = $this->priorityVaccinesDistributionSummary($this->warehouse_id, $row['pkId'], 3);
                                        $items = array();
                                        if ($data4 != false) {
                                            foreach ($data4 as $row4) {
                                                if (!in_array($row4['item_name'], $items)) {
                                                    $items[] = $row4['item_name'];
                                                }
                                            }
                                        }
                                        if ($data1 != false) {
                                            foreach ($data1 as $row1) {
                                                if (!in_array($row1['item_name'], $items)) {
                                                    $items[] = $row1['item_name'];
                                                }
                                            }
                                        }
                                        if ($data2 != false) {
                                            foreach ($data2 as $row2) {
                                                if (!in_array($row2['item_name'], $items)) {
                                                    $items[] = $row2['item_name'];
                                                }
                                            }
                                        }
                                        if ($data3 != false) {
                                            foreach ($data3 as $row3) {
                                                if (!in_array($row3['item_name'], $items)) {
                                                    $items[] = $row3['item_name'];
                                                }
                                            }
                                        }
                                        if ($items != false) {
                                            ?>

                                            <tr >
                                                <td colspan="4">
                                                    <?php foreach ($items as $item) { ?>
                                                        <b><?php echo $item; ?></b>
                                                    <?php } ?>
                                                </td>
                                            </tr> 
                                        <?php } ?>
                                        <?php
                                        if ($data4 != false) {
                                            ?>

                                            <?php
                                            foreach ($data4 as $row4) {
                                                ?>
                                                <tr>
                                                    <td>
                                                        Unusable
                                                    </td>

                                                    <td class="right">
                                                        <?php echo number_format($row4['quantity']); ?>
                                                    </td>
                                                    <td class="right">
                                                        <?php echo number_format($row4['doses']); ?>
                                                    </td>
                                                </tr>
                                                <?php
                                                $unusabletotal += $row4['quantity'];
                                                $unusabledoses += $row4['doses'];
                                            }
                                            ?>

                                            <?php
                                        }
                                        $data1 = $this->priorityVaccinesDistributionSummary($this->warehouse_id, $row['pkId'], 1);
                                        if ($data1 != false) {
                                            ?>

                                            <?php
                                            foreach ($data1 as $row1) {
                                                ?>
                                                <tr>
                                                    <td>
                                                        Priority 1
                                                    </td>


                                                    <td class="right">
                                                        <?php echo number_format($row1['quantity']); ?>
                                                    </td>
                                                    <td class="right">
                                                        <?php echo number_format($row1['doses']); ?>
                                                    </td>
                                                </tr>
                                                <?php
                                                $priority1total += $row1['quantity'];
                                                $priority1doses += $row1['doses'];
                                            }
                                            ?>

                                            <?php
                                        }
                                        $data2 = $this->priorityVaccinesDistributionSummary($this->warehouse_id, $row['pkId'], 2);
                                        if ($data2 != false) {
                                            ?>

                                            <?php
                                            foreach ($data2 as $row2) {
                                                ?>
                                                <tr>

                                                    <td>
                                                        Priority 2
                                                    </td>



                                                    <td class="right">
                                                        <?php echo number_format($row2['quantity']); ?>
                                                    </td>
                                                    <td class="right">
                                                        <?php echo number_format($row2['doses']); ?>
                                                    </td>
                                                </tr>
                                                <?php
                                                $priority2total += $row2['quantity'];
                                                $priority2doses += $row2['doses'];
                                            }
                                            ?>

                                            <?php
                                        }

                                        $data3 = $this->priorityVaccinesDistributionSummary($this->warehouse_id, $row['pkId'], 3);
                                        if ($data3 != false) {
                                            ?>

                                            <?php
                                            foreach ($data3 as $row3) {
                                                ?>
                                                <tr>

                                                    <td>
                                                        Priority 3 
                                                    </td>



                                                    <td class="right">
                                                        <?php echo number_format($row3['quantity']); ?>
                                                    </td>
                                                    <td class="right">
                                                        <?php echo number_format($row3['doses']); ?>
                                                    </td>
                                                </tr>
                                                <?php
                                                $priority3total += $row3['quantity'];
                                                $priority3doses += $row3['doses'];
                                            }
                                            ?>

                                            <?php
                                        }
                                        $total_vials = $unusabletotal + $priority1total + $priority2total + $priority3total;
                                        $total_doses = $unusabledoses + $priority1doses + $priority2doses + $priority3doses;
                                        if ($total_vials != 0) {
                                            ?>
                                            <tr>
                                                <th  class="right">
                                                    Total:
                                                </th>
                                                <th class="right">
                                                    <?php echo number_format($total_vials); ?>
                                                </th>
                                                <th class="right">
                                                    <?php echo number_format($total_doses); ?>
                                                </th>
                                            </tr>  <?php
                                                }
                                            }
                                        }
                                        ?>
                            </tbody>
                        </table>
                        <br>
                        <div class="right">
                            <button type="button" id="print" class="btn btn-warning input-sm"><?php echo $this->translate("Print") ?></button>
                        </div>
                    <?php } else {
                        ?>
                        <table class="mytable" id="priority-vaccine-distribution" cellpadding="2">
                            <thead>
                                <tr class="bg-priority-head2">
                                    <th>
                                        Product
                                    </th>
                                    <th>
                                        Batch Number
                                    </th>                    
                                    <th>
                                        Expiry Date
                                    </th>
                                    <th>
                                        VVM
                                    </th>
                                    <th>
                                        Cold room
                                    </th>                        
                                    <th class="right">
                                        Quantity (Vials)
                                    </th>
                                    <th class="right">
                                        Quantity (Doses)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
    <?php
    if ($this->products != false) {
        foreach ($this->products as $row) {
            $unusabletotal = 0;
            $unusabledoses = 0;
            $priority1total = 0;
            $priority1doses = 0;
            $priority2total = 0;
            $priority2doses = 0;
            $priority3total = 0;
            $priority3doses = 0;

            $data4 = $this->priorityVaccinesDistribution($this->warehouse_id, $row['pkId'], 4);
            if ($data4 != false) {
                ?>
                                            <tr>
                                                <td colspan="7">
                                                    <b>Unusable</b>
                                                </td>
                                            </tr>
                <?php
                foreach ($data4 as $row4) {
                    ?>
                                                <tr class="bg-unusable">
                                                    <td>
                                                <?php echo $row4['item_name']; ?>
                                                    </td>
                                                    <td>
                                                        <?php echo $row4['number']; ?>
                                                    </td>
                                                    <td nowrap>
                                                        <?php echo $row4['expiry_date']; ?>
                                                    </td>                            
                                                    <td>
                                                        <?php echo $row4['vvm']; ?>
                                                    </td>
                                                    <td>
                                                        <?php echo $row4['coldroom']; ?>
                                                    </td>
                                                    <td class="right">
                                                        <?php echo number_format($row4['quantity']); ?>
                                                    </td>
                                                    <td class="right">
                                                        <?php echo number_format($row4['doses']); ?>
                                                    </td>
                                                </tr>
                                                        <?php
                                                        $unusabletotal += $row4['quantity'];
                                                        $unusabledoses += $row4['doses'];
                                                    }
                                                    ?>
                                            <tr>
                                                <th colspan="5" class="right">
                                                    Total:
                                                </th>
                                                <th class="right">
                <?php echo number_format($unusabletotal); ?>
                                                </th>
                                                <th class="right">
                                                    <?php echo number_format($unusabledoses); ?>
                                                </th>
                                            </tr>
                                                    <?php
                                                }
                                                $data1 = $this->priorityVaccinesDistribution($this->warehouse_id, $row['pkId'], 1);
                                                if ($data1 != false) {
                                                    ?>
                                            <tr>
                                                <td colspan="7">
                                                    <b>Priority 1</b>
                                                </td>
                                            </tr>
                <?php
                foreach ($data1 as $row1) {
                    ?>
                                                <tr class="bg-priority1">
                                                    <td>
                                                <?php echo $row1['item_name']; ?>
                                                    </td>
                                                    <td>
                                                        <?php echo $row1['number']; ?>
                                                    </td>
                                                    <td nowrap>
                                                        <?php echo $row1['expiry_date']; ?>
                                                    </td>                            
                                                    <td>
                                                        <?php echo $row1['vvm']; ?>
                                                    </td>
                                                    <td>
                                                        <?php echo $row1['coldroom']; ?>
                                                    </td>
                                                    <td class="right">
                                                        <?php echo number_format($row1['quantity']); ?>
                                                    </td>
                                                    <td class="right">
                                                        <?php echo number_format($row1['doses']); ?>
                                                    </td>
                                                </tr>
                                                        <?php
                                                        $priority1total += $row1['quantity'];
                                                        $priority1doses += $row1['doses'];
                                                    }
                                                    ?>
                                            <tr>
                                                <th colspan="5" class="right">
                                                    Total:
                                                </th>
                                                <th class="right">
                <?php echo number_format($priority1total); ?>
                                                </th>
                                                <th class="right">
                                                    <?php echo number_format($priority1doses); ?>
                                                </th>
                                            </tr>
                                                    <?php
                                                }
                                                $data2 = $this->priorityVaccinesDistribution($this->warehouse_id, $row['pkId'], 2);
                                                if ($data2 != false) {
                                                    ?>
                                            <tr>
                                                <td colspan="7">
                                                    <b>Priority 2</b>
                                                </td>
                                            </tr>
                <?php
                foreach ($data2 as $row2) {
                    ?>
                                                <tr class="bg-priority2">
                                                    <td>
                                                <?php echo $row2['item_name']; ?>
                                                    </td>
                                                    <td>
                                                        <?php echo $row2['number']; ?>
                                                    </td>
                                                    <td nowrap>
                                                        <?php echo $row2['expiry_date']; ?>
                                                    </td>                            
                                                    <td>
                                                        <?php echo $row2['vvm']; ?>
                                                    </td>
                                                    <td>
                                                        <?php echo $row2['coldroom']; ?>
                                                    </td>
                                                    <td class="right">
                                                        <?php echo number_format($row2['quantity']); ?>
                                                    </td>
                                                    <td class="right">
                                                        <?php echo number_format($row2['doses']); ?>
                                                    </td>
                                                </tr>
                                                        <?php
                                                        $priority2total += $row2['quantity'];
                                                        $priority2doses += $row2['doses'];
                                                    }
                                                    ?>
                                            <tr>
                                                <th colspan="5" class="right">
                                                    Total:
                                                </th>
                                                <th class="right">
                <?php echo number_format($priority2total); ?>
                                                </th>
                                                <th class="right">
                                                    <?php echo number_format($priority2doses); ?>
                                                </th>
                                            </tr>
                                                    <?php
                                                }
                                                $data3 = $this->priorityVaccinesDistribution($this->warehouse_id, $row['pkId'], 3);
                                                if ($data3 != false) {
                                                    ?>
                                            <tr>
                                                <td colspan="7">
                                                    <b>Priority 3</b>
                                                </td>
                                            </tr>
                <?php
                foreach ($data3 as $row3) {
                    ?>
                                                <tr class="bg-priority3">
                                                    <td>
                                                <?php echo $row3['item_name']; ?>
                                                    </td>
                                                    <td>
                                                        <?php echo $row3['number']; ?>
                                                    </td>
                                                    <td nowrap>
                                                        <?php echo $row3['expiry_date']; ?>
                                                    </td>                            
                                                    <td>
                                                        <?php echo $row3['vvm']; ?>
                                                    </td>
                                                    <td>
                                                        <?php echo $row3['coldroom']; ?>
                                                    </td>
                                                    <td class="right">
                                                        <?php echo number_format($row3['quantity']); ?>
                                                    </td>
                                                    <td class="right">
                                                        <?php echo number_format($row3['doses']); ?>
                                                    </td>
                                                </tr>
                                                        <?php
                                                        $priority3total += $row3['quantity'];
                                                        $priority3doses += $row3['doses'];
                                                    }
                                                    ?>
                                            <tr>
                                                <th colspan="5" class="right">
                                                    Total:
                                                </th>
                                                <th class="right">
                <?php echo number_format($priority3total); ?>
                                                </th>
                                                <th class="right">
                                                    <?php echo number_format($priority3doses); ?>
                                                </th>
                                            </tr>
                                                    <?php
                                                }
                                            }
                                        }
                                        ?>
                            </tbody>
                        </table>
                            <?php } ?>
                </div>
            </div>
            </br>
            </br>


        </div>
    </div>
</div>

<script>

</script>