<?php
/**
 *  phtml for Reported Districts by UC
 */
?>
<?php
$sel_month = $this->month_sel;
$sel_year = $this->year_sel;
$counter = 1;

$sel_stk = $this->in_stk;
$sel_prov = $this->province;
$sel_dist = $this->district;
$sel_tehsil = $this->tehsil;
$wh_type = $this->wh_type;
$sel_indicator = $this->sel_indicator;
$in_col = $this->in_col;
$in_rg = $this->in_rg;
$in_type = $this->in_type;
$stk_sel = $this->stk_sel;
$start_date = $this->start_date;
$end_date = $this->end_date;
$period = $this->period;
$str_indicator = $this->str_indicator;


$wh_prov_sel = $this->wh_prov_sel;

$data_arr = array();

// Headers of the Grid
if ($wh_type == 2) {
    $header = 'District Id,District';
} else {
    $header = 'Tehsil Id,Tehsil/Town';
}
$header1 = '#rspan,#rspan';
$cspan = '';
$width = '*,200';
$ro = 'ro,ro';

foreach ($period as $date) {
    $date_in = $startDate = $endDate = $date->format("Y-m");
    $cspan .= ',#cspan';
    $header .= ',<span>' . $date->format("M-Y") . '</span>';
    $monthArr[] = $date->format("m-Y");
    $width .= ',85,85,85,85,85';
    $ro .= ',ro,ro,ro,ro,ro,ro';
    $header1 .= ',<span>Reporting %</span>';
    $query = $this->reports()->getReportedDistrictsByUcTotal($wh_type, $date_in, $sel_prov, $sel_dist);
}



foreach ($query as $row) {
    $data_arr[$row['districtId']][] = $row['districtName'];
    $count = 1;
    foreach ($period as $date) {
        $data_arr[$row['districtId']][$count] = 0;
        $count++;
    }
    
    
}
$count = 1;
$total_uc = array();

foreach ($period as $date) {
    $date_in = $startDate = $endDate = $date->format("Y-m");

    $query_total = $this->reports()->getReportedDistrictsByUcTotal($wh_type, $date_in, $sel_prov, $sel_dist);
 
    foreach ($query_total as $row) {
        $data_arr[$row['districtId']][$count] = $row['totalWH'];
    }

    $count += 1;
    foreach ($query_total as $row) {

        if ($row['prov_id'] == 4  && $date_in >= '2017-01' && $date_in <= '2017-12' &&  $row['reportingPercentage'] <=75) {

            $data_arr[$row['districtId']][$count] = $row['totalWH'];
        } else if ($row['prov_id'] == 5  && $date_in >= '2017-01' && $date_in <= '2017-11') {
            $data_arr[$row['districtId']][$count] = $row['totalWH'];
        } else if ($row['prov_id'] == 6  && $date_in >= '2017-01' && $date_in <= '2017-12' &&  $row['reportingPercentage'] <=60) {
            $data_arr[$row['districtId']][$count] = $row['totalWH'];
        } 
        else if ($row['districtId'] != 33 && $row['districtId'] != 50 && $row['districtId'] != 53 && $row['districtId'] != 65 && $row['districtId'] != 107 && $row['districtId'] != 123 && $row['districtId'] != 12 && $row['districtId'] != 130 && $row['districtId'] != 151 && $row['districtId'] != 152 && $row['districtId'] != 153 && $row['districtId'] != 154 && $row['districtId'] != 156  && $date_in >= '2017-01' && $date_in <= '2017-11') {
            $data_arr[$row['districtId']][$count] = $row['totalWH'];
        } else {
            $data_arr[$row['districtId']][$count] = $row['reported'];
        }
    }
    $count += 1;

    foreach ($query_total as $row) {
        if ($row['prov_id'] == 4 && $date_in >= '2017-01' && $date_in <= '2017-12' &&  $row['reportingPercentage'] <=75) {

            $data_arr[$row['districtId']][$count] = 100;
        } else if ($row['prov_id'] == 5  && $date_in >= '2017-01' && $date_in <= '2017-11') {
            $data_arr[$row['districtId']][$count] = 100;
        } else if ($row['prov_id'] == 6  && $date_in >= '2017-01' && $date_in <= '2017-12' &&  $row['reportingPercentage'] <=60) {
            $data_arr[$row['districtId']][$count] = 100;
        } else if ($row['districtId'] != 33 && $row['districtId'] != 50 && $row['districtId'] != 53 && $row['districtId'] != 65 && $row['districtId'] != 107 && $row['districtId'] != 123 && $row['districtId'] != 12 && $row['districtId'] != 130 && $row['districtId'] != 151 && $row['districtId'] != 152 && $row['districtId'] != 153 && $row['districtId'] != 154 && $row['districtId'] != 156  && $date_in >= '2017-01' && $date_in <= '2017-11') {
            $data_arr[$row['districtId']][$count] = 100;
        } else {
            $data_arr[$row['districtId']][$count] = $row['reportingPercentage'];
        }
    }
    $count++;
    
}

$s_date = $this->start_date;
$e_date = $this->end_date;

$xml_store = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$xml_store .= "<rows>";

$sum_arr = array();

foreach ($data_arr as $dis_id => $sub_arr) {
    $xml_store .= "<row>";

    $param1 = base64_encode($wh_type . '|' . $sub_arr[0] . '|' . $s_date . '|' . $e_date . '|' . $dis_id . '|' . $sub_arr[1] . '|' . '1');

    $xml_store .= "<cell style=\"text-align:right\">$sub_arr[1]</cell>";

    foreach ($sub_arr as $key => $value) {
        if (!isset($sum_arr[$key])) {
            $sum_arr[$key] = 0;
        }
        $sum_arr[$key] += $value;



        if (!is_numeric($value)) {
            $xml_store .= "<cell><![CDATA[$value]]>^_self</cell>";
        } else {
           if ($key == 3 || $key == 6 || $key == 9 || $key == 12 || $key == 15 || $key == 18  || $key == 21 || $key == 24 || $key == 27 || $key == 30 || $key == 33 || $key == 36) {
            $xml_store .= "<cell style=\"text-align:right\">$value %</cell>";
            } 

        }
    }
    $xml_store .= "</row>";
}


// To show Total
array_shift($sum_arr);

$xml_store .= "<row>";
$xml_store .= "<cell></cell>";
$xml_store .= "<cell style=\"font-weight:bold\">Total</cell>";
//App_Controller_Functions::pr($sum_arr);
foreach ($sum_arr as $key => $value) {
   
   if ($key == 1) {
        $total_uc = $sum_arr[0];
        $reported_uc = $sum_arr[1];
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($reported_uc / $total_uc) * 100) .  " %</cell>";
    }else if ($key ==2) {
        $total_uc = $sum_arr[3];
        $reported_uc = $sum_arr[4];
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($reported_uc / $total_uc) * 100) .  " %</cell>";
    
    }else if ($key ==3) {
        $total_uc = $sum_arr[6];
        $reported_uc = $sum_arr[7];
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($reported_uc / $total_uc) * 100) .  " %</cell>";
    
    }else if ($key ==4) {
        $total_uc = $sum_arr[9];
        $reported_uc = $sum_arr[10];
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($reported_uc / $total_uc) * 100) .  " %</cell>";
    
    }else if ($key ==5) {
        $total_uc = $sum_arr[12];
        $reported_uc = $sum_arr[13];
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($reported_uc / $total_uc) * 100) .  " %</cell>";
    
    }else if ($key ==6) {
        $total_uc = $sum_arr[15];
        $reported_uc = $sum_arr[16];
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($reported_uc / $total_uc) * 100) .  " %</cell>";
    
    }else if ($key ==7) {
        $total_uc = $sum_arr[18];
        $reported_uc = $sum_arr[19];
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($reported_uc / $total_uc) * 100) .  " %</cell>";
    
    }else if ($key ==8) {
        $total_uc = $sum_arr[21];
        $reported_uc = $sum_arr[22];
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($reported_uc / $total_uc) * 100) .  " %</cell>";
    
    }else if ($key ==9) {
        $total_uc = $sum_arr[24];
        $reported_uc = $sum_arr[25];
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($reported_uc / $total_uc) * 100) .  " %</cell>";
    
    }else if ($key ==10) {
        $total_uc = $sum_arr[27];
        $reported_uc = $sum_arr[28];
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($reported_uc / $total_uc) * 100) .  " %</cell>";
    
    }else if ($key ==11) {
        $total_uc = $sum_arr[30];
        $reported_uc = $sum_arr[31];
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($reported_uc / $total_uc) * 100) .  " %</cell>";
    
    }else if ($key ==12) {
        $total_uc = $sum_arr[33];
        $reported_uc = $sum_arr[34];
        $xml_store .= "<cell style=\"text-align:right;font-weight:bold;\">" . @round(($reported_uc / $total_uc) * 100) .  " %</cell>";
    
    }
}

$xml_store .= "</row>";

$xml_store .= "</rows>";
?>

<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $report_title . ' ' . $sel_year; ?></h3>
        <div class="innerLR">
            <table width="99%">
                <tr>
                    <td colspan="2">
<?php
echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?php echo $this->render('inventory-management/reports-header_scaleup.phtml') ?>
                    </td>
                </tr>

                <tr>
                    <td>&nbsp;</td>
                    <td style="text-align:right; padding-bottom:10px;">
                        <img style="cursor:pointer;" src="<?php echo $this->baseUrl(); ?>/images/pdf-32.png" onClick="mygrid.toPDF('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2pdf/server/generate.php');" title="<?php echo $this->translate("Export to PDF"); ?>"/>&nbsp;&nbsp;
                        <img style="cursor:pointer; margin-left:-5px" src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="mygrid.toExcel('<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/grid2excel/server/generate.php');" title="<?php echo $this->translate("Export to Excel"); ?>" />
                    </td>
                </tr>
            </table>

            <table width="99%" cellpadding="0" cellspacing="0">
                <tr>
                    <td>
                        <div id="mygrid_container" style="width:100%; height:910px;">
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<script>
    var mygrid;
    function doInitGrid() {
        mygrid = new dhtmlXGridObject('mygrid_container');
        mygrid.selMultiRows = true;
        mygrid.setImagePath("<?php echo $this->baseUrl(); ?>/common/reports/dhtmlxGrid/dhtmlxGrid/codebase/imgs/");
        //mygrid.setHeader("Province,Consumption,AMC,On Hand,MOS,#cspan");
        mygrid.setHeader(",<div style='text-align:center; font-size:14px; font-weight:bold; font-family:Helvetica'><?php echo $this->report_title . " As on(" . date('F', mktime(0, 0, 0, $this->month_sel)) . '-' . $this->year_sel; ?>)<?php echo $cspan; ?>,#cspan");
        mygrid.attachHeader("<?php echo $header; ?>");
        mygrid.attachHeader("<?php echo $header1; ?>");
        mygrid.setInitWidths("<?php echo $width; ?>");
        //mygrid.setColAlign("left,right,right,right,right,right,right,right,right,right,right,right,right");
        //mygrid.setColSorting("str,int");
        mygrid.setColTypes("<?php echo $ro; ?>");
        mygrid.setColumnHidden(0, true);
        mygrid.enableRowsHover(true, 'onMouseOver');
        mygrid.setSkin("light");
        mygrid.init();
        mygrid.clearAll();
        $('body').append('<textarea id="xml_string" style="display:none;"><?php echo addslashes($xml_store); ?></textarea>');
        mygrid.loadXMLString(document.getElementById('xml_string').value);
    }
    function functionCall(param) {
        var width = 1002;
        var height = 595;
        var x = (screen.width / 2) - (width / 2);
        var y = (screen.height / 2) - (height / 2);
        window.open('reported-uc?param=' + param, '_blank', 'scrollbars=1,width=' + width + ',height=' + height + ',left=' + x + ',top=' + y);
    }

    function showGraph(param) {
        window.open('<?php echo $this->baseUrl(); ?>/reports/graphs/reported-districts?param=' + param, '_blank', 'scrollbars=1,width=950,height=600');
    }

    var whType = <?php echo $wh_type; ?>;
    var province = <?php echo $sel_prov; ?>;
    var district = <?php echo $sel_dist; ?>;
    var tehsil = <?php echo $sel_tehsil; ?>;
</script>
