<?php
/**
 *  phtml for Pentavalent Coverage Detail
 */
?>
<?php
$from_date = $this->from_date;
$to_date = $this->to_date;
$from_sel_month = $this->from_month_sel;
$from_sel_year = $this->from_year_sel;
$year = $this->year_sel;
$month = $this->month_sel;
$sel_prov = $this->prov_sel;
$sel_dist = $this->district_id;
$sel_tehsil = $this->tehsil;
$wh_type = $this->wh_type;
$report_type = $this->report_type;
// Headers of the Grid
?>

<?php
?>

<?php
$sum_arr = array();

$query = $this->reports()->utilizationReport(1, $wh_type, $year, $month, $from_date, $to_date, $sel_prov, $sel_dist, $sel_tehsil, Model_ListDetail::AGE_0_11, 1, 0, 11, $report_type);
$j = 1;
foreach ($query as $row) {
    $location_id = $row['location_id'];
    $data_arr[$location_id][] = $j;


    $data_arr[$location_id][] = $row['tehsil'];
    $data_arr[$location_id][] = $row['ucs'];

    $data_arr[$location_id][] = $row['lbt'];
    $data_arr[$location_id][] = $row['consumption_1_0_11'];
    $consumption_arr[$location_id] = $row['consumption_1_0_11'];
    $data_arr[$location_id][] = $row['consumptionPercentage_1_0_11'];
    $data_arr[$location_id][] = $row['lbt'] - $row['consumption_1_0_11'];
    $total_consumpiton[$location_id][] = $row['consumption_1_0_11'];
    $j++;
}
$query2 = $this->reports()->utilizationReport(3, $wh_type, $year, $month, $from_date, $to_date, $sel_prov, $sel_dist, $sel_tehsil, Model_ListDetail::AGE_0_11, 2, 0, 11, $report_type);


foreach ($query2 as $row) {
    $location_id = $row['location_id'];
    $data_arr[$location_id][] = $row['consumption_1_0_11'];

    $data_arr[$location_id][] = $row['consumptionPercentage_1_0_11'];
    $data_arr[$location_id][] = $row['lbt'] - $row['consumption_1_0_11'];
    $data_arr[$location_id][] = Round((($consumption_arr[$location_id] - $row['consumption_1_0_11']) / $consumption_arr[$location_id]) * 100);

    $data_arr[$location_id][] = 0;
    $total_consumpiton[$location_id][] = $row['consumption_1_0_11'];
}
?>
<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $report_title; ?></h3>
        <h5 style="color: red">
            Note: Please check and provide feedback at support@lmis.gov.pk
        </h5>

        <div class="row">
            <table width="99%">
                <tr>
                    <td colspan="2">
                        <?php echo $this->render('inventory-management/reports-header_analytic.phtml') ?>
                    </td>
                </tr>
            </table>
            <div class="col-md-12 right">

                <img src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="tableToExcel('export', 'sheet 1', '<?php echo $report_title; ?>')" alt="Excel" style="cursor:pointer;" />
            </div>
        </div>
        <div>
            &nbsp; &nbsp; &nbsp;
        </div>
        <div class="row" id="export">
            <style>
                table#myTable{margin-top:0px !important; color: #000;}
                table#myTable{margin-top:20px;border-collapse: collapse;border-spacing: 0; border:1px solid #999;}
                table#myTable tr td{font-size:11px;padding:3px; text-align:left; border:1px solid #999; color: #000;}
                table#myTable tr th{font-size:11px;padding:3px; text-align:center; border:1px solid #999; color: #000;}
                table#myTable tr td.TAR{text-align:right; padding:5px;width:50px !important;}
                .sb1NormalFont {color: #444444; font-size: 11px; font-weight: bold; text-decoration: none;}
                p{margin-bottom:5px; font-size:11px !important; line-height:1 !important; padding:0 !important; color: #000;}
                table#headerTable tr td{ font-size:11px; color: #000;}
                h4{margin:0; color: #000; font-size:14px;}
                h5{margin:15px 0 5px 0; color: #000;}
                h6{margin:0; color: #000; font-size:12px;}
                .right{text-align:right !important;}
                .center{text-align:center !important;}

                /* Print styles */
                @media only print
                {
                    table#myTable{margin-top:0px !important;}
                    table#myTable tr th{font-size:8px;padding:3px !important; text-align:center; border:1px solid #999; color: #000;}
                    table#myTable tr td{font-size:8px;padding:3px !important; text-align:left; border:1px solid #999; color: #000;}
                    #doNotPrint{display: none !important;}
                    h4{margin:0; color: #000;}
                    h5{margin:0; color: #000;}
                    h6{margin:0; color: #000;}
                    p{margin-bottom:5px; font-size:11px !important; line-height:1 !important; padding:0 !important; color: #000;}
                }
            </style>


            <script>
                function printContents() {
                    var w = 900;
                    var h = screen.height;
                    var left = Number((screen.width / 2) - (w / 2));
                    var top = Number((screen.height / 2) - (h / 2));
                    var dispSetting = "toolbar=yes,location=no,directories=yes,menubar=yes,scrollbars=yes,left=" + left + ",top=" + top + ",width=" + w + ",height=" + h;
                    var printingContents = document.getElementById("export").innerHTML;
                    var docprint = window.open("", "", dispSetting);
                    docprint.document.open();
                    docprint.document.write('<html><head>');
                    docprint.document.write('</head><body onLoad="self.print();self.close();"><center>');
                    docprint.document.write(printingContents);
                    docprint.document.write('</center></body></html>');
                    docprint.document.close();
                    docprint.focus();
                }

            </script>
            <div class="row">
                <?php
                $cat11 = 0;
                $cat22 = 0;
                $cat33 = 0;
                $cat44 = 0;
                foreach ($data_arr as $dis_id => $sub_arr) {


                    $penta1_total = $sub_arr[5];
                    $dropout = (($sub_arr[5] - $sub_arr[8]) / $sub_arr[5]) * 100;
                    if ($sub_arr[5] < $sub_arr[8]) {
                        $cat44 += 1;
                    } else {
                        if ($penta1_total >= 80 && $dropout < 10) {
                            $cat11 += 1;
                        } else if ($penta1_total >= 80 && $dropout > 10) {
                            $cat22 += 1;
                        } else if ($penta1_total < 80 && $dropout < 10) {
                            $cat33 += 1;
                        } else if ($penta1_total < 80 && $dropout > 10) {
                            $cat44 += 1;
                        }
                    }
                }
                $total_ucs1 = $sub_arr[0];
                ?>
                <?php $r_ti = $report_title.' at '.$this->loc_name; ?>
                <?php
                $xmlstore = "<chart exportEnabled='1' exportAction='Download' caption='$r_ti' subcaption='' exportFileName=' " . date('Y-m-d H:i:s') . "' yAxisName='Percentage' numberSuffix='%'  formatNumberScale='0' >";
                $cat111 = Round($cat11 / $total_ucs1 * 100);
                $xmlstore .= "<set label='Category-1' color='#008000' value='$cat111' />";
                $cat222 = Round($cat22 / $total_ucs1 * 100);
                $xmlstore .= "<set label='Category-2' color='#FFFF00' value='$cat222' />";
                $cat333 = Round($cat33 / $total_ucs1 * 100);
                $xmlstore .= "<set label='Category-3' color='#FFA500' value='$cat333' />";
                $cat444 = Round($cat44 / $total_ucs1 * 100);
                $xmlstore .= "<set label='Category-4' color='#FF0000' value='$cat444' />";

                $xmlstore .= "</chart>";
                ?>

                <div class="col-md-8">
                    <?php
                    require_once "FusionCharts/Code/PHP/Includes/FusionCharts.php";
                    FC_SetRenderer('javascript');
                    //  exit;
                    echo renderChart($this->baseUrl() . "/FusionCharts/Charts/Pie3D.swf", "", $xmlstore, 'DataEntryStatus', '100%', 250, false, false);
                    ?>
                </div>
            </div>
            <div class="innerLR" style="overflow:auto;">
                <table id="myTable" cellspacing="0" align="center" width="100%">
                    <thead>


                        <tr>
                            <th rowspan="4" width="50">Total Number of Ucs</th>

                        </tr>
                        <tr>

                            <th style='text-align:center; background: green;'  colspan="2">Category-1</th>
                            <th style='text-align:center; background: yellow;' colspan="2">Category-2</th>

                            <th style='text-align:center; background: orange;' colspan="2">Category-3</th>
                            <th style='text-align:center; background: red;'  colspan="2">Category-4</th>
                        </tr>
                        <tr>


                            <th style='text-align:center; background: green;'  colspan="2">Penta-1 Coverage > 80% & Dropout < 10% </th>




                            <th style='text-align:center; background: yellow;' colspan="2">Penta-1 Coverage > 80% & Dropout > 10%</th>



                            <th style='text-align:center; background: orange;' colspan="2">Penta-1 Coverage < 80% & Dropout < 10% </th>




                            <th style='text-align:center; background: red;' colspan="2">Penta-1 Coverage < 80% & Dropout > 10%</th>



                        </tr>
                        <tr>


                            <th style='text-align:center; background: green;'  colspan="1">Total </th>



                            <th style='text-align:center; background: green;' colspan="1">% </th>

                            <th style='text-align:center; background: yellow;' colspan="1">Total </th>



                            <th style='text-align:center; background: yellow;' colspan="1">% </th>
                            <th style='text-align:center; background: orange;' colspan="1">Total </th>



                            <th style='text-align:center; background: orange;' colspan="1">% </th>
                            <th style='text-align:center; background: red;' colspan="1">Total </th>



                            <th style='text-align:center; background: red;' colspan="1">%</th>

                        </tr>
                    </thead>
                    <tbody>
                        <tr>

                            <?php
                            $cat1 = 0;
                            $cat2 = 0;
                            $cat3 = 0;
                            $cat4 = 0;
                            foreach ($data_arr as $dis_id => $sub_arr) {


                                $penta1_total = $sub_arr[5];
                                $dropout = (($sub_arr[5] - $sub_arr[8]) / $sub_arr[5]) * 100;
                                if ($sub_arr[5] < $sub_arr[8]) {
                                    $cat4 += 1;
                                } else {
                                    if ($penta1_total >= 80 && $dropout < 10) {
                                        $cat1 += 1;
                                    } else if ($penta1_total >= 80 && $dropout > 10) {
                                        $cat2 += 1;
                                    } else if ($penta1_total < 80 && $dropout < 10) {
                                        $cat3 += 1;
                                    } else if ($penta1_total < 80 && $dropout > 10) {
                                        $cat4 += 1;
                                    }
                                }

                                foreach ($sub_arr as $key => $value) {



                                    if (!isset($sum_arr[$key])) {
                                        $sum_arr[$key] = 0;
                                    }
                                    $sum_arr[$key] += $value;
                                }
                            }
                            array_shift($sum_arr);
                            ?>
                            <td style="text-align:right; "><?php echo number_format($sub_arr[0]); ?></td>
                            <?php $total_ucs = $sub_arr[0]; ?>


                            <td style="text-align:right; "><?php echo number_format($cat1); ?></td>
                            <td style="text-align:right; "><?php echo Round($cat1 / $total_ucs * 100); ?></td>
                            <td style="text-align:right; "><?php echo number_format($cat2); ?></td>
                            <td style="text-align:right; "><?php echo Round($cat2 / $total_ucs * 100); ?></td>
                            <td style="text-align:right; "><?php echo number_format($cat3); ?></td>
                            <td style="text-align:right; "><?php echo Round($cat3 / $total_ucs * 100); ?></td>
                            <td style="text-align:right; "><?php echo number_format($cat4); ?></td>
                            <td style="text-align:right; "><?php echo Round($cat4 / $total_ucs * 100); ?></td>



                        </tr>

                    </tbody>
                </table>

                <br>

                <table width="100%" >

                    <td align="center"><h4 class="center">
                            <?php echo "'$report_title at  $this->loc_name'" . '<br>' . " for (" . date('F', mktime(0, 0, 0, $this->from_month_sel)) . '-' . $this->from_year_sel . ') to (' . date('F', mktime(0, 0, 0, $this->to_month_sel)) . '-' . $this->to_year_sel; ?>)  (Doses)
                        </h4></td>
                    </tr>
                    <tr>
                        <td style="padding-top: 10px;"><table id="myTable" cellspacing="0" align="center" style="width:100%">
                                <thead>


                                    <tr>
                                        <th rowspan="3" width="50">S.No</th>
                                        <th rowspan="3" width="150">Tehsil/Taluka</th>
                                        <th rowspan="3" width="150">UC</th>
                                        <th rowspan="3" width="80">Target</th>
                                    </tr>
                                    <tr>
                                        <th tyle="text-align:center;" colspan="1">Total </th>

                                        <th style='text-align:center;' colspan="1" >Coverage(%)</th>
                                        <th style='text-align:center;' rowspan="2" >Un Immunized</th>
                                        <th style='text-align:center;' colspan="1">Total</th>
                                        <th style='text-align:center;' colspan="1">Coverage(%)</th>
                                        <th style='text-align:center;' rowspan="2" >Un Immunized</th>
                                        <th style='text-align:center;' colspan="1">Drop Out Rate</th>
                                        <th style='text-align:center;' rowspan="2" >Category</th>
                                    </tr>
                                    <tr>
                                        <th tyle="text-align:center;" colspan="1">Penta-1 </th>
                                        <th tyle="text-align:center;" colspan="1">Penta-1 </th>
                                        <th tyle="text-align:center;" colspan="1">Penta-3 </th>
                                        <th tyle="text-align:center;" colspan="1">Penta-3 </th>
                                        <th tyle="text-align:center;" colspan="1">P1 to P3 </th>


                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    unset($sum_arr);
                                    foreach ($data_arr as $dis_id => $sub_arr) {

                                        $penta1_total = $sub_arr[5];
                                        $penta1_per = $sub_arr[6];
                                        $dropout = (($sub_arr[5] - $sub_arr[8]) / $sub_arr[5]) * 100;
                                        if ($sub_arr[5] < $sub_arr[8]) {
                                            $color1 = 'red';
                                            $category = 'Cat 4';
                                        } else {
                                            if ($penta1_total >= 80 && $dropout < 10) {
                                                $color1 = 'green';
                                                $category = 'Cat 1';
                                            } else if ($penta1_total >= 80 && $dropout > 10) {
                                                $color1 = 'yellow';
                                                $category = 'Cat 2';
                                            } else if ($penta1_total < 80 && $dropout < 10) {
                                                $color1 = 'orange';
                                                $category = 'Cat 3';
                                            } else if ($penta1_total < 80 && $dropout > 10) {
                                                $color1 = 'red';
                                                $category = 'Cat 4';
                                            }
                                        }

                                        if ($penta1_total >= 80) {
                                            $color_penta1 = 'greenyellow';
                                        } else {
                                            $color_penta1 = '';
                                        }
                                        ?>
                                        <tr>
                                            <?php
                                            if ($wh_type == 2 && $report_type == 1) {
                                                ?>
                                                <td><?php echo $sub_arr[0]; ?></td>
                                                <td><?php echo $sub_arr[1]; ?></td>
                                                <?php
                                            } else if ($wh_type == 2 && $report_type == 2) {
                                                ?>
                                                <td><?php echo $sub_arr[0]; ?></td>
                                                <td><?php echo $sub_arr[1]; ?></td>
                                                <td><?php echo $sub_arr[2]; ?></td>
                                                <td><?php echo $sub_arr[3]; ?></td>
                                                <?php
                                            } else if ($wh_type == 4 && $report_type == 1) {
                                                ?>
                                                <td><?php echo $sub_arr[0]; ?></td>
                                                <td><?php echo $sub_arr[1]; ?></td>
                                                <?php
                                            } else if ($wh_type == 4 && $report_type == 2) {
                                                ?>
                                                <td><?php echo $sub_arr[0]; ?></td>
                                                <td><?php echo $sub_arr[1]; ?></td>
                                                <td><?php echo $sub_arr[2]; ?></td>
                                                <?php
                                            }

                                            foreach ($sub_arr as $key => $value) {
                                                if (!isset($sum_arr[$key])) {
                                                    $sum_arr[$key] = 0;
                                                }
                                                $sum_arr[$key] += $value;

                                                if ($wh_type == 2 && $report_type == 1) {
                                                    if ($key > 1) {
                                                        ?><td style="text-align:right;"><?php echo number_format($value); ?></td>

                                                        <?php
                                                    }
                                                } else if ($wh_type == 2 && $report_type == 2) {
                                                    if ($key > 3) {
                                                        ?>
                                                        <td style="text-align:right;"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    }
                                                } else if ($wh_type == 4 && $report_type == 1) {
                                                    if ($key > 1) {
                                                        ?>
                                                        <td style="text-align:right;"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    }
                                                } else if ($wh_type == 4 && $report_type == 2) {
                                                    if ($key == 3) {
                                                        ?>
                                                        <td style="text-align:right;"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 4) {
                                                        ?>
                                                        <td style="text-align:right;"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 5) {
                                                        ?>
                                                        <td style="text-align:right;background: <?php echo $color_penta1; ?>"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key > 5 && $key < 10) {
                                                        ?>
                                                        <td style="text-align:right;"><?php echo number_format($value); ?></td>
                                                        <?php
                                                    } else if ($key == 10) {
                                                        ?>
                                                        <td style="text-align:right; background: <?php echo $color1; ?>"><?php echo number_format($value); ?></td>
                                                    <?php } else if ($key == 11) {
                                                        ?>
                                                        <td style="text-align:right; "><?php echo $category; ?></td>
                                                        <?php
                                                    }
                                                }
                                            }
                                        }

                                        // To show Total
                                        array_shift($sum_arr);
                                        ?>
                                    <tr>
                                        <?php if ($wh_type == 2 && $report_type == 1) {
                                            ?>
                                            <td></td>
                                            <?php
                                        } else if ($wh_type == 2 && $report_type == 2) {
                                            ?>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        <?php } else if ($wh_type == 4 && $report_type == 1) {
                                            ?>
                                            <td></td>
                                        <?php } else if ($wh_type == 4 && $report_type == 2) {
                                            ?>
                                            <td></td>
                                            <td></td>
                                        <?php }
                                        ?>
                                        <td style="font-weight:bold">Total</td>
                                        <?php
                                        foreach ($sum_arr as $key => $value) {

                                            if ($key == 2) {
                                                $total_target = $value;
                                                ?>
                                                <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                <?php
                                            } else if ($key == 3) {
                                                $total_wh = $value
                                                ?> 
                                                <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>


                                                <?php
                                            } else if ($key == 4) {

                                                $toal_penta1 = Round(($total_wh / $total_target) * 100);
                                                ?>
                                                <td style="text-align:right; font-weight:bold"><?php echo Round(($total_wh / $total_target) * 100); ?></td>
                                                <?php
                                            } else if ($key == 5) {
                                                $total_wh1 = $value;
                                                ?>
                                                <td style="text-align:right; font-weight:bold"><?php echo number_format($total_target - $total_wh); ?></td>
                                                <?php
                                            } else if ($key == 6) {
                                                $total_wh1 = $value;
                                                ?>
                                                <td style="text-align:right; font-weight:bold"><?php echo number_format($value); ?></td>
                                                <?php
                                            } else if ($key == 7) {
                                                ?>
                                                <td style="text-align:right; font-weight:bold"><?php echo Round(($total_wh1 / $total_target) * 100); ?></td>
                                                <?php
                                            } else if ($key == 8) {
                                                ?>
                                                <td style="text-align:right; font-weight:bold"><?php echo number_format($total_target - $total_wh1); ?></td>
                                                <?php
                                            } else if ($key == 9) {
                                                $total_dropout = (($total_wh - $total_wh1) / $total_wh) * 100;

                                                if ($toal_penta1 >= 80 && $total_dropout < 10) {
                                                    $color_t = 'green';
                                                } else if ($toal_penta1 >= 80 && $total_dropout > 10) {
                                                    $color_t = 'yellow';
                                                } else if ($toal_penta1 < 80 && $total_dropout < 10) {
                                                    $color_t = 'orange';
                                                } else if ($toal_penta1 < 80 && $total_dropout > 10) {
                                                    $color_t = 'red';
                                                }
                                                ?>
                                                <td style="text-align:right; font-weight:bold; background-color:<?php echo $color_t; ?> "><?php echo number_format((($total_wh - $total_wh1) / $total_wh) * 100); ?></td>
                                                <?php
                                            }
                                        }
                                        ?>
                                    </tr>
                                </tbody>
                            </table></td>
                    </tr>

                </table>

            </div>
        </div>
    </div>

    <script>

        var whType = <?php echo $wh_type; ?>;
        var province = <?php echo $sel_prov; ?>;
        var district = <?php echo $sel_dist; ?>;
        var tehsil = <?php echo $sel_tehsil; ?>;
    </script>