<?php
/**
*  phtml for Sufficient Report
*/

/**
* Sufficient Report
*/
?>
<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">
            Health Facility Types
        </h3>
       
        <?php if (count($this->result) > 0) { ?>
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-striped table-bordered table-condensed" id="stkledger">
                        <thead>
                            <tr>
                                <th width="5%">S.No</th>
                                <th class="col-md-2">Health Facility Type</th>
                                <th class="col-md-2" style="text-align: right">Count</th>
                                  </tr>
                        </thead>
                        <tbody>
                            <?php
                            $count = 1;
                            foreach ($this->result as $row) {
                               
                                ?>
                                <tr>
                                    <td><?php echo $count; ?></td>
                                    <td><?php echo $row['warehouse_type_name']; ?></td>
                                    <td class="right"><?php echo number_format($row['total']); ?></td>
                                   </tr>
                                <?php
                                $count++;
                                //}
                            }
                            ?>

                        </tbody>
                    </table>
                </div>
            </div>
        <?php } else { ?>
            <div class="row">
                <div class="col-md-12">
                    <h4>Transactions not found</h4>
                </div>
            </div>
        <?php } ?>
       
    </div>
</div>