<?php
/**
 *  phtml for Index
 */
?>
<!-- BEGIN CONTAINER -->
<div class="page-content-wrapper">
    <div class="page-content">
            <div class="row">
                <div class="widget" id="printing">                            
                    <div class="widget-head">
                        <h3 class="heading">Pivot Table - Test run</h3>
                    </div>
                    <div class="widget-body">
                        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.css">

                        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
                        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
                        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
                        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
                        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.1.2/papaparse.min.js"></script>
                        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.js"></script>

                        <!-- PivotTable.js libs from dist -->
                        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/pivot/pivot.css">
                        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/pivot/pivot.js"></script>
                        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/pivot/d3_renderers.js"></script>
                        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/pivot/c3_renderers.js"></script>
                        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/pivot/export_renderers.js"></script>

                        <style>
                            .node {
                                border: solid 1px white;
                                font: 10px sans-serif;
                                line-height: 12px;
                                overflow: hidden;
                                position: absolute;
                                text-indent: 2px;
                            }
                            .c3-line, .c3-focused {stroke-width: 3px !important;}
                            .c3-bar {stroke: white !important; stroke-width: 1;}
                            .c3 text { font-size: 12px; color: grey;}
                            .tick line {stroke: white;}
                            .c3-axis path {stroke: grey;}
                            .c3-circle { opacity: 1 !important; }
                            .c3-xgrid-focus {visibility: hidden !important;}
                        </style>
                        </head>
                        <body class="whiteborder">
                            <script type="text/javascript">
                                $(function () {
                                    var renderers = $.extend(
                                            $.pivotUtilities.renderers,
                                            $.pivotUtilities.c3_renderers,
                                            $.pivotUtilities.d3_renderers,
                                            $.pivotUtilities.export_renderers
                                            );

                                    var parseAndPivot = function (f) {
                                        $("#output").html("<p align='center' style='color:grey;'><img src='<?php echo $this->baseUrl(); ?>/images/ajax-loader.gif'><br>Loading data...</p>")
                                        $.getJSON("<?php echo $this->baseUrl(); ?>/pivot/cons_summary.json", function (mps) {
                                            $("#output").pivotUI(
                                                    mps,
                                                    {
                                                        renderers: renderers,
                                                        //rows: ["Province","District"],
                                                        //cols: ["Product"]
                                                    },
                                                    true
                                                    );
                                        });
                                    };

                                    parseAndPivot();
                                });
                            </script>
                            <div id="output" style="margin: 10px;"></div>


                    </div>
                </div>
            </div>
        </div>
    </div>