<?php
/**
 *  phtml for Index
 */
?>
<!-- BEGIN CONTAINER -->
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="widget" id="printing">
                <div class="widget-head">
                    <h3 class="heading">Microsoft Power BI</h3>
                </div>
                <div class="widget-body">
                    <iframe width="100%" height="800" src="https://app.powerbi.com/view?r=eyJrIjoiY2ViZDhiYTYtMGFjMi00ZTNiLWIwYjAtNjgxNjdiNmU2MTE1IiwidCI6IjdjMWYyNGE2LTdkMzktNDUyYy04MjM3LTA3MjZlM2IxOWE3MyIsImMiOjF9" frameborder="0" allowFullScreen="true"></iframe>
                </div>
            </div>
        </div>
    </div>
</div>