<?php
//$login_id1 = Zend_Registry::get('login_log_id');
//$login_id2 = Zend_Registry::get('login_log_last_id');

$isUpdatable = Zend_Registry::get('isupdatable');
if ($isUpdatable == 'Yes') {

    $sysusr_name = Zend_Registry::get('username');
    $sysusr_cell = Zend_Registry::get('cellno');
    $sysusr_deg = Zend_Registry::get('designation');
    $sysusr_dept = Zend_Registry::get('department');
    $sysusr_email = Zend_Registry::get('email');
    ?>
    <form action="" method="post" id="survey" name="survey" onsubmit="return ValidateForm();">
        <!-- Modal -->
        <div id="myModal" class="modal fade col-md-6 center-block" style="margin-top: 20px;" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header" style="background-color:#F4F4F4;">
                <h4 id="myModalLabel"><b>Please update your contact information! It's mandatory.</b></h4>
            </div>
            <div class="modal-body" style="background-color:white;">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">

                            <label class="control-label" for="name">
                                Name
                            </label>
                            <input class="form-control" tabindex="1"  type="text" name="name"  id="name" required value="<?php
                            echo $sysusr_name;
                            ?>">

                            <?php if (!empty($row)) { ?>
                                <input class="form-control"  type="hidden" name="feedback_id"  id="feedback_id" value="<?php
                                if (!empty($row)) {
                                    echo $row['pk_id'];
                                }
                                ?>" > <?php } ?>

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label" for="CELL NUMBER">
                                Cell number (Format: 923XXXXXXXXX)
                            </label>
                            <input class="form-control" tabindex="2" type="text" name="cellnumber" id="cellnumber" required value="<?php
                            echo $sysusr_cell;
                            ?>">

                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label" for="cnic">
                                Designation
                            </label>
                            <input class="form-control" tabindex="3" type="text" name="office" required value="<?php
                            echo $sysusr_deg;
                            ?>">

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label" for="cnic">
                                Department
                            </label>
                            <input class="form-control" tabindex="4" type="text" name="department" required value="<?php
                            echo $sysusr_dept;
                            ?>">

                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label" for="email">
                                Email
                            </label>
                            <input class="form-control" type="email" tabindex="5" name="email" id="email"  required value="<?php
                            echo $sysusr_email;
                            ?>">

                        </div>
                    </div>
                    <!--            <div class="col-md-5">
                                    <div class="form-group">
                                    </div>
                                </div>
                    -->
                </div>

            </div>
            <div class="modal-footer" style="background-color:#F4F4F4;">
                <?php
                //if ($_SESSION['e'] == 'contact') {
                ?>
    <!--                <span style="color: red;">Thanks for updating your contact information! &nbsp;&nbsp;&nbsp;&nbsp;</span>
                    <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
                    <script>
                        setTimeout(function () {
                            $('#myModal').modal('hide');
                        }, 3000);
                    </script>-->
                <?php
                //}
                ?>
                <button type = "submit" id = "submit" name = "submit" value = "contact" class = "btn btn-primary">Update</button>
            </div>
        </div>
    </form>

    <script>
        $(function () {
            $('#myModal').modal({
                backdrop: 'static',
                keyboard: false
            });

            $("#survey").submit(function (event) {
                var validform = ValidateForm();
                event.preventDefault();

                var url = "index/update-profile";
                if (validform) {
                    $.ajax({
                        type: "POST",
                        url: appName + '/' + url,
                        data: $('form#survey').serialize(),
                        dataType: 'html',
                        success: function (data) {
                            if (data == 'success') {
                                location.reload();
                                $('#myModal').modal('hide');
                            }
                        }
                    });
                }
            });
        });

        function ValidateForm() {
            var email = document.getElementById('email').value;
            var cellnumber = document.getElementById('cellnumber').value;

            if (ValidateEmail(email)) {
                if (validatePhone(cellnumber)) {
                    return true;
                }
            }
            return false;
        }
        function ValidateEmail(mail) {
            if (!(/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(mail))) {
                alert("You have entered an invalid email address!");
                document.getElementById('email').focus();
                return false;
            }
            return true;
        }
        function validatePhone(phone) {
            var error = "";
            var stripped = phone.replace(/[\(\)\.\-\ ]/g, '');

            if (stripped == "") {
                error = "You didn't enter a phone number.";
            } else if (isNaN(parseInt(stripped))) {
                phone = "";
                error = "The phone number contains illegal characters.";
            } else if (!(stripped.length == 12)) {
                phone = "";
                error = "The phone number is the wrong length. Make sure that country code is included without zero.\n";
            }

            if (error != "") {
                alert(error);
                document.getElementById('cellnumber').focus();
                return false;
            }

            return true;
        }
    </script>
    <?php
} else if ($isUpdatable == 'Verify') {
    $sysusr_email = Zend_Registry::get('email');
    $user_id = Zend_Registry::get('userID');
    ?>
    <!-- Modal -->
    <div id="myModal" class="modal fade col-md-6 center-block" style="margin-top: 20px;" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header" style="background-color:#F4F4F4;">
            <h3 id="myModalLabel"><b class="red">Verify your email address</b></h3>
        </div>
        <div class="modal-body" style="background-color:white;">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <p>Thanks for updating your contact information!</p>
                        <p>We now need to verify your email address. We've sent an email to <?php echo $sysusr_email; ?> to verify your address. Please click the link in that email to continue.</p>

                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer" style="background-color:#F4F4F4;">
            <a id="delink-link">Need to resend the email, change your address, or get help?</a>
        </div>
    </div>

    <script>
        $(function () {
            $('#myModal').modal({
                backdrop: 'static',
                keyboard: false
            });

            $("#delink-link").click(function (e) {
                e.preventDefault();

                var url = "index/delink";
                $.ajax({
                    type: "POST",
                    url: appName + '/' + url,
                    data: {id: '<?php echo $user_id; ?>', e: '<?php echo $sysusr_email; ?>'},
                    dataType: 'html',
                    success: function (data) {
                        if (data == 'success') {
                            location.reload();
                            $('#myModal').modal('hide');
                        }
                    }
                });
            });
        });
    </script>
    <?php
}
?>