<?php
/**
 *  Layout for Header Doc.
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9"> <![endif]-->
<!--[if gt IE 8]> <html class="ie gt-ie8"> <![endif]-->
<!--[if !IE]><!--><html><!-- <![endif]-->
    <head>
        <meta charset="UTF-8" />
        <?php echo $this->headTitle('Pakistan Logistics Management Information System'); ?>

        <!-- Meta -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="title" content="<?php echo Zend_Registry::get('pageTitle'); ?>">
        <meta name="description" content="<?php echo Zend_Registry::get('metaDescription'); ?>">

        <link href="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/global/css/fonts/custom.css" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/global/css/components.css" rel="stylesheet" type="text/css"/>

        <!-- Glyphicons Font Icons -->
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/css/glyphicons.css" rel="stylesheet" />
        <!--[if !IE]>
        <!-- Column Filter Widgets Css -->
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/css/ColumnFilterWidgets.css" rel="stylesheet" />
        <!-- PrettyPhoto -->
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/gallery/prettyphoto/css/prettyPhoto.css" rel="stylesheet" />
        <!-- DateTimePicker Plugin -->
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/forms/bootstrap-datetimepicker/css/datetimepicker.css" rel="stylesheet" />
        <!-- JQueryUI -->
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/jquery-ui/css/smoothness/jquery-ui-1.9.2.custom.min.css" rel="stylesheet" />
        <!--[endif]>
        <!-- Main Theme Stylesheet :: CSS -->
        <!-- Notyfy Notifications Plugin -->
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/notifications/notyfy/jquery.notyfy.css" rel="stylesheet" />
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/notifications/notyfy/themes/default.css" rel="stylesheet" />

        <!-- BEGIN PAGE LEVEL STYLES -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/common/assets/plugins/select2/select2.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/common/assets/plugins/select2/select2-metronic.css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css"/>
        <!-- END PAGE LEVEL STYLES -->

        <link href="<?php echo $this->baseUrl(); ?>/common/theme/css/style-light.css?1369414385" rel="stylesheet" />
        <!--        <link href="--><?php ////echo $this->baseUrl();                         ?><!--<!--/common/theme/css/style-green.css" rel="stylesheet" />-->
        <!-- LESS.js Library
        <script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/less.min.js"></script>-->
        <!--[if !IE]>
        <link href="<?php echo $this->baseUrl(); ?>/common/theme/css/google-fonts.css" rel="stylesheet" />

        <!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
        <!--        <link href="--><?php //echo $this->baseUrl();                        ?><!--/common/assets/plugins/gritter/css/jquery.gritter.css" rel="stylesheet" type="text/css"/>-->
        <!--[endif]>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css"/>
        <!--        <link href="--><?php //echo $this->baseUrl();                        ?><!--/common/assets/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css"/>-->
        <!--        <link href="--><?php //echo $this->baseUrl();                        ?><!--/common/assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css"/>-->
        <!-- END PAGE LEVEL PLUGIN STYLES -->

        <!-- BEGIN THEME STYLES -->
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/style.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/plugins.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/pages/tasks.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/admin/layout/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/css/print.css" rel="stylesheet" type="text/css" media="print"/>
        <link href="<?php echo $this->baseUrl(); ?>/common/assets/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>

        <!-- BEGIN PAGE LEVEL STYLES -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/jquery-notific8/jquery.notific8.min.css"/>
        <!-- END PAGE LEVEL STYLES -->
        <style>
            .page-content{
                margin-left: 0;
                margin-top: 0;
            }
        </style>
        <!--[if lt IE 9]>
        <script src="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/respond.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/excanvas.min.js"></script>
        <!--<link href="<?php echo $this->baseUrl(); ?>/common/assets/global/css/ie8.css" rel="stylesheet" type="text/css" />-->
        <!--[endif]-->

        <!-- Fusion Charts -->
        <!-- JQuery-->
        <script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/jquery.min.js"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/FusionCharts/Charts/fusioncharts.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/FusionCharts/Charts/themes/fusioncharts.theme.fint.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/FusionCharts/Charts/themes/fusioncharts.theme.carbon.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/FusionCharts/Charts/themes/fusioncharts.theme.ocean.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/FusionCharts/Charts/themes/fusioncharts.theme.zune.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl(); ?>/FusionCharts/Code/assets/ui/js/lib.js"></script>

        <link href="<?php echo $this->baseUrl(); ?>/js/OpenLayers-2.13/theme/default/style.css" rel="stylesheet" />
        <!--<script src="<?php echo $this->baseUrl(); ?>/js/OpenLayers-2.13/OpenLayers.js"></script>-->

        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body class="page-header-fixed">
        <div class="page-container">
            <!-- Sidebar menu & content wrapper -->

<?php echo $this->layout()->content; ?>
<!-- // Main Container Fluid END -->
<!-- JQuery-->
<!--<![if !IE]>
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/jquery.min.js"></script>
<![endif]-->

<!-- JQueryUI-->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/jquery-ui/js/jquery-ui-1.9.2.custom.min.js"></script>
<!-- JQueryUI Touch Punch -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/forms/jquery-validation/dist/jquery.validate.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/forms/jquery-validation/dist/additional-methods.js"></script>
<!-- small hack that enables the use of touch events on sites using the jQuery UI user interface library -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
<!-- Modernizr -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/modernizr.js"></script>
<!-- Bootstrap
<script src="<?php echo $this->baseUrl(); ?>/common/bootstrap/js/bootstrap.min.js"></script>-->
<!-- SlimScroll Plugin -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/other/jquery-slimScroll/jquery.slimscroll.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/forms/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
<!-- Tables Demo Script -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/demo/tables.js"></script>
<!-- Common Demo Script -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/demo/common.js?1369414385"></script>
<!-- PrettyPhoto -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/gallery/prettyphoto/js/jquery.prettyPhoto.js"></script>
<!-- DataTables Tables Plugin -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/tables/DataTables/media/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/tables/DataTables/media/js/DT_bootstrap.js"></script>
<!-- <script src="<?php echo $this->baseUrl(); ?>/plmis_js/jquery.price_format.1.8.min.js"></script> -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/notifications/notyfy/jquery.notyfy.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.price_format.1.8.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.inlineEdit.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.mask.min.js"></script>


<!-- Column Filter Widget -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/demo/ColumnFilterWidgets.js"></script>
<!-- Column Table Tools -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/tables/DataTables/extras/TableTools/media/js/TableTools.js"></script>
<!-- Column Table Tools min -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/tables/DataTables/extras/TableTools/media/js/TableTools.min.js"></script>
<!-- Column Table Tools zero Clipboard -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/tables/DataTables/extras/TableTools/media/js/ZeroClipboard.js"></script>
<!-- jQuery cookie plugin -->
<script src="<?php echo $this->baseUrl(); ?>/common/theme/scripts/plugins/system/jquery.cookie.js"></script>

<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->

<!-- jQuery 1.10.2
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>-->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip-->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->

<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery.pulsate.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap-daterangepicker/moment.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
<!--<script src="<?php //echo $this->baseUrl();  ?>/common/assets/plugins/gritter/js/jquery.gritter.js" type="text/javascript"></script> -->


<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/data-tables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/data-tables/DT_bootstrap.js"></script>

<!-- END PAGE LEVEL PLUGINS -->


<!-- IMPORTANT! fullcalendar depends on jquery-ui-1.10.3.custom.min.js for drag & drop support -->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/global/plugins/jquery-notific8/jquery.notific8.min.js"></script>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/scripts/core/app.js" type="text/javascript"></script>
<!-- -->
<script src="<?php echo $this->baseUrl(); ?>/common/assets/scripts/custom/date-uk.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/scripts/custom/table-advanced.js"></script>

<script src="<?php echo $this->baseUrl(); ?>/common/assets/global/scripts/metronic.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/scripts/custom/index.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/scripts/custom/tasks.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/common/assets/admin/pages/scripts/ui-notific8.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery.floatThead.min.js"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
    jQuery(document).ready(function () {
        App.init(); // initlayout and core plugins
        Index.init();
        Metronic.init();
        Index.initCalendar(); // init index page's custom scripts
        Index.initCharts(); // init index page's custom scripts
        Index.initChat();
        Index.initMiniCharts();
        Index.initDashboardDaterange();
        Index.initIntro();
        Tasks.initDashboardWidget();
        TableAdvanced.init();
        UINotific8.init();
    });
</script>
<!-- END JAVASCRIPTS -->

<?php echo $this->inlineScript(); ?>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-48587374-1', 'auto');
  ga('send', 'pageview');
</script>

</body>
</html>