<?php
/**
 *  phtml for Ajax Edit
 */
?>
<div class="row">
    <?php $this->locationsEditCombo($office_term = null, $population = null, $this->warehouse_id, $this->role_id); ?>

</div>
<div class="row">
    <div class="col-md-4">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Type"); ?></label>
            <div class="controls">
                <?php echo $this->form->location_type_id_update; ?>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Location Name"); ?></label>
            <div class="controls">
                <?php echo $this->form->location_name_update; ?>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Ccm Code"); ?></label>
            <div class="controls">
                <?php echo $this->form->ccm_location_id_update; ?>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="control-group ">
            <label class="control-label" ><?php echo $this->translate("Population"); ?></label>
            <div class="controls">
                <?php echo $this->form->population_update; ?>
            </div>
        </div>
    </div>
</div>

<?php echo $this->form->location_id; ?>
<?php echo $this->form->location_type; ?>
<?php echo $this->form->province_id_edit; ?>
<?php echo $this->form->district_id_edit; ?> 
<?php echo $this->form->parent_id_edit; ?>
<?php echo $this->form->location_type_id_update_hidden; ?>
  <input type="hidden" name="hdn_warehouse_id" id="hdn_warehouse_id" value="<?php echo $this->warehouse_id; ?>">
 <input type="hidden" name="hdn_role_id" id="hdn_role_id" value="<?php echo $this->role_id; ?>">