<?php
/**
 *  phtml for BCG Coverage Detail
 */
error_reporting(0);
?>
<?php
$from_sel_month = $this->from_month_sel;
$from_sel_year = $this->from_year_sel;
$year = $this->year_sel;
$month = $this->month_sel;
$sel_prov = $this->prov_sel;
$sel_dist = $this->district_id;
$sel_tehsil = $this->tehsil;
$wh_type = $this->wh_type;
$province = $this->prov_sel;
$report_type = $this->report_type;
$sel_item = $this->sel_item;
$province_sel = $this->wh_prov_sel;


//echo $from_sel_month."<br>";
//echo $from_sel_year."<br>";
//echo $year."<br>";
//echo $month."<br>";
//echo $sel_prov."<br>";
//echo $sel_dist."<br>";
//echo $sel_tehsil."<br>";
//echo $wh_type."<br>";
//echo $province."<br>";
//echo $report_type."<br>";
//echo $sel_item."<br>";
//exit;

$sum_arr = array();


if ($sel_item == 'all' && $wh_type == '4') {
    $query_d_1 = $this->wastageReports()->antigenWiseCoverageReport(6, 1, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);
    $j = 1;


    foreach ($query_d_1 as $row) {

        $location_id = $row['location_id'];
        $data_arr[$location_id][] = $j;


        $data_arr[$location_id][] = $row['location_name'];





        $j++;
    }

    $query_0 = $this->wastageReports()->antigenWiseCoverageReport(6, 1, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_0 as $row) {

        $location_id = $row['location_id'];

        $data_arr[$location_id][] = Round($row['target'] / $row['consumption'] * 100, 2);
    }
    $query_1 = $this->wastageReports()->antigenWiseCoverageReport(43, 1, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);
    foreach ($query_1 as $row) {

        $location_id = $row['location_id'];

        $data_arr[$location_id][] = Round($row['target'] / $row['consumption'] * 100, 2);
    }

    $query_5 = $this->wastageReports()->antigenWiseCoverageReport(40, 1, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_5 as $row) {

        $location_id = $row['location_id'];

        $data_arr[$location_id][] = Round($row['target'] / $row['consumption'] * 100, 2);
    }





    $query_57 = $this->wastageReports()->antigenWiseCoverageReport(7, 1, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_57 as $row) {

        $location_id = $row['location_id'];



        $data_arr[$location_id][] = Round($row['target'] / $row['consumption'] * 100, 2);
    }

    $query_67 = $this->wastageReports()->antigenWiseCoverageReport(8, 2, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_67 as $row) {

        $location_id = $row['location_id'];


        $data_arr[$location_id][] = Round($row['target'] / $row['consumption'] * 100, 2);
    }



    $query_7 = $this->wastageReports()->antigenWiseCoverageReport(9, 1, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_7 as $row) {

        $location_id = $row['location_id'];


        $data_arr[$location_id][] = Round($row['target'] / $row['consumption'] * 100, 2);
    }
    $query_8 = $this->wastageReports()->antigenWiseCoverageReport(12, 2, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_8 as $row) {

        $location_id = $row['location_id'];


        $data_arr[$location_id][] = Round($row['target'] / $row['consumption'] * 100, 2);
    }

    $query_9 = $this->wastageReports()->antigenWiseCoverageReport(46, 2, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_9 as $row) {

        $location_id = $row['location_id'];


        $data_arr[$location_id][] = Round($row['target'] / $row['consumption'] * 100, 2);
    }


  

    $query_01 = $this->wastageReports()->wTotal(6, 1, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_01 as $row) {

        $location_id = $row['location_id'];

        $data_arr1[$location_id] = Round($row['target'] / $row['consumption'] * 100, 2);
    }
    
  
    $query_11 = $this->wastageReports()->wTotal(43, 1, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);
    foreach ($query_11 as $row) {

        $location_id = $row['location_id'];

        $data_arr1[$location_id] = Round($row['target'] / $row['consumption'] * 100, 2);
    }
 
    $query_51 = $this->wastageReports()->wTotal(40, 1, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_51 as $row) {

        $location_id = $row['location_id'];

        $data_arr1[$location_id] = Round($row['target'] / $row['consumption'] * 100, 2);
    }





    $query_571 = $this->wastageReports()->wTotal(7, 1, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_571 as $row) {

        $location_id = $row['location_id'];



        $data_arr1[$location_id] = Round($row['target'] / $row['consumption'] * 100, 2);
    }

    $query_671 = $this->wastageReports()->wTotal(8, 2, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_671 as $row) {

        $location_id = $row['location_id'];


        $data_arr1[$location_id] = Round($row['target'] / $row['consumption'] * 100, 2);
    }



    $query_71 = $this->wastageReports()->wTotal(9, 1, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_71 as $row) {

        $location_id = $row['location_id'];


        $data_arr1[$location_id] = Round($row['target'] / $row['consumption'] * 100, 2);
    }
    $query_81 = $this->wastageReports()->wTotal(12, 2, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_81 as $row) {

        $location_id = $row['location_id'];


        $data_arr1[$location_id] = Round($row['target'] / $row['consumption'] * 100, 2);
    }

    $query_91 = $this->wastageReports()->wTotal(46, 2, $wh_type, $year, $month, $from_sel_month, $from_sel_year, $province, $sel_dist, $sel_tehsil, $report_type, $province_sel);



    foreach ($query_91 as $row) {

        $location_id = $row['location_id'];


        $data_arr1[$location_id] = Round($row['target'] / $row['consumption'] * 100, 2);
    }
   
}
?>
<?php
$report_title = $this->report_title;
if (!empty($sel_month)) {
    $report_month = date('F', mktime(0, 0, 0, $sel_month));
} else {
    $report_month = "";
}
?>

<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $report_title; ?></h3>


        <div class="row">
            <table width="99%">
                <tr>
                    <td colspan="2">
                        <?php echo $this->render('wastage/header_coverage_report.phtml') ?>
                    </td>
                </tr>
            </table>
            <div class="col-md-12 right">

                <img src="<?php echo $this->baseUrl(); ?>/images/excel-32.png" onClick="tableToExcel('export', 'sheet 1', 'Antigen')" alt="Excel" style="cursor:pointer;" />
            </div>
        </div>
        <div>
            &nbsp; &nbsp; &nbsp;
        </div>
        <div class="row" id="export">
            <style>
                table#myTable{margin-top:0px !important; color: #000;}
                table#myTable{margin-top:20px;border-collapse: collapse;border-spacing: 0; border:1px solid #999;}
                table#myTable tr td{font-size:11px;padding:3px; text-align:left; border:1px solid #ddd; color: #000;}
                table#myTable tr:nth-child(even){background-color: #f2f2f2;}

                table#myTable tr:hover {background-color: #ddd;}
                table#myTable tr th{
                    font-size:11px;
                    padding-top: 12px;
                    padding-bottom: 12px;
                    text-align: center;
                    background-color: white;
                    border:2px solid #ddd;
                    color: black;}
                table#myTable tr td.TAR{text-align:right; padding:5px;width:50px !important;}
                .sb1NormalFont {color: #444444; font-size: 11px; font-weight: bold; text-decoration: none;}
                p{margin-bottom:5px; font-size:11px !important; line-height:1 !important; padding:0 !important; color: #000;}
                table#headerTable tr td{ font-size:11px; color: #000;}
                h4{margin:0; color: #000; font-size:14px;}
                h5{margin:15px 0 5px 0; color: #000;}
                h6{margin:0; color: #000; font-size:12px;}
                .right{text-align:right !important;}
                .center{text-align:center !important;}

                /* Print styles */
                @media only print
                {
                    table#myTable{margin-top:0px !important;}
                    table#myTable tr th{font-size:8px;padding:3px !important; text-align:center; border:1px solid #999; color: #000;}
                    table#myTable tr td{font-size:8px;padding:3px !important; text-align:left; border:1px solid #999; color: #000;}
                    #doNotPrint{display: none !important;}
                    h4{margin:0; color: #000;}
                    h5{margin:0; color: #000;}
                    h6{margin:0; color: #000;}
                    p{margin-bottom:5px; font-size:11px !important; line-height:1 !important; padding:0 !important; color: #000;}
                }
            </style>


            <script>
                function printContents() {
                    var w = 900;
                    var h = screen.height;
                    var left = Number((screen.width / 2) - (w / 2));
                    var top = Number((screen.height / 2) - (h / 2));
                    var dispSetting = "toolbar=yes,location=no,directories=yes,menubar=yes,scrollbars=yes,left=" + left + ",top=" + top + ",width=" + w + ",height=" + h;
                    var printingContents = document.getElementById("export").innerHTML;
                    var docprint = window.open("", "", dispSetting);
                    docprint.document.open();
                    docprint.document.write('<html><head>');
                    docprint.document.write('</head><body onLoad="self.print();self.close();"><center>');
                    docprint.document.write(printingContents);
                    docprint.document.write('</center></body></html>');
                    docprint.document.close();
                    docprint.focus();
                }

            </script>

            <div class="innerLR" style="overflow:auto;">
                <table width="100%" >
                    <tr>
                        <td >

                            <h4 class="center">
                                <?php echo "<b>EXPANDED PROGRAMME ON IMMUNIZATION</b> <br>District wise wastage rate of all the vaccines<br> <b> " . date('F', mktime(0, 0, 0, $this->from_month_sel, 1)) . ' - ' . date('F', mktime(0, 0, 0, $this->month_sel, 1)) . ', ' . $this->from_year_sel; ?>
                            </h4></td>
                    </tr>
                    <tr>
                        <td style="padding-top: 10px;">
                            <table id="myTable" style="width:100%" cellspacing="0" align="center">
                                <thead>


                                    <tr>
                                        <th rowspan="2" width="5%">Sr.No.</th>

                                        <th rowspan="2" width="15%">District</th>

                                        <?php
                                        $w1 = '10%';
                                        $w2 = '10%';
                                        $w2_ = '10%';
                                        $w3 = '10%';
                                        ?>
                                    </tr>
                                    <tr>
                                        <th style='text-align:center;'    width="<?php echo $w1; ?>">BCG 50% </th>

                                        <th style='text-align:center;'  width="<?php echo $w1; ?>">OPV 20%</th>
                                        <th  style='text-align:center;'  width="<?php echo $w1; ?>">IPV 10%</th>

                                        <th   style='text-align:center;'  width="<?php echo $w1; ?>">Penta 5%</th>


                                        <th  style='text-align:center;' width="<?php echo $w1; ?>">PCV10 10%</th>
                                        <th style='text-align:center;'  width="<?php echo $w1; ?>">Measles 20%</th>
                                        <th style='text-align:center;'  width="<?php echo $w1; ?>">TT 20%</th>
                                        <th style='text-align:center;'  width="<?php echo $w1; ?>">Rota 5%</th>



                                    </tr>






                                </thead>
                                <tbody>
                                    <?php
                                    $c = array(2 => 50, 3 => 20, 4 => 10, 5 => 5, 6 => 10, 7 => 20, 8 => 20, 9 => 5);
                                    foreach ($data_arr as $dis_id => $sub_arr) {
                                        ?>
                                        <tr>
                                            <?php
                                            if ($wh_type == 2) {
                                                ?>
                                                <td><?php echo $sub_arr[0]; ?></td>
                                                <td><?php echo $sub_arr[1]; ?></td>
                                                <?php
                                            } else if ($wh_type == 4) {
                                                ?>
                                                <td><?php echo $sub_arr[0]; ?></td>
                                                <td><?php echo $sub_arr[1]; ?></td>


                                                <?php
                                            }

                                            foreach ($sub_arr as $key => $value) {

                                                if (!isset($sum_arr[$key])) {
                                                    $sum_arr[$key] = 0;
                                                }
                                                $sum_arr[$key] += $value;

                                                if ($wh_type == 4) {


                                                    if ($key > 1) {
                                                        if ($value >= $c[$key]) {
                                                            $co = "#f1948a";
                                                        } else if ($value <= $c[$key]) {
                                                            $co = "#d4efdf";
                                                        } else if ($value < 0) {
                                                            $co = "#fcf3cf";
                                                        } else {
                                                            $co = "#d4efdf";
                                                        }
                                                        ?>
                                                        <td style="text-align:right;" bgcolor="<?php echo $co; ?>"><?php echo $value; ?></td>

                                                        <?php
                                                    }
                                                }
                                            }
                                            ?>
                                        </tr>
                                        <?php
                                    }
                                    ?>

                                    <?php
// To show Total
                                    array_shift($sum_arr);
                                    ?>
                                    <tr>
                                        <?php if ($wh_type == 2) {
                                            ?>
                                            <td></td>


                                        <?php } else if ($wh_type == 4) {
                                            ?>

                                            <td></td>

                                        <?php }
                                        ?>
                                        <td style="font-weight:bold; text-align: right;"><?php if ($wh_type == 2) { ?>Pakistan <?php } else { ?>Total<?php }php ?></td>
                                        <?php
                                         $c1 = array(6 => 50, 43 => 20, 40 => 10, 7 => 5, 8 => 10, 9 => 20, 12 => 20, 45 => 5);
                                        foreach ($data_arr1 as $key => $value1) {
                                           
                                                if ($wh_type == 4 && $sel_item == 'all') {
                                                    if ($value1 >= $c1[$key]) {
                                                            $co1 = "#f1948a";
                                                        } else if ($value1 <= $c1[$key]) {
                                                            $co1 = "#d4efdf";
                                                        } else if ($value1 < 0) {
                                                            $co1 = "#fcf3cf";
                                                        } else {
                                                            $co1 = "#d4efdf";
                                                        }
                                                        ?>
                                                        <td style="text-align:right; font-weight:bold" bgcolor="<?php echo $co1; ?>"><?php echo $value1; ?></td>


                                                        <?php
                                                   
                                                
                                            }
                                        }
                                        ?>
                                    </tr>

                                </tbody>
                            </table></td>
                    </tr>

                </table>

            </div>
        </div>
    </div>

</div>

<script>

    var whType = <?php echo $wh_type; ?>;
    var province = <?php echo $sel_prov; ?>;
    var district = <?php echo $sel_dist; ?>;
    var tehsil = <?php echo $sel_tehsil; ?>;

</script>


