<style>
    .page-content{
          background-image:none !important;
    }
</style>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="innerLR">
<div class="row">
    <div class="col-md-12">
        <h2>Ex Works – What is Ex Works?</h2>
        <div>Ex Works are a type of <a style="color:blue" href="https://www.tradefinanceglobal.com/freight-forwarding/incoterms/">Incoterm</a> (International Commercial Terms), defined by the International Chamber of Commerce.</div>
        <img src="<?php echo $this->baseUrl(); ?>/images/epi.png" class="img-thumbnail"style="height:77%;width:77%">
        <div><br>Responsibility of the Buyer (versus Seller)<br><br>Relative Price<br><br><b>Transport Modes:</b><br><br>Rail,<a style="color:blue"  href="https://www.tradefinanceglobal.com/freight-forwarding/ocean-freight/"> Sea</a>, <a style="color:blue" href="https://www.tradefinanceglobal.com/freight-forwarding/air-freight/">Air</a>, Road</div>
        <div><br><b>Ex Works</b> is a rule making the seller (or shipper / supplier) of goods responsible for packaging <br>and leaving the goods at their factory or place of manufacture.<br><br>The buyer (or consignee) is then responsible for everything else:
            <br>§ Loading goods onto transport<br>§ Transporting goods to a port or terminal<br>
            § Shipping the goods<br>
            § Unloading the goods at the buyer’s port or terminal<br>
            § Transporting the goods to the end destination or warehouse<br><br>
            Ex Works can be complex and problematic for a buyer importing goods from overseas, given that they<br> will still need the seller’s communication or authority to pass goods through customs or provide<br> documentation to freight parties along the way.<br><br>
            In Ex Works, the buyer is responsible for everything from the point of the goods being made available,<br> so diligent and detailed planning is advised.<br><br>
            Ex Works is preferable for domestic (in market) transportation of goods, and the buyer can use their<br> preferred freight forwarders or logistics partners to arrange the transport, potentially being cheaper<br> than the seller arranging the entire delivery process.<br><br>
        </div>
        <br>

        <h3>Delivery at Place – What is DAP?</h3>
        <div>DAP, or, Delivery at Place is an incoterm defining the buyer and seller’s responsibilities when moving <br>goods. In this case, the seller is responsible for moving the goods from the country of origin right <br>through to the end destination, which includes responsibility for loading, transport and unloading. With <br>DAP, we’d recommend being very clear about the end destination place to avoid any confusion later on. <br>DAP means that seller bears the risk of any issues with the goods until the agreed delivery point. If there <br>are any extra fees for unloading the goods, the seller must incur these.</div>
        <div>
            <br><br>
            This term can be used for any mode of transportation.<br>
            <img src="<?php echo $this->baseUrl(); ?>/images/dap.png" class="img-thumbnail" style="height:68%;width:68%">
        </div>
        <br>
        <br>
        <br>
    </div>
</div>
                </div>
    </div>
</div>
