<table class="table table-striped table-bordered table-hover dataTable no-footer" id="sample_2">
    <!-- Table heading -->
    <?php
    $fields = array(
        's_no' => 'S.No',
        'province' => 'Province',
        'district' => 'District',
        'tehsil' => 'Tehsil',
        'UC' => 'UC',
        'store/facility' => 'Store/facility',
        'c_status' => 'Current Status',
        'ch_status' => 'Change Status'
    );
    $this->tableHeading($this->order, $this->sort, $fields);
    ?>
    <!-- // Table heading END -->
    <!-- Table body -->

    <!-- // Table body END -->
    <tbody>
        <?php
        $m_res = array();
        $i = 1;

        if ($this->result && count($this->result) > 0) :
            foreach ($this->result as $row):
                ?>
                <tr class="<?php
                if ($row['warehouseName'] == $this->locations_add && $this->action == 1) {
                    echo 'danger';
                } else if ($row['warehouseName'] == $this->locations_edit && $this->action == 2) {
                    echo 'danger';
                }
                ?>">
                    <td class="center" width="25"> <?php
                        if ($row['warehouseName'] == $this->locations_add && $this->action == '1') {
                            echo "<span class='label label-sm label-info'>New</span>";
                        } else if ($row['warehouseName'] == $this->locations_edit && $this->action == '2') {
                            echo "<span class='label label-sm label-info'>Edited</span>";
                        }
                        ?> <?php echo $i; ?></td>


                    <td><?php echo $row['provinceName']; ?></td>
                    <td><?php echo $row['districtName']; ?></td>
                   
                    <td><?php echo $row['tehsilName']; ?></td>
 		<td><?php echo $row['UC']; ?></td>
                    <td><?php echo $row['warehouseName']; ?></td>

                    <td>
                        <?php
                        if ($row['status'] == 1) {
                            ?>
                            <p id="<?php echo 's_' . $row['pkId']; ?>"> Active     </p>

                        <?php } elseif ($row['status'] == 0) {
                            ?>
                            <p id="<?php echo 's_' . $row['pkId']; ?>"> In-Active     </p>
                            <?php
                        }
                        ?>
                    </td>

                    <td>
                        <?php if ($row['status'] == 1) { ?>
                            <a id="<?php echo $row['pkId']; ?>" class="active btn btn-link btn-danger input-sm"><?php echo $this->translate("Deactivate"); ?></a>
                        <?php } else { ?>
                            <a id="<?php echo $row['pkId']; ?>" class="deactivate btn btn-link btn-danger input-sm"><?php echo $this->translate("Activate"); ?></a>
                        <?php } ?>
                    </td>
                    <td>
                        <?php if ($this->role_id != 39) { ?>
                            <a itemid="<?php echo $row['pkId']; ?>" class="update-stores btn btn-xs green" data-toggle="modal" href="#modal-update-stores"><i class="fa fa-edit"></i><?php echo $this->translate("Edit") ?></a>
                                <?php //if ($this->warehouseDelete($row['pkId'])) {  ?>
                                <?php //} else {  ?> 
                                <?php //}  ?>
                            <?php } ?>
                    </td>

                    <!-- // Table row END --><?php
                    $i++;
                endforeach;
            endif;
            ?>
    </tbody>
</table>