`<?php
/**
 *  phtml for Routine
 */
?>
<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Manage Stores/Facilities (Routine)") ?> </h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Stores/Facilities Search") ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" name="asset_sub_type_search" action="" id="locations">
                                    <!-- Row -->


                                    <div class="row">

                                        <?php echo $this->routineCombo($this->combos, $this->warehouse_id, $this->role_id); ?>

                                        <?php echo $this->form->province_id; ?>
                                        <?php echo $this->form->district_id; ?>
                                        <?php echo $this->form->tehsil_id; ?>
                                        <?php echo $this->form->parent_id; ?>
                                        <input type="hidden" name="hdn_warehouse_id" id="hdn_warehouse_id" value="<?php echo $this->warehouse_id; ?>">
                                        <input type="hidden" name="hdn_role_id" id="hdn_role_id" value="<?php echo $this->role_id; ?>">
                                        <input type="hidden" name="location_name_hdn" id="location_name_hdn" value="">
                                        <input type="hidden" name="location_name_edit_hdn" id="location_name_edit_hdn" value="">
                                        <input type="hidden" name="action_hdn" id="action_hdn" value="">

                                    </div>
                                    <br>
                                    <br>
                                    <div class="row">
                                        <div class="col-md-10">
                                        </div>
                                        <div class="col-md-2">

                                            <button data-loading-text="Searching"  class="btn btn-sm green btn-outline filter-submit" type="button" name="search" id="search" ><i class="fa fa-search"></i>
                                                <?php echo $this->translate("Search") ?></button>
                                            <button type="reset" class="btn btn-sm default btn-outline filter-cancel" id="reset"><i class="fa fa-times"></i>
                                                Reset</button>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Stores/Facilities List") ?>
                        </div>
                        <div class="actions">
                            <a  class="btn btn-default btn-sm"  data-toggle="modal" href="#add-store">
                                <i class="fa fa-plus"></i> <?php echo $this->translate("Add Store/Facility") ?> </a>

                        </div>
                        <div class="tools">

                            <a href="javascript:;" class="reload" style="visibility: hidden"></a>

                        </div>


                    </div>
                    <div class="portlet-body">
                        <div class="dataTables_wrapper form-inline" id="ajax-table">

                            <!--                                <div class="col-md-3">
                                                            </div>-->


                            <br><br>
                            <table class="table table-striped table-bordered table-hover dataTable no-footer" id="sample_2">
                                <!-- Table heading -->
                                <?php
                                $fields = array(
                                    's_no' => 'S.No',
                                    'province' => 'Province',
                                    'district' => 'District',
                                    'tehsil' => 'Tehsil',
                                    'UC' => 'UC',
                                    'store/facility' => 'Store/facility',
                                    'c_status' => 'Current Status',
                                    'ch_status' => 'Change Status'
                                );
                                $this->tableHeading($this->order, $this->sort, $fields);
                                ?>
                                <!-- // Table heading END -->
                                <!-- Table body -->

                                <!-- // Table body END -->
                                <tbody>
                                    <?php
                                    $m_res = array();
                                    $i = 1;

                                    if ($this->result && count($this->result) > 0) :
                                        foreach ($this->result as $row):
                                            ?>
                                            <tr class="<?php if ($i % 2 == 0) { ?>gradeX even<?php } else { ?> gradeA odd<?php } ?>">
                                                <td class="center" width="25"><?php echo $i; ?></td>
                                                <td><?php echo $row['provinceName']; ?></td>
                                                <td><?php echo $row['districtName']; ?></td>
                                                <td><?php echo $row['tehsilName']; ?></td>
                                                <td><?php echo $row['UC']; ?></td>
                                                <td><?php echo $row['warehouseName']; ?></td>
                                                <td>
                                                    <?php
                                                    if ($row['status'] == 1) {
                                                        ?>
                                                        <p id="<?php echo 's_' . $row['pkId']; ?>"> Active     </p>

                                                    <?php } elseif ($row['status'] == 0) {
                                                        ?>
                                                        <p id="<?php echo 's_' . $row['pkId']; ?>"> In-Active     </p>
                                                        <?php
                                                    }
                                                    ?>
                                                </td>
                                                <td>
                                                    <?php if ($row['status'] == 1) { ?>
                                                        <a id="<?php echo $row['pkId']; ?>" class="active btn btn-link btn-danger input-sm"><?php echo $this->translate("Deactivate"); ?></a>
                                                    <?php } else { ?>
                                                        <a id="<?php echo $row['pkId']; ?>" class="deactivate btn btn-link btn-danger input-sm"><?php echo $this->translate("Activate"); ?></a>
                                                    <?php } ?>
                                                </td>
                                                <td>
                                                    <?php if ($this->role_id != 39) { ?>
                                                        <a itemid="<?php echo $row['pkId']; ?>" class="update-stores btn btn-xs green" data-toggle="modal" href="#modal-update-stores"><i class="fa fa-edit"></i><?php echo $this->translate("Edit") ?></a>
                                                        <?php //if ($this->warehouseDelete($row['pkId'])) { ?>
                                                        <?php //} else { ?>

                                                        <?php // } ?>
                                                    <?php } ?>

                                                </td>

                                                <!-- // Table row END --><?php
                                                $i++;
                                            endforeach;
                                        endif;
                                        ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- // modal box for add -->
        <form method="post" action="#" id="add-stores">
            <div class="modal fade" id="add-store" tabindex="-1" role="basic" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Add Stores/Facilities</h3>
                        </div>

                        <div class="modal-body">
                            <div class="row">
                                <?php echo $this->routineAddCombo($this->combos_1, $this->warehouse_id, $this->role_id); ?>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Type"); ?></label>
                                        <div class="controls">
                                            <?php echo $this->form->warehouse_type; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4" id="div_warehouse_type" style="display:none">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Warehouse Type"); ?></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" name="warehouse_type_other" id="warehouse_type_other">
                                        </div>
                                    </div>
                                </div>


                                <div class="col-md-4">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Store/Facility"); ?></label>
                                        <div class="controls">
                                            <?php echo $this->form->store_name_add; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("CCM Code"); ?></label>
                                        <div class="controls">
                                            <?php echo $this->form->ccm_warehouse_id; ?>
                                        </div>
                                    </div>
                                </div>


                                <div class="col-md-4">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Store Establishment Date"); ?></label>
                                        <div class="controls">
                                            <?php echo $this->form->starting_on; ?>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="control-group ">
                                        <label class="control-label" ><?php echo $this->translate("Reporting Start Date"); ?></label>
                                        <div class="controls">
                                            <?php echo $this->form->from_edit; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="control-group ">
                                        <label class="control-label"  ><?php echo $this->translate("Population") . " (" . date('Y') . ")"; ?><span class="red">*</span></label>
                                        <div class="controls">
                                            <?php echo $this->form->population; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button data-loading-text="Adding" class="btn btn-primary" type="submit" id="add" ><?php echo $this->translate("Add"); ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <!-- // modal box for update -->
        <form method="post" action="#" id="update-stores">
            <div class="modal fade" id="modal-update-stores" tabindex="-1" role="basic" aria-hidden="true" >
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Edit Stores/Facilities</h3>
                        </div>

                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer " id="update-button">
                            <button data-loading-text="Updating" class="btn btn-primary" type="submit" id="update" ><?php echo $this->translate("Update"); ?></button>

                        </div>
                    </div>
                </div>
            </div>
        </form>


        <form method="post" action="#" id="update-status">
            <div class="modal fade" id="modal-update-stores" tabindex="-1" role="basic" aria-hidden="true" >
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3>Update Status</h3>
                        </div>

                        <div class="modal-body" id="modal-body-contents">
                            <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                        </div>
                        <div class="modal-footer " id="update-button">
                            <button data-loading-text="Updating" class="btn btn-primary" type="submit" id="update" ><?php echo $this->translate("Update"); ?></button>

                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- // Content END -->
